-- Initial Category Data for New Users
-- Auto-generated from migrate_categories.sql and migrate_categories_i18n.sql
-- Uses new code format: EXPENSE, C2_E_xxx, C3_E_xxx
-- NOTE: Replace :pUserID with actual user_id when using this SQL

-- ============================================================================
-- CATEGORY2 (中分類)
-- ============================================================================

-- 食費
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 1, '食費', 0, datetime('now'), NULL);

-- 日用雑貨
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_2', 2, '日用雑貨', 0, datetime('now'), NULL);

-- 交通費
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 3, '交通費', 0, datetime('now'), NULL);

-- 通信
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_4', 4, '通信', 0, datetime('now'), NULL);

-- 娯楽
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 5, '娯楽', 0, datetime('now'), NULL);

-- 教養
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_6', 6, '教養', 0, datetime('now'), NULL);

-- 美容・健康
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 7, '美容・健康', 0, datetime('now'), NULL);

-- 医療
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_8', 8, '医療', 0, datetime('now'), NULL);

-- 保険・年金
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 9, '保険・年金', 0, datetime('now'), NULL);

-- 光熱費
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_10', 10, '光熱費', 0, datetime('now'), NULL);

-- 住居
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 11, '住居', 0, datetime('now'), NULL);

-- 税金
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_12', 12, '税金', 0, datetime('now'), NULL);

-- 大型出費
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 13, '大型出費', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_14', 14, 'その他', 0, datetime('now'), NULL);

-- 給与
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_1', 1, '給与', 0, datetime('now'), NULL);

-- 賞与
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_2', 2, '賞与', 0, datetime('now'), NULL);

-- 年金
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_3', 3, '年金', 0, datetime('now'), NULL);

-- 支給金
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_4', 4, '支給金', 0, datetime('now'), NULL);

-- 保険金
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_5', 5, '保険金', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_6', 6, 'その他', 0, datetime('now'), NULL);


-- ============================================================================
-- CATEGORY2_I18N (中分類 - 多言語)
-- ============================================================================

-- Food (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'en', 'Food', datetime('now'), NULL);

-- Daily Necessities (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_2', 'en', 'Daily Necessities', datetime('now'), NULL);

-- Transportation (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'en', 'Transportation', datetime('now'), NULL);

-- Communication (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_4', 'en', 'Communication', datetime('now'), NULL);

-- Entertainment (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'en', 'Entertainment', datetime('now'), NULL);

-- Education (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_6', 'en', 'Education', datetime('now'), NULL);

-- Beauty & Health (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'en', 'Beauty & Health', datetime('now'), NULL);

-- Medical (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_8', 'en', 'Medical', datetime('now'), NULL);

-- Insurance & Pension (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 'en', 'Insurance & Pension', datetime('now'), NULL);

-- Utilities (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_10', 'en', 'Utilities', datetime('now'), NULL);

-- Housing (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 'en', 'Housing', datetime('now'), NULL);

-- Tax (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_12', 'en', 'Tax', datetime('now'), NULL);

-- Large Expenses (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'en', 'Large Expenses', datetime('now'), NULL);

-- Other (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_14', 'en', 'Other', datetime('now'), NULL);

-- Salary (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_1', 'en', 'Salary', datetime('now'), NULL);

-- Bonus (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_2', 'en', 'Bonus', datetime('now'), NULL);

-- Pension (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_3', 'en', 'Pension', datetime('now'), NULL);

-- Subsidy (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_4', 'en', 'Subsidy', datetime('now'), NULL);

-- Insurance (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_5', 'en', 'Insurance', datetime('now'), NULL);

-- Other (en)
INSERT INTO CATEGORY2_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_6', 'en', 'Other', datetime('now'), NULL);


-- ============================================================================
-- CATEGORY3 (小分類)
-- ============================================================================

-- 食料品
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_1', 1, '食料品', 0, datetime('now'), NULL);

-- 飲料
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_2', 2, '飲料', 0, datetime('now'), NULL);

-- 朝食
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_3', 3, '朝食', 0, datetime('now'), NULL);

-- 昼食
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_4', 4, '昼食', 0, datetime('now'), NULL);

-- 夕食
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_5', 5, '夕食', 0, datetime('now'), NULL);

-- 夜食
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_6', 6, '夜食', 0, datetime('now'), NULL);

-- 中食(ブランチなど)
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_7', 7, '中食(ブランチなど)', 0, datetime('now'), NULL);

-- 外食
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_8', 8, '外食', 0, datetime('now'), NULL);

-- 嗜好品
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_9', 9, '嗜好品', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_10', 10, 'その他', 0, datetime('now'), NULL);

-- 消耗品
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_2', 'C3_E_2_1', 1, '消耗品', 0, datetime('now'), NULL);

-- 子ども関連
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_2', 'C3_E_2_2', 2, '子ども関連', 0, datetime('now'), NULL);

-- タバコ
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_2', 'C3_E_2_3', 3, 'タバコ', 0, datetime('now'), NULL);

-- ペット関連
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_2', 'C3_E_2_4', 4, 'ペット関連', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_2', 'C3_E_2_5', 5, 'その他', 0, datetime('now'), NULL);

-- バス
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_1', 1, 'バス', 0, datetime('now'), NULL);

-- 電車
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_2', 2, '電車', 0, datetime('now'), NULL);

-- タクシー
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_3', 3, 'タクシー', 0, datetime('now'), NULL);

-- 飛行機
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_4', 4, '飛行機', 0, datetime('now'), NULL);

-- 電子マネー
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_5', 5, '電子マネー', 0, datetime('now'), NULL);

-- 自動車(ガソリン代など)
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_6', 6, '自動車(ガソリン代など)', 0, datetime('now'), NULL);

-- バイク(ガソリン代など)
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_7', 7, 'バイク(ガソリン代など)', 0, datetime('now'), NULL);

-- 自転車(駐輪代など)
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_8', 8, '自転車(駐輪代など)', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_9', 9, 'その他', 0, datetime('now'), NULL);

-- 携帯電話
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_4', 'C3_E_4_1', 1, '携帯電話', 0, datetime('now'), NULL);

-- 固定回線/IP(固定)電話
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_4', 'C3_E_4_2', 2, '固定回線/IP(固定)電話', 0, datetime('now'), NULL);

-- インターネット関連
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_4', 'C3_E_4_3', 3, 'インターネット関連', 0, datetime('now'), NULL);

-- 放送サービス
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_4', 'C3_E_4_4', 4, '放送サービス', 0, datetime('now'), NULL);

-- 郵便
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_4', 'C3_E_4_5', 5, '郵便', 0, datetime('now'), NULL);

-- 宅配便
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_4', 'C3_E_4_6', 6, '宅配便', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_4', 'C3_E_4_7', 7, 'その他', 0, datetime('now'), NULL);

-- 映画・動画
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_1', 1, '映画・動画', 0, datetime('now'), NULL);

-- 音楽
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_2', 2, '音楽', 0, datetime('now'), NULL);

-- 演劇
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_3', 3, '演劇', 0, datetime('now'), NULL);

-- スポーツ
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_4', 4, 'スポーツ', 0, datetime('now'), NULL);

-- 書籍
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_5', 5, '書籍', 0, datetime('now'), NULL);

-- 漫画
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_6', 6, '漫画', 0, datetime('now'), NULL);

-- ゲーム
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_7', 7, 'ゲーム', 0, datetime('now'), NULL);

-- イベント
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_8', 8, 'イベント', 0, datetime('now'), NULL);

-- レジャー
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_9', 9, 'レジャー', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_10', 10, 'その他', 0, datetime('now'), NULL);

-- 書籍
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_6', 'C3_E_6_1', 1, '書籍', 0, datetime('now'), NULL);

-- 塾
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_6', 'C3_E_6_2', 2, '塾', 0, datetime('now'), NULL);

-- 習い事
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_6', 'C3_E_6_3', 3, '習い事', 0, datetime('now'), NULL);

-- 講習会
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_6', 'C3_E_6_4', 4, '講習会', 0, datetime('now'), NULL);

-- 新聞
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_6', 'C3_E_6_5', 5, '新聞', 0, datetime('now'), NULL);

-- 試験
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_6', 'C3_E_6_6', 6, '試験', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_6', 'C3_E_6_7', 7, 'その他', 0, datetime('now'), NULL);

-- 化粧品
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_1', 1, '化粧品', 0, datetime('now'), NULL);

-- 衣類
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_2', 2, '衣類', 0, datetime('now'), NULL);

-- 小物
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_3', 3, '小物', 0, datetime('now'), NULL);

-- アクセサリー
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_4', 4, 'アクセサリー', 0, datetime('now'), NULL);

-- 食品・サプリメント
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_5', 5, '食品・サプリメント', 0, datetime('now'), NULL);

-- コインランドリー
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_6', 6, 'コインランドリー', 0, datetime('now'), NULL);

-- 美容院・理容院
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_7', 7, '美容院・理容院', 0, datetime('now'), NULL);

-- ジム
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_8', 8, 'ジム', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_9', 9, 'その他', 0, datetime('now'), NULL);

-- 病院
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_8', 'C3_E_8_1', 1, '病院', 0, datetime('now'), NULL);

-- 薬
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_8', 'C3_E_8_2', 2, '薬', 0, datetime('now'), NULL);

-- 医療器具
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_8', 'C3_E_8_3', 3, '医療器具', 0, datetime('now'), NULL);

-- 食品
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_8', 'C3_E_8_4', 4, '食品', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_8', 'C3_E_8_5', 5, 'その他', 0, datetime('now'), NULL);

-- 健康保険
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 'C3_E_9_1', 1, '健康保険', 0, datetime('now'), NULL);

-- 国民年金
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 'C3_E_9_2', 2, '国民年金', 0, datetime('now'), NULL);

-- 共済保険
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 'C3_E_9_3', 3, '共済保険', 0, datetime('now'), NULL);

-- 医療保険
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 'C3_E_9_4', 4, '医療保険', 0, datetime('now'), NULL);

-- 終身保険
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 'C3_E_9_5', 5, '終身保険', 0, datetime('now'), NULL);

-- 携帯保険(故障・紛失補償など)
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 'C3_E_9_6', 6, '携帯保険(故障・紛失補償など)', 0, datetime('now'), NULL);

-- 車両保険
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 'C3_E_9_7', 7, '車両保険', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 'C3_E_9_8', 8, 'その他', 0, datetime('now'), NULL);

-- 電気代
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_10', 'C3_E_10_1', 1, '電気代', 0, datetime('now'), NULL);

-- ガス代
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_10', 'C3_E_10_2', 2, 'ガス代', 0, datetime('now'), NULL);

-- 水道代
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_10', 'C3_E_10_3', 3, '水道代', 0, datetime('now'), NULL);

-- 薪代
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_10', 'C3_E_10_4', 4, '薪代', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_10', 'C3_E_10_5', 5, 'その他', 0, datetime('now'), NULL);

-- 家賃
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 'C3_E_11_1', 1, '家賃', 0, datetime('now'), NULL);

-- 管理・共益費
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 'C3_E_11_2', 2, '管理・共益費', 0, datetime('now'), NULL);

-- 修繕費
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 'C3_E_11_3', 3, '修繕費', 0, datetime('now'), NULL);

-- リフォーム代
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 'C3_E_11_4', 4, 'リフォーム代', 0, datetime('now'), NULL);

-- 引越代
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 'C3_E_11_5', 5, '引越代', 0, datetime('now'), NULL);

-- 敷金
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 'C3_E_11_6', 6, '敷金', 0, datetime('now'), NULL);

-- 礼金
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 'C3_E_11_7', 7, '礼金', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 'C3_E_11_8', 8, 'その他', 0, datetime('now'), NULL);

-- 消費税
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_12', 'C3_E_12_1', 1, '消費税', 0, datetime('now'), NULL);

-- 住民税
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_12', 'C3_E_12_2', 2, '住民税', 0, datetime('now'), NULL);

-- 固定資産税
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_12', 'C3_E_12_3', 3, '固定資産税', 0, datetime('now'), NULL);

-- 自動車税
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_12', 'C3_E_12_4', 4, '自動車税', 0, datetime('now'), NULL);

-- 法人税
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_12', 'C3_E_12_5', 5, '法人税', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_12', 'C3_E_12_6', 6, 'その他', 0, datetime('now'), NULL);

-- IT家電(PC・ガジェットなど)
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_1', 1, 'IT家電(PC・ガジェットなど)', 0, datetime('now'), NULL);

-- その他家電
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_2', 2, 'その他家電', 0, datetime('now'), NULL);

-- 家具
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_3', 3, '家具', 0, datetime('now'), NULL);

-- 什器
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_4', 4, '什器', 0, datetime('now'), NULL);

-- 冠婚葬祭
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_5', 5, '冠婚葬祭', 0, datetime('now'), NULL);

-- 出産
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_6', 6, '出産', 0, datetime('now'), NULL);

-- 介護
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_7', 7, '介護', 0, datetime('now'), NULL);

-- 旅行
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_8', 8, '旅行', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_9', 9, 'その他', 0, datetime('now'), NULL);

-- 電子マネーを使用
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_14', 'C3_E_14_1', 1, '電子マネーを使用', 0, datetime('now'), NULL);

-- 仕送り
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_14', 'C3_E_14_2', 2, '仕送り', 0, datetime('now'), NULL);

-- お小遣い
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_14', 'C3_E_14_3', 3, 'お小遣い', 0, datetime('now'), NULL);

-- お年玉
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_14', 'C3_E_14_4', 4, 'お年玉', 0, datetime('now'), NULL);

-- 立替金
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_14', 'C3_E_14_5', 5, '立替金', 0, datetime('now'), NULL);

-- 使途不明金
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_14', 'C3_E_14_6', 6, '使途不明金', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_14', 'C3_E_14_7', 7, 'その他', 0, datetime('now'), NULL);

-- 報酬
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_1', 'C3_I_1_1', 1, '報酬', 0, datetime('now'), NULL);

-- アルバイト・パート代
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_1', 'C3_I_1_2', 2, 'アルバイト・パート代', 0, datetime('now'), NULL);

-- 講師代
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_1', 'C3_I_1_3', 3, '講師代', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_1', 'C3_I_1_4', 4, 'その他', 0, datetime('now'), NULL);

-- 夏季賞与
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_2', 'C3_I_2_1', 1, '夏季賞与', 0, datetime('now'), NULL);

-- 冬季賞与
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_2', 'C3_I_2_2', 2, '冬季賞与', 0, datetime('now'), NULL);

-- 期末賞与
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_2', 'C3_I_2_3', 3, '期末賞与', 0, datetime('now'), NULL);

-- 臨時賞与
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_2', 'C3_I_2_4', 4, '臨時賞与', 0, datetime('now'), NULL);

-- 寸志
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_2', 'C3_I_2_5', 5, '寸志', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_2', 'C3_I_2_6', 6, 'その他', 0, datetime('now'), NULL);

-- 基礎年金
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_3', 'C3_I_3_1', 1, '基礎年金', 0, datetime('now'), NULL);

-- 厚生年金
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_3', 'C3_I_3_2', 2, '厚生年金', 0, datetime('now'), NULL);

-- 老齢年金
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_3', 'C3_I_3_3', 3, '老齢年金', 0, datetime('now'), NULL);

-- 遺族年金
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_3', 'C3_I_3_4', 4, '遺族年金', 0, datetime('now'), NULL);

-- 障害基礎年金
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_3', 'C3_I_3_5', 5, '障害基礎年金', 0, datetime('now'), NULL);

-- 障害厚生年金
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_3', 'C3_I_3_6', 6, '障害厚生年金', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_3', 'C3_I_3_7', 7, 'その他', 0, datetime('now'), NULL);

-- 医療保険
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_5', 'C3_I_5_1', 1, '医療保険', 0, datetime('now'), NULL);

-- 終身保険
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_5', 'C3_I_5_2', 2, '終身保険', 0, datetime('now'), NULL);

-- 車両保険
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_5', 'C3_I_5_3', 3, '車両保険', 0, datetime('now'), NULL);

-- その他
INSERT INTO CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_5', 'C3_I_5_4', 4, 'その他', 0, datetime('now'), NULL);


-- ============================================================================
-- CATEGORY3_I18N (小分類 - 多言語)
-- ============================================================================

-- Groceries (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_1', 'en', 'Groceries', datetime('now'), NULL);

-- Beverages (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_2', 'en', 'Beverages', datetime('now'), NULL);

-- Breakfast (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_3', 'en', 'Breakfast', datetime('now'), NULL);

-- Lunch (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_4', 'en', 'Lunch', datetime('now'), NULL);

-- Dinner (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_5', 'en', 'Dinner', datetime('now'), NULL);

-- Midnight Snack (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_6', 'en', 'Midnight Snack', datetime('now'), NULL);

-- Brunch (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_7', 'en', 'Brunch', datetime('now'), NULL);

-- Eating Out (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_8', 'en', 'Eating Out', datetime('now'), NULL);

-- Snacks (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_9', 'en', 'Snacks', datetime('now'), NULL);

-- Other (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_1', 'C3_E_1_10', 'en', 'Other', datetime('now'), NULL);


-- ============================================================================
-- Additional CATEGORY3_I18N (English translations) - 116 items
-- Categories C2_E_2 onwards
-- ============================================================================

-- 消耗品 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_2', 'C3_E_2_1', 'en', 'Consumables', datetime('now'), NULL);

-- 子ども関連 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_2', 'C3_E_2_2', 'en', 'Childcare', datetime('now'), NULL);

-- タバコ (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_2', 'C3_E_2_3', 'en', 'Tobacco', datetime('now'), NULL);

-- ペット関連 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_2', 'C3_E_2_4', 'en', 'Pet Care', datetime('now'), NULL);

-- その他 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_2', 'C3_E_2_5', 'en', 'Other', datetime('now'), NULL);

-- バス (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_1', 'en', 'Bus', datetime('now'), NULL);

-- 電車 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_2', 'en', 'Train', datetime('now'), NULL);

-- タクシー (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_3', 'en', 'Taxi', datetime('now'), NULL);

-- 飛行機 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_4', 'en', 'Airplane', datetime('now'), NULL);

-- 電子マネー (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_5', 'en', 'Electronic Money', datetime('now'), NULL);

-- 自動車(ガソリン代など) (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_6', 'en', 'Car (Gas, etc.)', datetime('now'), NULL);

-- バイク(ガソリン代など) (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_7', 'en', 'Motorcycle (Gas, etc.)', datetime('now'), NULL);

-- 自転車(駐輪代など) (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_8', 'en', 'Bicycle (Parking, etc.)', datetime('now'), NULL);

-- その他 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_3', 'C3_E_3_9', 'en', 'Other', datetime('now'), NULL);

-- 携帯電話 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_4', 'C3_E_4_1', 'en', 'Mobile Phone', datetime('now'), NULL);

-- 固定回線/IP(固定)電話 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_4', 'C3_E_4_2', 'en', 'Fixed Line/IP Phone', datetime('now'), NULL);

-- インターネット関連 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_4', 'C3_E_4_3', 'en', 'Internet', datetime('now'), NULL);

-- 放送サービス (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_4', 'C3_E_4_4', 'en', 'Broadcasting Service', datetime('now'), NULL);

-- 郵便 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_4', 'C3_E_4_5', 'en', 'Postal Service', datetime('now'), NULL);

-- 宅配便 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_4', 'C3_E_4_6', 'en', 'Delivery Service', datetime('now'), NULL);

-- その他 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_4', 'C3_E_4_7', 'en', 'Other', datetime('now'), NULL);

-- 映画・動画 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_1', 'en', 'Movies/Videos', datetime('now'), NULL);

-- 音楽 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_2', 'en', 'Music', datetime('now'), NULL);

-- 演劇 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_3', 'en', 'Theater', datetime('now'), NULL);

-- スポーツ (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_4', 'en', 'Sports', datetime('now'), NULL);

-- 書籍 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_5', 'en', 'Books', datetime('now'), NULL);

-- 漫画 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_6', 'en', 'Comics/Manga', datetime('now'), NULL);

-- ゲーム (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_7', 'en', 'Games', datetime('now'), NULL);

-- イベント (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_8', 'en', 'Events', datetime('now'), NULL);

-- レジャー (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_9', 'en', 'Leisure', datetime('now'), NULL);

-- その他 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_5', 'C3_E_5_10', 'en', 'Other', datetime('now'), NULL);

-- 書籍 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_6', 'C3_E_6_1', 'en', 'Books', datetime('now'), NULL);

-- 塾 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_6', 'C3_E_6_2', 'en', 'Cram School', datetime('now'), NULL);

-- 習い事 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_6', 'C3_E_6_3', 'en', 'Lessons', datetime('now'), NULL);

-- 講習会 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_6', 'C3_E_6_4', 'en', 'Workshop', datetime('now'), NULL);

-- 新聞 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_6', 'C3_E_6_5', 'en', 'Newspaper', datetime('now'), NULL);

-- 試験 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_6', 'C3_E_6_6', 'en', 'Examination', datetime('now'), NULL);

-- その他 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_6', 'C3_E_6_7', 'en', 'Other', datetime('now'), NULL);

-- 化粧品 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_1', 'en', 'Cosmetics', datetime('now'), NULL);

-- 衣類 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_2', 'en', 'Clothes', datetime('now'), NULL);

-- 小物 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_3', 'en', 'Accessories', datetime('now'), NULL);

-- アクセサリー (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_4', 'en', 'Jewelry', datetime('now'), NULL);

-- 食品・サプリメント (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_5', 'en', 'Food Supplements', datetime('now'), NULL);

-- コインランドリー (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_6', 'en', 'Coin Laundry', datetime('now'), NULL);

-- 美容院・理容院 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_7', 'en', 'Hair/Barber Shop', datetime('now'), NULL);

-- ジム (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_8', 'en', 'Gym', datetime('now'), NULL);

-- その他 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_7', 'C3_E_7_9', 'en', 'Other', datetime('now'), NULL);

-- 病院 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_8', 'C3_E_8_1', 'en', 'Hospital', datetime('now'), NULL);

-- 薬 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_8', 'C3_E_8_2', 'en', 'Medicine', datetime('now'), NULL);

-- 医療器具 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_8', 'C3_E_8_3', 'en', 'Medical Equipment', datetime('now'), NULL);

-- 食品 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_8', 'C3_E_8_4', 'en', 'Dietary Products', datetime('now'), NULL);

-- その他 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_8', 'C3_E_8_5', 'en', 'Other', datetime('now'), NULL);

-- 健康保険 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 'C3_E_9_1', 'en', 'Health Insurance', datetime('now'), NULL);

-- 国民年金 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 'C3_E_9_2', 'en', 'National Pension', datetime('now'), NULL);

-- 共済保険 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 'C3_E_9_3', 'en', 'Mutual Insurance', datetime('now'), NULL);

-- 医療保険 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 'C3_E_9_4', 'en', 'Medical Insurance', datetime('now'), NULL);

-- 終身保険 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 'C3_E_9_5', 'en', 'Life Insurance', datetime('now'), NULL);

-- 携帯保険(故障・紛失補償など) (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 'C3_E_9_6', 'en', 'Mobile Phone Insurance', datetime('now'), NULL);

-- 車両保険 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 'C3_E_9_7', 'en', 'Vehicle Insurance', datetime('now'), NULL);

-- その他 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_9', 'C3_E_9_8', 'en', 'Other', datetime('now'), NULL);

-- 電気代 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_10', 'C3_E_10_1', 'en', 'Electricity', datetime('now'), NULL);

-- ガス代 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_10', 'C3_E_10_2', 'en', 'Gas', datetime('now'), NULL);

-- 水道代 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_10', 'C3_E_10_3', 'en', 'Water', datetime('now'), NULL);

-- 薪代 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_10', 'C3_E_10_4', 'en', 'Firewood', datetime('now'), NULL);

-- その他 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_10', 'C3_E_10_5', 'en', 'Other', datetime('now'), NULL);

-- 家賃 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 'C3_E_11_1', 'en', 'Rent', datetime('now'), NULL);

-- 管理・共益費 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 'C3_E_11_2', 'en', 'Management/Common Fee', datetime('now'), NULL);

-- 修繕費 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 'C3_E_11_3', 'en', 'Repair Cost', datetime('now'), NULL);

-- リフォーム代 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 'C3_E_11_4', 'en', 'Renovation Cost', datetime('now'), NULL);

-- 引越代 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 'C3_E_11_5', 'en', 'Moving Cost', datetime('now'), NULL);

-- 敷金 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 'C3_E_11_6', 'en', 'Security Deposit', datetime('now'), NULL);

-- 礼金 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 'C3_E_11_7', 'en', 'Key Money', datetime('now'), NULL);

-- その他 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_11', 'C3_E_11_8', 'en', 'Other', datetime('now'), NULL);

-- 消費税 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_12', 'C3_E_12_1', 'en', 'Consumption Tax', datetime('now'), NULL);

-- 住民税 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_12', 'C3_E_12_2', 'en', 'Resident Tax', datetime('now'), NULL);

-- 固定資産税 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_12', 'C3_E_12_3', 'en', 'Property Tax', datetime('now'), NULL);

-- 自動車税 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_12', 'C3_E_12_4', 'en', 'Automobile Tax', datetime('now'), NULL);

-- 法人税 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_12', 'C3_E_12_5', 'en', 'Corporate Tax', datetime('now'), NULL);

-- その他 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_12', 'C3_E_12_6', 'en', 'Other', datetime('now'), NULL);

-- IT家電(PC・ガジェットなど) (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_1', 'en', 'IT Devices (PC/Gadgets)', datetime('now'), NULL);

-- その他家電 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_2', 'en', 'Other Appliances', datetime('now'), NULL);

-- 家具 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_3', 'en', 'Furniture', datetime('now'), NULL);

-- 什器 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_4', 'en', 'Equipment', datetime('now'), NULL);

-- 冠婚葬祭 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_5', 'en', 'Ceremonial Occasions', datetime('now'), NULL);

-- 出産 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_6', 'en', 'Childbirth', datetime('now'), NULL);

-- 介護 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_7', 'en', 'Nursing Care', datetime('now'), NULL);

-- 旅行 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_8', 'en', 'Travel', datetime('now'), NULL);

-- その他 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_13', 'C3_E_13_9', 'en', 'Other', datetime('now'), NULL);

-- 電子マネーを使用 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_14', 'C3_E_14_1', 'en', 'Electronic Money Usage', datetime('now'), NULL);

-- 仕送り (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_14', 'C3_E_14_2', 'en', 'Remittance', datetime('now'), NULL);

-- お小遣い (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_14', 'C3_E_14_3', 'en', 'Allowance', datetime('now'), NULL);

-- お年玉 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_14', 'C3_E_14_4', 'en', 'New Year''s Gift Money', datetime('now'), NULL);

-- 立替金 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_14', 'C3_E_14_5', 'en', 'Reimbursement', datetime('now'), NULL);

-- 使途不明金 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_14', 'C3_E_14_6', 'en', 'Unaccounted Expenses', datetime('now'), NULL);

-- その他 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'EXPENSE', 'C2_E_14', 'C3_E_14_7', 'en', 'Other', datetime('now'), NULL);

-- 報酬 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_1', 'C3_I_1_1', 'en', 'Compensation', datetime('now'), NULL);

-- アルバイト・パート代 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_1', 'C3_I_1_2', 'en', 'Part-time Job Pay', datetime('now'), NULL);

-- 講師代 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_1', 'C3_I_1_3', 'en', 'Instructor Fee', datetime('now'), NULL);

-- その他 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_1', 'C3_I_1_4', 'en', 'Other', datetime('now'), NULL);

-- 夏季賞与 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_2', 'C3_I_2_1', 'en', 'Summer Bonus', datetime('now'), NULL);

-- 冬季賞与 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_2', 'C3_I_2_2', 'en', 'Winter Bonus', datetime('now'), NULL);

-- 期末賞与 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_2', 'C3_I_2_3', 'en', 'Year-end Bonus', datetime('now'), NULL);

-- 臨時賞与 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_2', 'C3_I_2_4', 'en', 'Special Bonus', datetime('now'), NULL);

-- 寸志 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_2', 'C3_I_2_5', 'en', 'Gratuity', datetime('now'), NULL);

-- その他 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_2', 'C3_I_2_6', 'en', 'Other', datetime('now'), NULL);

-- 基礎年金 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_3', 'C3_I_3_1', 'en', 'Basic Pension', datetime('now'), NULL);

-- 厚生年金 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_3', 'C3_I_3_2', 'en', 'Employee Pension', datetime('now'), NULL);

-- 老齢年金 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_3', 'C3_I_3_3', 'en', 'Old-age Pension', datetime('now'), NULL);

-- 遺族年金 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_3', 'C3_I_3_4', 'en', 'Survivor''s Pension', datetime('now'), NULL);

-- 障害基礎年金 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_3', 'C3_I_3_5', 'en', 'Disability Basic Pension', datetime('now'), NULL);

-- 障害厚生年金 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_3', 'C3_I_3_6', 'en', 'Disability Employee Pension', datetime('now'), NULL);

-- その他 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_3', 'C3_I_3_7', 'en', 'Other', datetime('now'), NULL);

-- 医療保険 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_5', 'C3_I_5_1', 'en', 'Medical Insurance', datetime('now'), NULL);

-- 終身保険 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_5', 'C3_I_5_2', 'en', 'Life Insurance', datetime('now'), NULL);

-- 車両保険 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_5', 'C3_I_5_3', 'en', 'Vehicle Insurance', datetime('now'), NULL);

-- その他 (en)
INSERT INTO CATEGORY3_I18N(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT, UPDATE_DT)
VALUES (:pUserID, 'INCOME', 'C2_I_5', 'C3_I_5_4', 'en', 'Other', datetime('now'), NULL);

-- Total: 20 CATEGORY2 + 20 I18N (en), 126 CATEGORY3 + 126 I18N (en)
