-- Create CATEGORY3 table
-- Auto-generated from database schema
-- Created: 2025-11-21

CREATE TABLE CATEGORY3 (
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(64) NOT NULL,
    CATEGORY2_CODE VARCHAR(64) NOT NULL,
    CATEGORY3_CODE VARCHAR(64) NOT NULL,
    DISPLAY_ORDER INTEGER NOT NULL,
    CATEGORY3_NAME VARCHAR(128) NOT NULL,
    IS_DISABLED INTEGER NOT NULL DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL,
    UPDATE_DT DATETIME,
    PRIMARY KEY(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE),
    FOREIGN KEY(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE) REFERENCES CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE) ON DELETE CASCADE
);

-- Indexes for CATEGORY3
CREATE INDEX idx_category3_parent ON CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE);
CREATE INDEX idx_category3_order ON CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER);
CREATE INDEX idx_category3_disabled ON CATEGORY3(USER_ID, IS_DISABLED);
