-- Create ACCOUNT_TEMPLATES table
-- Auto-generated from database schema
-- Created: 2025-11-21

CREATE TABLE ACCOUNT_TEMPLATES (
    TEMPLATE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TEMPLATE_CODE VARCHAR(50) NOT NULL UNIQUE,
    TEMPLATE_NAME_JA TEXT NOT NULL,
    TEMPLATE_NAME_EN TEXT NOT NULL,
    DISPLAY_ORDER INTEGER,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now'))
);
