-- Create MANUFACTURERS table
-- Auto-generated from database schema
-- Created: 2025-11-21

CREATE TABLE MANUFACTURERS (
    MANUFACTURER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    MANUFACTURER_NAME TEXT NOT NULL,
    MEMO TEXT,
    DISPLAY_ORDER INTEGER NOT NULL DEFAULT 0,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    UNIQUE(USER_ID, MANUFACTURER_NAME)
);

-- Indexes for MANUFACTURERS
CREATE INDEX idx_manufacturers_user;
ON MANUFACTURERS(USER_ID, DISPLAY_ORDER);
