-- Create CATEGORY1 table
-- Auto-generated from database schema
-- Created: 2025-11-21

CREATE TABLE CATEGORY1 (
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(64) NOT NULL,
    DISPLAY_ORDER INTEGER NOT NULL,
    CATEGORY1_NAME VARCHAR(128) NOT NULL,
    IS_DISABLED INTEGER NOT NULL DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL,
    UPDATE_DT DATETIME,
    PRIMARY KEY(USER_ID, CATEGORY1_CODE)
);

-- Indexes for CATEGORY1
CREATE INDEX idx_category1_order ON CATEGORY1(USER_ID, DISPLAY_ORDER);
CREATE INDEX idx_category1_disabled ON CATEGORY1(USER_ID, IS_DISABLED);
