-- Create CATEGORY2 table
-- Auto-generated from database schema
-- Created: 2025-11-21

CREATE TABLE CATEGORY2 (
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(64) NOT NULL,
    CATEGORY2_CODE VARCHAR(64) NOT NULL,
    DISPLAY_ORDER INTEGER NOT NULL,
    CATEGORY2_NAME VARCHAR(128) NOT NULL,
    IS_DISABLED INTEGER NOT NULL DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL,
    UPDATE_DT DATETIME,
    PRIMARY KEY(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE),
    FOREIGN KEY(USER_ID, CATEGORY1_CODE) REFERENCES CATEGORY1(USER_ID, CATEGORY1_CODE) ON DELETE CASCADE
);

-- Indexes for CATEGORY2
CREATE INDEX idx_category2_parent ON CATEGORY2(USER_ID, CATEGORY1_CODE);
CREATE INDEX idx_category2_order ON CATEGORY2(USER_ID, CATEGORY1_CODE, DISPLAY_ORDER);
CREATE INDEX idx_category2_disabled ON CATEGORY2(USER_ID, IS_DISABLED);
