-- Create PRODUCTS table
-- Auto-generated from database schema
-- Created: 2025-11-21

CREATE TABLE PRODUCTS (
    PRODUCT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    PRODUCT_NAME TEXT NOT NULL,
    MANUFACTURER_ID INTEGER,
    MEMO TEXT,
    DISPLAY_ORDER INTEGER NOT NULL DEFAULT 0,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURERS(MANUFACTURER_ID) ON DELETE SET NULL,
    UNIQUE(USER_ID, PRODUCT_NAME)
);

-- Indexes for PRODUCTS
CREATE INDEX idx_products_user;
ON PRODUCTS(USER_ID, DISPLAY_ORDER);
CREATE INDEX idx_products_manufacturer;
ON PRODUCTS(MANUFACTURER_ID);
