//! SQL Query Constants
//! This module centralizes all SQL queries used in the application.
//! Some queries may be reserved for future use or referenced in documentation.
#![allow(dead_code)]

// ============================================================================
// Authentication Service Queries
// ============================================================================

pub const AUTH_GET_USER_BY_NAME: &str = r#"
SELECT USER_ID, NAME, PAW, ROLE, ENTRY_DT, UPDATE_DT 
FROM USERS 
WHERE NAME = ?
"#;

pub const AUTH_GET_NEXT_USER_ID: &str = "SELECT COALESCE(MAX(USER_ID), 0) + 1 as next_id FROM USERS";

pub const AUTH_INSERT_USER: &str = r#"
INSERT INTO USERS (USER_ID, NAME, PAW, ROLE, ENCRYPTION_SALT, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, datetime('now'))
"#;

pub const AUTH_CHECK_TABLE_EXISTS: &str = r#"
SELECT name FROM sqlite_master 
WHERE type='table' AND name='USERS'
"#;

pub const AUTH_COUNT_USERS: &str = "SELECT COUNT(*) as count FROM USERS";

pub const AUTH_COUNT_USERS_BY_ROLE: &str = "SELECT COUNT(*) as count FROM USERS WHERE ROLE = ?";

pub const AUTH_GET_USER_NAME_BY_ID: &str = "SELECT NAME FROM USERS WHERE USER_ID = 1";

pub const AUTH_GET_PASSWORD_BY_ID: &str = "SELECT PAW FROM USERS WHERE USER_ID = 1";

pub const AUTH_GET_ROLE_BY_ID: &str = "SELECT ROLE FROM USERS WHERE USER_ID = 1";

// ============================================================================
// User Management Service Queries
// ============================================================================

pub const USER_LIST_USERS: &str = r#"
SELECT USER_ID, NAME, ROLE, ENTRY_DT, UPDATE_DT 
FROM USERS 
ORDER BY USER_ID
"#;

pub const USER_GET_BY_ID: &str = r#"
SELECT USER_ID, NAME, ROLE, ENTRY_DT, UPDATE_DT 
FROM USERS 
WHERE USER_ID = ?
"#;

pub const USER_CHECK_NAME_EXISTS: &str = "SELECT COUNT(*) as count FROM USERS WHERE NAME = ?";

pub const USER_GET_NEXT_ID: &str = "SELECT COALESCE(MAX(USER_ID), 0) + 1 as next_id FROM USERS";

pub const USER_INSERT: &str = r#"
INSERT INTO USERS (USER_ID, NAME, PAW, ROLE, ENCRYPTION_SALT, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, datetime('now'))
"#;

/// Fetch a user's per-user Argon2 salt for encryption-key derivation.
/// Returns `None` for a missing user_id; the caller decides whether that
/// is an error. The salt is stored as `BLOB` — a fixed-width 16-byte
/// value generated by `security::generate_encryption_salt`.
pub const USER_GET_ENCRYPTION_SALT: &str = r#"
SELECT ENCRYPTION_SALT
FROM USERS
WHERE USER_ID = ?
"#;

pub const USER_UPDATE_NAME: &str = r#"
UPDATE USERS 
SET NAME = ?, UPDATE_DT = datetime('now') 
WHERE USER_ID = ?
"#;

pub const USER_CHECK_NAME_EXISTS_EXCLUDING_ID: &str = r#"
SELECT COUNT(*) as count 
FROM USERS 
WHERE NAME = ? AND USER_ID != ?
"#;

pub const USER_UPDATE_PASSWORD: &str = r#"
UPDATE USERS 
SET PAW = ?, UPDATE_DT = datetime('now') 
WHERE USER_ID = ?
"#;

pub const USER_GET_PASSWORD_BY_ID: &str = "SELECT PAW FROM USERS WHERE USER_ID = ?";

pub const USER_DELETE: &str = "DELETE FROM USERS WHERE USER_ID = ?";

pub const USER_GET_PERIOD_SETTINGS: &str = r#"
SELECT MONTH_PERIOD_START_DAY, YEAR_PERIOD_START_MONTH, YEAR_PERIOD_START_DAY,
       COALESCE(MONTH_PERIOD_HOLIDAY_SHIFT, 0)
FROM USERS WHERE USER_ID = ?
"#;

pub const USER_UPDATE_PERIOD_SETTINGS: &str = r#"
UPDATE USERS
SET MONTH_PERIOD_START_DAY = ?,
    YEAR_PERIOD_START_MONTH = ?,
    YEAR_PERIOD_START_DAY = ?,
    MONTH_PERIOD_HOLIDAY_SHIFT = ?,
    UPDATE_DT = datetime('now')
WHERE USER_ID = ?
"#;

// ============================================================================
// Encryption Service Queries
// ============================================================================

pub const ENCRYPTION_LIST_FIELDS: &str = r#"
SELECT FIELD_ID, TABLE_NAME, COLUMN_NAME, DESCRIPTION, IS_ACTIVE 
FROM ENCRYPTED_FIELDS 
WHERE IS_ACTIVE = 1
"#;

pub const ENCRYPTION_GET_NEXT_FIELD_ID: &str = "SELECT COALESCE(MAX(FIELD_ID), 0) + 1 as next_id FROM ENCRYPTED_FIELDS";

pub const ENCRYPTION_INSERT_FIELD: &str = r#"
INSERT INTO ENCRYPTED_FIELDS (FIELD_ID, TABLE_NAME, COLUMN_NAME, DESCRIPTION, IS_ACTIVE, ENTRY_DT) 
VALUES (?, ?, ?, ?, 1, datetime('now'))
"#;

// ============================================================================
// I18N Service Queries
// ============================================================================

pub const I18N_GET_RESOURCE: &str = r#"
SELECT RESOURCE_VALUE 
FROM I18N_RESOURCES 
WHERE RESOURCE_KEY = ? AND LANG_CODE = ?
"#;

pub const I18N_GET_BY_CATEGORY: &str = r#"
SELECT RESOURCE_KEY, RESOURCE_VALUE 
FROM I18N_RESOURCES 
WHERE LANG_CODE = ? AND CATEGORY = ?
"#;

pub const I18N_GET_ALL: &str = r#"
SELECT RESOURCE_KEY, RESOURCE_VALUE 
FROM I18N_RESOURCES 
WHERE LANG_CODE = ?
"#;

pub const I18N_GET_AVAILABLE_LANGUAGES: &str = r#"
SELECT DISTINCT LANG_CODE 
FROM I18N_RESOURCES 
ORDER BY LANG_CODE
"#;

// ============================================================================
// Category Service Queries
// ============================================================================

pub const CATEGORY_COUNT_BY_USER: &str = "SELECT COUNT(*) FROM CATEGORY1 WHERE USER_ID = ?";

// PR4 (Fable-5 #24): category.rs count queries used for either a
// "already populated?" guard or as the incremental suffix for the next
// CATEGORY{2,3}_CODE (`C2_{USER}_{CAT1}_{count+1}`).
pub const CATEGORY2_COUNT_BY_USER: &str = "SELECT COUNT(*) FROM CATEGORY2 WHERE USER_ID = ?";

pub const CATEGORY2_COUNT_BY_USER_AND_CATEGORY1: &str =
    "SELECT COUNT(*) FROM CATEGORY2 WHERE USER_ID = ? AND CATEGORY1_CODE = ?";

pub const CATEGORY3_COUNT_BY_USER_AND_CATEGORY2: &str =
    "SELECT COUNT(*) FROM CATEGORY3 WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ?";

pub const CATEGORY1_LIST: &str = r#"
SELECT 
    c.USER_ID,
    c.CATEGORY1_CODE,
    c.DISPLAY_ORDER,
    COALESCE(i18n.CATEGORY1_NAME_I18N, c.CATEGORY1_NAME) as CATEGORY1_NAME,
    c.IS_DISABLED
FROM CATEGORY1 c
LEFT JOIN CATEGORY1_I18N i18n 
    ON c.USER_ID = i18n.USER_ID 
    AND c.CATEGORY1_CODE = i18n.CATEGORY1_CODE 
    AND i18n.LANG_CODE = ?
WHERE c.USER_ID = ? AND c.IS_DISABLED = 0
ORDER BY c.DISPLAY_ORDER
"#;

pub const CATEGORY1_TREE: &str = r#"
SELECT 
    c.CATEGORY1_CODE,
    c.DISPLAY_ORDER,
    COALESCE(i18n.CATEGORY1_NAME_I18N, c.CATEGORY1_NAME) as name
FROM CATEGORY1 c
LEFT JOIN CATEGORY1_I18N i18n 
    ON c.USER_ID = i18n.USER_ID 
    AND c.CATEGORY1_CODE = i18n.CATEGORY1_CODE 
    AND i18n.LANG_CODE = ?
WHERE c.USER_ID = ? AND c.IS_DISABLED = 0
ORDER BY c.DISPLAY_ORDER
"#;

// PR11 (Fable-5 #31): the CATEGORY{2,3}_TREE queries used to be
// invoked once per parent row inside a nested loop
// (`get_category_tree` / `get_category_tree_all`), giving a
// 1 + N + N×M query pattern. They are now issued once each and
// grouped in Rust — the parent code columns are included in the
// SELECT so the caller can bucket rows by parent, and the WHERE
// no longer filters on the parent code. Bind order is (lang_code,
// user_id).
pub const CATEGORY2_TREE: &str = r#"
SELECT
    c.CATEGORY1_CODE,
    c.CATEGORY2_CODE,
    c.DISPLAY_ORDER,
    COALESCE(i18n.CATEGORY2_NAME_I18N, c.CATEGORY2_NAME) as name
FROM CATEGORY2 c
LEFT JOIN CATEGORY2_I18N i18n
    ON c.USER_ID = i18n.USER_ID
    AND c.CATEGORY1_CODE = i18n.CATEGORY1_CODE
    AND c.CATEGORY2_CODE = i18n.CATEGORY2_CODE
    AND i18n.LANG_CODE = ?
WHERE c.USER_ID = ? AND c.IS_DISABLED = 0
ORDER BY c.CATEGORY1_CODE, c.DISPLAY_ORDER
"#;

pub const CATEGORY3_TREE: &str = r#"
SELECT
    c.CATEGORY1_CODE,
    c.CATEGORY2_CODE,
    c.CATEGORY3_CODE,
    c.DISPLAY_ORDER,
    COALESCE(i18n.CATEGORY3_NAME_I18N, c.CATEGORY3_NAME) as name
FROM CATEGORY3 c
LEFT JOIN CATEGORY3_I18N i18n
    ON c.USER_ID = i18n.USER_ID
    AND c.CATEGORY1_CODE = i18n.CATEGORY1_CODE
    AND c.CATEGORY2_CODE = i18n.CATEGORY2_CODE
    AND c.CATEGORY3_CODE = i18n.CATEGORY3_CODE
    AND i18n.LANG_CODE = ?
WHERE c.USER_ID = ?
    AND c.IS_DISABLED = 0
ORDER BY c.CATEGORY1_CODE, c.CATEGORY2_CODE, c.DISPLAY_ORDER
"#;

// Category tree queries including disabled items (for management screen)
// Same PR11 flat shape as CATEGORY{2,3}_TREE above.
pub const CATEGORY2_TREE_ALL: &str = r#"
SELECT
    c.CATEGORY1_CODE,
    c.CATEGORY2_CODE,
    c.DISPLAY_ORDER,
    c.IS_DISABLED,
    COALESCE(i18n.CATEGORY2_NAME_I18N, c.CATEGORY2_NAME) as name
FROM CATEGORY2 c
LEFT JOIN CATEGORY2_I18N i18n
    ON c.USER_ID = i18n.USER_ID
    AND c.CATEGORY1_CODE = i18n.CATEGORY1_CODE
    AND c.CATEGORY2_CODE = i18n.CATEGORY2_CODE
    AND i18n.LANG_CODE = ?
WHERE c.USER_ID = ?
ORDER BY c.CATEGORY1_CODE, c.IS_DISABLED, c.DISPLAY_ORDER
"#;

pub const CATEGORY3_TREE_ALL: &str = r#"
SELECT
    c.CATEGORY1_CODE,
    c.CATEGORY2_CODE,
    c.CATEGORY3_CODE,
    c.DISPLAY_ORDER,
    c.IS_DISABLED,
    COALESCE(i18n.CATEGORY3_NAME_I18N, c.CATEGORY3_NAME) as name
FROM CATEGORY3 c
LEFT JOIN CATEGORY3_I18N i18n
    ON c.USER_ID = i18n.USER_ID
    AND c.CATEGORY1_CODE = i18n.CATEGORY1_CODE
    AND c.CATEGORY2_CODE = i18n.CATEGORY2_CODE
    AND c.CATEGORY3_CODE = i18n.CATEGORY3_CODE
    AND i18n.LANG_CODE = ?
WHERE c.USER_ID = ?
ORDER BY c.CATEGORY1_CODE, c.CATEGORY2_CODE, c.IS_DISABLED, c.DISPLAY_ORDER
"#;

pub const CATEGORY2_ENABLE: &str = r#"
UPDATE CATEGORY2
SET IS_DISABLED = 0, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ?
"#;

pub const CATEGORY3_ENABLE: &str = r#"
UPDATE CATEGORY3
SET IS_DISABLED = 0, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND CATEGORY3_CODE = ?
"#;

pub const CATEGORY2_GET_MAX_ORDER: &str = r#"
SELECT COALESCE(MAX(DISPLAY_ORDER), 0) as max_order
FROM CATEGORY2
WHERE USER_ID = ? AND CATEGORY1_CODE = ?
"#;

pub const CATEGORY2_INSERT: &str = r#"
INSERT INTO CATEGORY2 (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, 0, datetime('now'))
"#;

pub const CATEGORY2_I18N_INSERT: &str = r#"
INSERT INTO CATEGORY2_I18N (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, datetime('now'))
"#;

pub const CATEGORY3_GET_MAX_ORDER: &str = r#"
SELECT COALESCE(MAX(DISPLAY_ORDER), 0) as max_order
FROM CATEGORY3
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ?
"#;

pub const CATEGORY3_INSERT: &str = r#"
INSERT INTO CATEGORY3 (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, ?, 0, datetime('now'))
"#;

pub const CATEGORY3_I18N_INSERT: &str = r#"
INSERT INTO CATEGORY3_I18N (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
"#;

pub const CATEGORY2_CHECK_DUPLICATE_NAME: &str = r#"
SELECT COUNT(*) as count FROM CATEGORY2_I18N 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_NAME_I18N = ? AND LANG_CODE = ?
"#;

pub const CATEGORY2_CHECK_DUPLICATE_NAME_EXCLUDING: &str = r#"
SELECT COUNT(*) as count FROM CATEGORY2_I18N 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE != ? 
AND LANG_CODE = ? AND CATEGORY2_NAME_I18N = ?
"#;

pub const CATEGORY3_CHECK_DUPLICATE_NAME: &str = r#"
SELECT COUNT(*) as count FROM CATEGORY3_I18N 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND CATEGORY3_NAME_I18N = ? AND LANG_CODE = ?
"#;

pub const CATEGORY3_CHECK_DUPLICATE_NAME_EXCLUDING: &str = r#"
SELECT COUNT(*) as count FROM CATEGORY3_I18N 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? 
AND CATEGORY3_CODE != ? AND LANG_CODE = ? AND CATEGORY3_NAME_I18N = ?
"#;

pub const CATEGORY2_CHECK_DUPLICATE_CODE: &str = r#"
SELECT COUNT(*) as count FROM CATEGORY2 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ?
"#;

pub const CATEGORY3_CHECK_DUPLICATE_CODE: &str = r#"
SELECT COUNT(*) as count FROM CATEGORY3 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND CATEGORY3_CODE = ?
"#;

pub const CATEGORY2_UPDATE: &str = r#"
UPDATE CATEGORY2 
SET CATEGORY2_NAME = ?, UPDATE_DT = datetime('now') 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ?
"#;

pub const CATEGORY2_I18N_UPDATE: &str = r#"
UPDATE CATEGORY2_I18N 
SET CATEGORY2_NAME_I18N = ?, UPDATE_DT = datetime('now') 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND LANG_CODE = ?
"#;

pub const CATEGORY3_UPDATE: &str = r#"
UPDATE CATEGORY3 
SET CATEGORY3_NAME = ?, UPDATE_DT = datetime('now') 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND CATEGORY3_CODE = ?
"#;

pub const CATEGORY3_I18N_UPDATE: &str = r#"
UPDATE CATEGORY3_I18N 
SET CATEGORY3_NAME_I18N = ?, UPDATE_DT = datetime('now') 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND CATEGORY3_CODE = ? AND LANG_CODE = ?
"#;

pub const CATEGORY2_GET_FOR_EDIT: &str = r#"
SELECT 
    c.CATEGORY2_CODE,
    c.CATEGORY2_NAME,
    COALESCE(i18n_ja.CATEGORY2_NAME_I18N, c.CATEGORY2_NAME) as name_ja,
    COALESCE(i18n_en.CATEGORY2_NAME_I18N, c.CATEGORY2_NAME) as name_en
FROM CATEGORY2 c
LEFT JOIN CATEGORY2_I18N i18n_ja 
    ON c.USER_ID = i18n_ja.USER_ID 
    AND c.CATEGORY1_CODE = i18n_ja.CATEGORY1_CODE 
    AND c.CATEGORY2_CODE = i18n_ja.CATEGORY2_CODE 
    AND i18n_ja.LANG_CODE = 'ja'
LEFT JOIN CATEGORY2_I18N i18n_en 
    ON c.USER_ID = i18n_en.USER_ID 
    AND c.CATEGORY1_CODE = i18n_en.CATEGORY1_CODE 
    AND c.CATEGORY2_CODE = i18n_en.CATEGORY2_CODE 
    AND i18n_en.LANG_CODE = 'en'
WHERE c.USER_ID = ? AND c.CATEGORY1_CODE = ? AND c.CATEGORY2_CODE = ?
"#;

pub const CATEGORY3_GET_FOR_EDIT: &str = r#"
SELECT 
    c.CATEGORY3_CODE,
    c.CATEGORY3_NAME,
    COALESCE(i18n_ja.CATEGORY3_NAME_I18N, c.CATEGORY3_NAME) as name_ja,
    COALESCE(i18n_en.CATEGORY3_NAME_I18N, c.CATEGORY3_NAME) as name_en
FROM CATEGORY3 c
LEFT JOIN CATEGORY3_I18N i18n_ja 
    ON c.USER_ID = i18n_ja.USER_ID 
    AND c.CATEGORY1_CODE = i18n_ja.CATEGORY1_CODE 
    AND c.CATEGORY2_CODE = i18n_ja.CATEGORY2_CODE 
    AND c.CATEGORY3_CODE = i18n_ja.CATEGORY3_CODE 
    AND i18n_ja.LANG_CODE = 'ja'
LEFT JOIN CATEGORY3_I18N i18n_en 
    ON c.USER_ID = i18n_en.USER_ID 
    AND c.CATEGORY1_CODE = i18n_en.CATEGORY1_CODE 
    AND c.CATEGORY2_CODE = i18n_en.CATEGORY2_CODE 
    AND c.CATEGORY3_CODE = i18n_en.CATEGORY3_CODE 
    AND i18n_en.LANG_CODE = 'en'
WHERE c.USER_ID = ? AND c.CATEGORY1_CODE = ? AND c.CATEGORY2_CODE = ? AND c.CATEGORY3_CODE = ?
"#;

// ============================================================================
// Category Order Management Queries
// ============================================================================

pub const CATEGORY2_GET_ORDER: &str = r#"
SELECT DISPLAY_ORDER FROM CATEGORY2 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ?
"#;

pub const CATEGORY2_UPDATE_ORDER: &str = r#"
UPDATE CATEGORY2 SET DISPLAY_ORDER = ?, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ?
"#;

pub const CATEGORY2_GET_SIBLING_BY_ORDER: &str = r#"
SELECT CATEGORY2_CODE FROM CATEGORY2
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND DISPLAY_ORDER = ?
"#;

pub const CATEGORY3_GET_ORDER: &str = r#"
SELECT DISPLAY_ORDER FROM CATEGORY3 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND CATEGORY3_CODE = ?
"#;

pub const CATEGORY3_UPDATE_ORDER: &str = r#"
UPDATE CATEGORY3 SET DISPLAY_ORDER = ?, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND CATEGORY3_CODE = ?
"#;

pub const CATEGORY3_GET_SIBLING_BY_ORDER: &str = r#"
SELECT CATEGORY3_CODE FROM CATEGORY3
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND DISPLAY_ORDER = ?
"#;

pub const CATEGORY2_DELETE_LOGICAL: &str = r#"
UPDATE CATEGORY2
SET IS_DISABLED = 1, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ?
"#;

pub const CATEGORY3_DELETE_LOGICAL: &str = r#"
UPDATE CATEGORY3
SET IS_DISABLED = 1, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND CATEGORY3_CODE = ?
"#;

pub const CATEGORY3_DISABLE_BY_CATEGORY2: &str = r#"
UPDATE CATEGORY3
SET IS_DISABLED = 1, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND IS_DISABLED = 0
"#;

// ============================================================================
// Account Management Service Queries
// ============================================================================

// Note: get_accounts() and get_account_by_code() use sqlx::query_as! macro
// with hardcoded SQL for compile-time type checking. The queries below are
// provided for reference but not used directly in those functions.

// Account Templates
pub const ACCOUNT_TEMPLATE_LIST: &str = r#"
SELECT TEMPLATE_ID, TEMPLATE_CODE, TEMPLATE_NAME_JA, TEMPLATE_NAME_EN, DISPLAY_ORDER, ENTRY_DT
FROM ACCOUNT_TEMPLATES
ORDER BY DISPLAY_ORDER
"#;

// User Accounts
pub const ACCOUNT_LIST_BY_USER: &str = r#"
SELECT ACCOUNT_ID, USER_ID, ACCOUNT_CODE, ACCOUNT_NAME, TEMPLATE_CODE, 
       INITIAL_BALANCE, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT, UPDATE_DT
FROM ACCOUNTS
WHERE USER_ID = ? AND IS_DISABLED = 0
ORDER BY DISPLAY_ORDER, ACCOUNT_CODE
"#;

pub const ACCOUNT_GET_BY_CODE: &str = r#"
SELECT ACCOUNT_ID, USER_ID, ACCOUNT_CODE, ACCOUNT_NAME, TEMPLATE_CODE, 
       INITIAL_BALANCE, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT, UPDATE_DT
FROM ACCOUNTS
WHERE USER_ID = ? AND ACCOUNT_CODE = ?
"#;

pub const ACCOUNT_CHECK_DUPLICATE_CODE: &str = r#"
SELECT COUNT(*) as count
FROM ACCOUNTS
WHERE USER_ID = ? AND ACCOUNT_CODE = ? AND IS_DISABLED = 0
"#;

pub const ACCOUNT_INSERT: &str = r#"
INSERT INTO ACCOUNTS (USER_ID, ACCOUNT_CODE, ACCOUNT_NAME, TEMPLATE_CODE, 
                      INITIAL_BALANCE, DISPLAY_ORDER, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
"#;

pub const ACCOUNT_UPSERT: &str = r#"
INSERT INTO ACCOUNTS (USER_ID, ACCOUNT_CODE, ACCOUNT_NAME, TEMPLATE_CODE, 
                      INITIAL_BALANCE, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, ?, 0, datetime('now'))
ON CONFLICT(USER_ID, ACCOUNT_CODE) 
DO UPDATE SET 
    ACCOUNT_NAME = excluded.ACCOUNT_NAME,
    TEMPLATE_CODE = excluded.TEMPLATE_CODE,
    INITIAL_BALANCE = excluded.INITIAL_BALANCE,
    DISPLAY_ORDER = excluded.DISPLAY_ORDER,
    IS_DISABLED = 0,
    UPDATE_DT = datetime('now')
"#;

pub const ACCOUNT_UPDATE: &str = r#"
UPDATE ACCOUNTS 
SET ACCOUNT_NAME = ?, TEMPLATE_CODE = ?, INITIAL_BALANCE = ?, 
    DISPLAY_ORDER = ?, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND ACCOUNT_CODE = ?
"#;

pub const ACCOUNT_DELETE_LOGICAL: &str = r#"
UPDATE ACCOUNTS
SET IS_DISABLED = 1, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND ACCOUNT_CODE = ?
"#;

/// Delete-lock guard: does any transaction or recurring rule still name
/// this account on either side (FROM_ACCOUNT_CODE / TO_ACCOUNT_CODE)?
/// Deleted (IS_DISABLED=1) transactions also count as a reference — they
/// remain in history and their account handle must not be recycled.
/// Binds: (user_id, account_code, account_code, user_id, account_code,
/// account_code).
pub const ACCOUNT_CHECK_IN_USE: &str = r#"
SELECT EXISTS(
    SELECT 1 FROM TRANSACTIONS_HEADER
    WHERE USER_ID = ?
      AND (FROM_ACCOUNT_CODE = ? OR TO_ACCOUNT_CODE = ?)
    UNION ALL
    SELECT 1 FROM RECURRING_RULES
    WHERE USER_ID = ?
      AND (FROM_ACCOUNT_CODE = ? OR TO_ACCOUNT_CODE = ?)
)
"#;

pub const ACCOUNT_GET_NEXT_DISPLAY_ORDER: &str = r#"
SELECT COALESCE(MAX(DISPLAY_ORDER), 0) + 1 as next_order
FROM ACCOUNTS
WHERE USER_ID = ?
"#;

// PR4: extracted from account.rs to satisfy the "all queries live in
// sql_queries.rs" project rule (Fable-5 #24).
// PR4 (Fable-5 #24): holiday.rs inline SQL moved out.
pub const HOLIDAY_GET_USER_LOCALE: &str = r#"
SELECT COALESCE(HOLIDAY_LOCALE, 'JP') FROM USERS WHERE USER_ID = ?
"#;

pub const HOLIDAY_LIST_STANDARD_IN_RANGE: &str = r#"
SELECT HOLIDAY_DATE FROM HOLIDAYS_STANDARD
WHERE LOCALE = ? AND HOLIDAY_DATE BETWEEN ? AND ?
"#;

pub const HOLIDAY_LIST_USER_CUSTOM_IN_RANGE: &str = r#"
SELECT HOLIDAY_DATE FROM HOLIDAYS_USER_CUSTOM
WHERE USER_ID = ? AND HOLIDAY_DATE BETWEEN ? AND ?
"#;

pub const ACCOUNT_TEMPLATE_GET_NONE: &str = r#"
SELECT TEMPLATE_ID, TEMPLATE_CODE, TEMPLATE_NAME_JA, TEMPLATE_NAME_EN, DISPLAY_ORDER, ENTRY_DT
FROM ACCOUNT_TEMPLATES
WHERE TEMPLATE_CODE = 'NONE'
"#;

pub const ACCOUNT_LIST_ALL: &str = r#"
SELECT ACCOUNT_ID, USER_ID, ACCOUNT_CODE, ACCOUNT_NAME, TEMPLATE_CODE,
       INITIAL_BALANCE, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT, UPDATE_DT
FROM ACCOUNTS
ORDER BY USER_ID, DISPLAY_ORDER
"#;

/// Running balance of every active account for `user_id`, counted up to and
/// including `?` (as_of_date, `YYYY-MM-DD`). Applies actualised
/// transactions only (`IS_SCHEDULED = 0`):
///   + INCOME  with TO_ACCOUNT   = a.ACCOUNT_CODE
///   - EXPENSE with FROM_ACCOUNT = a.ACCOUNT_CODE
///   + TRANSFER with TO_ACCOUNT  = a.ACCOUNT_CODE
///   - TRANSFER with FROM_ACCOUNT = a.ACCOUNT_CODE
///
/// The single-pass CASE keeps a transfer visible to both source and
/// destination accounts with sign flipped per side. Bindings: (as_of_date,
/// user_id).
pub const ACCOUNT_BALANCES_AS_OF: &str = r#"
SELECT
    a.ACCOUNT_CODE,
    a.ACCOUNT_NAME,
    a.INITIAL_BALANCE
        -- Fable-5 review #20 — sum every applicable arm independently
        -- instead of using a single CASE that stops at first match.
        -- The old shape put the TRANSFER-TO arm ahead of the
        -- TRANSFER-FROM arm, so a self-transfer (from == to == a)
        -- matched only the credit side and inflated the balance by the
        -- transfer amount. Four independent CASE expressions each
        -- resolve to 0 when their condition doesn't fire, so the sum
        -- nets to zero for a self-transfer even if a stale one is
        -- already in the DB; the write-side guards in
        -- `save_transaction_header` / `update_transaction_header`
        -- prevent new occurrences.
        + COALESCE(SUM(
              CASE WHEN th.CATEGORY1_CODE = 'INCOME'
                        AND th.TO_ACCOUNT_CODE = a.ACCOUNT_CODE
                   THEN th.TOTAL_AMOUNT ELSE 0 END
            + CASE WHEN th.CATEGORY1_CODE = 'EXPENSE'
                        AND th.FROM_ACCOUNT_CODE = a.ACCOUNT_CODE
                   THEN -th.TOTAL_AMOUNT ELSE 0 END
            + CASE WHEN th.CATEGORY1_CODE = 'TRANSFER'
                        AND th.TO_ACCOUNT_CODE = a.ACCOUNT_CODE
                   THEN th.TOTAL_AMOUNT ELSE 0 END
            + CASE WHEN th.CATEGORY1_CODE = 'TRANSFER'
                        AND th.FROM_ACCOUNT_CODE = a.ACCOUNT_CODE
                   THEN -th.TOTAL_AMOUNT ELSE 0 END
        ), 0) AS BALANCE,
    a.DISPLAY_ORDER
FROM ACCOUNTS a
LEFT JOIN TRANSACTIONS_HEADER th
    ON th.USER_ID = a.USER_ID
   AND th.IS_SCHEDULED = 0
   AND DATE(th.TRANSACTION_DATE) <= DATE(?)
   AND ( th.FROM_ACCOUNT_CODE = a.ACCOUNT_CODE
      OR th.TO_ACCOUNT_CODE   = a.ACCOUNT_CODE )
WHERE a.USER_ID = ? AND a.IS_DISABLED = 0
GROUP BY a.ACCOUNT_CODE, a.ACCOUNT_NAME, a.INITIAL_BALANCE, a.DISPLAY_ORDER
ORDER BY a.DISPLAY_ORDER
"#;

// ============================================================================
// Database Service Queries
// ============================================================================

pub const DB_PRAGMA_WAL: &str = "PRAGMA journal_mode = WAL;";

pub const DB_TEST_CONNECTION: &str = "SELECT 1 as test";

// ============================================================================
// Test-Only Queries (用于测试代码)
// ============================================================================

pub const TEST_AUTH_GET_USER_NAME_BY_ID: &str = "SELECT NAME FROM USERS WHERE USER_ID = 1";

pub const TEST_AUTH_GET_PASSWORD_BY_ID: &str = "SELECT PAW FROM USERS WHERE USER_ID = 1";

pub const TEST_AUTH_GET_ROLE_BY_ID: &str = "SELECT ROLE FROM USERS WHERE USER_ID = 1";

pub const TEST_CREATE_USERS_TABLE: &str = r#"
CREATE TABLE USERS (
    USER_ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    PAW TEXT NOT NULL,
    ROLE INTEGER NOT NULL,
    ENTRY_DT DATETIME NOT NULL,
    UPDATE_DT DATETIME
)
"#;

// Test queries for category service
pub const TEST_CATEGORY_GET_CATEGORY2_NAME: &str = "SELECT CATEGORY2_NAME FROM CATEGORY2 WHERE USER_ID = ? AND CATEGORY2_CODE = ?";

pub const TEST_CATEGORY_GET_CATEGORY2_I18N_NAME: &str = "SELECT CATEGORY2_NAME_I18N FROM CATEGORY2_I18N WHERE USER_ID = ? AND CATEGORY2_CODE = ? AND LANG_CODE = ?";

pub const TEST_CATEGORY_GET_FIRST_CATEGORY2_CODE: &str = "SELECT CATEGORY2_CODE FROM CATEGORY2 WHERE USER_ID = ? LIMIT 1";

pub const TEST_CATEGORY_GET_CATEGORY3_NAME: &str = "SELECT CATEGORY3_NAME FROM CATEGORY3 WHERE USER_ID = ? AND CATEGORY3_CODE = ?";

// Test queries for account service
pub const TEST_ACCOUNT_CREATE_TEMPLATES_TABLE: &str = r#"
CREATE TABLE ACCOUNT_TEMPLATES (
    TEMPLATE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TEMPLATE_CODE VARCHAR(50) NOT NULL UNIQUE,
    TEMPLATE_NAME_JA TEXT NOT NULL,
    TEMPLATE_NAME_EN TEXT NOT NULL,
    DISPLAY_ORDER INTEGER,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now'))
)
"#;

pub const TEST_ACCOUNT_CREATE_ACCOUNTS_TABLE: &str = r#"
CREATE TABLE ACCOUNTS (
    ACCOUNT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    ACCOUNT_CODE VARCHAR(50) NOT NULL,
    ACCOUNT_NAME TEXT NOT NULL,
    TEMPLATE_CODE VARCHAR(50) NOT NULL,
    INITIAL_BALANCE INTEGER DEFAULT 0,
    DISPLAY_ORDER INTEGER,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (TEMPLATE_CODE) REFERENCES ACCOUNT_TEMPLATES(TEMPLATE_CODE),
    UNIQUE(USER_ID, ACCOUNT_CODE)
)
"#;

pub const TEST_ACCOUNT_INSERT_TEMPLATES: &str = r#"
INSERT INTO ACCOUNT_TEMPLATES (TEMPLATE_CODE, TEMPLATE_NAME_JA, TEMPLATE_NAME_EN, DISPLAY_ORDER)
VALUES 
('CASH', '現金', 'Cash', 1),
('BANK', '銀行口座', 'Bank Account', 2)
"#;

pub const TEST_INSERT_USER_ADMIN: &str = "INSERT INTO USERS (USER_ID, NAME, PAW, ROLE, ENTRY_DT) VALUES (1, 'admin', 'dummy', 0, datetime('now'))";

pub const TEST_INSERT_USER_GENERAL: &str = "INSERT INTO USERS (USER_ID, NAME, PAW, ROLE, ENTRY_DT) VALUES (2, 'testuser', 'dummy', 1, datetime('now'))";

/// Auto-increment USERS INSERT for test helpers that need a per-user
/// random `ENCRYPTION_SALT` (so `_with_password` code paths can derive
/// keys the same way production users do). Kept in one place so a
/// future USERS column addition only touches one statement — the two
/// helpers in `test_helpers.rs` used to duplicate this INSERT verbatim
/// (CodeRabbit review on #123). Bind order: NAME, PAW, ROLE,
/// ENCRYPTION_SALT, ENTRY_DT.
pub const TEST_INSERT_USER_WITH_SALT: &str =
    "INSERT INTO USERS (NAME, PAW, ROLE, ENCRYPTION_SALT, ENTRY_DT) VALUES (?, ?, ?, ?, ?)";

pub const TEST_CATEGORY2_GET_DISPLAY_ORDER: &str = "SELECT DISPLAY_ORDER FROM CATEGORY2 WHERE USER_ID = ? AND CATEGORY2_CODE = ?";

pub const TEST_CATEGORY3_GET_DISPLAY_ORDER: &str = "SELECT DISPLAY_ORDER FROM CATEGORY3 WHERE USER_ID = ? AND CATEGORY3_CODE = ?";

pub const TEST_CATEGORY2_COUNT: &str = "SELECT COUNT(*) FROM CATEGORY2 WHERE USER_ID = ?";

pub const TEST_CATEGORY3_COUNT: &str = "SELECT COUNT(*) FROM CATEGORY3 WHERE USER_ID = ?";

pub const TEST_CREATE_CATEGORY2_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS CATEGORY2 (
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(64) NOT NULL,
    CATEGORY2_CODE VARCHAR(64) NOT NULL,
    DISPLAY_ORDER INTEGER NOT NULL,
    CATEGORY2_NAME VARCHAR(128) NOT NULL,
    IS_DISABLED INTEGER NOT NULL DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL,
    UPDATE_DT DATETIME,
    PRIMARY KEY(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE),
    FOREIGN KEY(USER_ID, CATEGORY1_CODE) REFERENCES CATEGORY1(USER_ID, CATEGORY1_CODE) ON DELETE CASCADE
)
"#;

pub const TEST_CREATE_CATEGORY3_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS CATEGORY3 (
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(64) NOT NULL,
    CATEGORY2_CODE VARCHAR(64) NOT NULL,
    CATEGORY3_CODE VARCHAR(64) NOT NULL,
    DISPLAY_ORDER INTEGER NOT NULL,
    CATEGORY3_NAME VARCHAR(128) NOT NULL,
    IS_DISABLED INTEGER NOT NULL DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL,
    UPDATE_DT DATETIME,
    PRIMARY KEY(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE),
    FOREIGN KEY(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE) REFERENCES CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE) ON DELETE CASCADE
)
"#;

pub const TEST_CREATE_CATEGORY1_TABLE: &str = r#"
CREATE TABLE CATEGORY1 (
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(64) NOT NULL,
    CATEGORY1_NAME VARCHAR(128) NOT NULL,
    ENTRY_DT DATETIME NOT NULL,
    UPDATE_DT DATETIME,
    PRIMARY KEY(USER_ID, CATEGORY1_CODE),
    FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
)
"#;

pub const TEST_INSERT_TEST_USER: &str = "INSERT INTO USERS (USER_ID, NAME, PAW, ROLE, ENTRY_DT) VALUES (1, 'testuser', 'hash', 0, datetime('now'))";

pub const TEST_INSERT_CATEGORY1: &str = "INSERT INTO CATEGORY1 (USER_ID, CATEGORY1_CODE, CATEGORY1_NAME, ENTRY_DT) VALUES (1, 'INCOME', '収入', datetime('now'))";

pub const TEST_INSERT_CATEGORY2: &str = "INSERT INTO CATEGORY2 (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY2_NAME, DISPLAY_ORDER, ENTRY_DT) VALUES (1, 'INCOME', 'SALARY', '給料', 0, datetime('now'))";

pub const TEST_INSERT_CATEGORY3: &str = "INSERT INTO CATEGORY3 (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, CATEGORY3_NAME, DISPLAY_ORDER, ENTRY_DT) VALUES (1, 'INCOME', 'SALARY', 'MONTHLY', '月給', 0, datetime('now'))";

pub const TEST_INSERT_TRANSACTION_HEADER: &str = r#"
INSERT INTO TRANSACTIONS_HEADER
(USER_ID, CATEGORY1_CODE, FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE, TRANSACTION_DATE, TOTAL_AMOUNT, ENTRY_DT)
VALUES (1, 'INCOME', 'NONE', 'NONE', datetime('now'), 1000, datetime('now'))
"#;

pub const TEST_CREATE_OLD_TRANSACTIONS_DETAIL_TABLE: &str = r#"
CREATE TABLE TRANSACTIONS_DETAIL (
    DETAIL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TRANSACTION_ID INTEGER NOT NULL,
    CATEGORY2_CODE VARCHAR(50) NOT NULL,
    CATEGORY3_CODE VARCHAR(50) NOT NULL,
    ITEM_NAME TEXT NOT NULL,
    AMOUNT INTEGER NOT NULL,
    TAX_AMOUNT INTEGER DEFAULT 0,
    TAX_RATE INTEGER DEFAULT 8,
    MEMO_ID INTEGER,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS_HEADER(TRANSACTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (MEMO_ID) REFERENCES MEMOS(MEMO_ID),
    CHECK (ITEM_NAME != '')
)
"#;

pub const TEST_INSERT_TRANSACTION_DETAIL: &str = r#"
INSERT INTO TRANSACTIONS_DETAIL
(TRANSACTION_ID, CATEGORY2_CODE, CATEGORY3_CODE, ITEM_NAME, AMOUNT, ENTRY_DT)
VALUES (1, 'SALARY', 'MONTHLY', 'Test Item', 1000, datetime('now'))
"#;

pub const TEST_SELECT_MIGRATED_TRANSACTION_DETAIL: &str = "SELECT DETAIL_ID, TRANSACTION_ID, USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, ITEM_NAME, AMOUNT FROM TRANSACTIONS_DETAIL WHERE DETAIL_ID = 1";

// ============================================================================
// Category Initialization Queries
// ============================================================================

pub const CATEGORY_INSERT_CATEGORY1: &str = r#"
INSERT INTO CATEGORY1 (USER_ID, CATEGORY1_CODE, DISPLAY_ORDER, CATEGORY1_NAME, IS_DISABLED, ENTRY_DT) 
VALUES (?, ?, ?, ?, 0, ?)
"#;

pub const CATEGORY_INSERT_CATEGORY1_I18N: &str = r#"
INSERT INTO CATEGORY1_I18N (USER_ID, CATEGORY1_CODE, LANG_CODE, CATEGORY1_NAME_I18N, ENTRY_DT) 
VALUES (?, ?, ?, ?, ?)
"#;

// ============================================================================
// Test-only Data Setup Queries
// ============================================================================

// Test data setup queries
pub const TEST_CATEGORY_INSERT_CATEGORY1: &str = "INSERT INTO CATEGORY1 (USER_ID, CATEGORY1_CODE, DISPLAY_ORDER, CATEGORY1_NAME, IS_DISABLED, ENTRY_DT) VALUES (?, ?, ?, ?, ?, datetime('now'))";

pub const TEST_CATEGORY_INSERT_CATEGORY1_I18N: &str = "INSERT INTO CATEGORY1_I18N (USER_ID, CATEGORY1_CODE, LANG_CODE, CATEGORY1_NAME_I18N, ENTRY_DT) VALUES (?, ?, ?, ?, datetime('now'))";

pub const TEST_USER_GET_PASSWORD_BY_ID: &str = "SELECT PAW FROM USERS WHERE USER_ID = ?";

// ============================================================================
// Transaction Management Service Queries
// ============================================================================

// Transaction CRUD operations
// PR7 (Fable-5 #19): the legacy `TRANSACTION_INSERT` / `_SELECT_BY_ID`
// / `_UPDATE` constants targeted a `TRANSACTIONS` table that no
// migration ever created. The three service methods that used them
// (`add_transaction` / `get_transaction` / `update_transaction`) were
// unreachable from any Tauri command and have been deleted alongside
// this comment. `TRANSACTION_DELETE` below is kept because it targets
// the live `TRANSACTIONS_HEADER` table and backs `delete_transaction`.

pub const TRANSACTION_DELETE: &str = r#"
DELETE FROM TRANSACTIONS_HEADER 
WHERE USER_ID = ? AND TRANSACTION_ID = ?
"#;

// Transaction list queries (base queries - WHERE clause is built dynamically)
pub const TRANSACTION_COUNT_BASE: &str = "SELECT COUNT(*) FROM TRANSACTIONS_HEADER t WHERE ";

pub const TRANSACTION_LIST_BASE: &str = r#"
SELECT
    t.TRANSACTION_ID, t.USER_ID, t.SHOP_ID, t.TRANSACTION_DATE,
    t.CATEGORY1_CODE, t.FROM_ACCOUNT_CODE, t.TO_ACCOUNT_CODE,
    t.TOTAL_AMOUNT, t.TAX_ROUNDING_TYPE, t.MEMO_ID, t.IS_SCHEDULED,
    c1.CATEGORY1_NAME,
    a1.ACCOUNT_NAME as FROM_ACCOUNT_NAME,
    a2.ACCOUNT_NAME as TO_ACCOUNT_NAME,
    m.MEMO_TEXT
FROM TRANSACTIONS_HEADER t
LEFT JOIN CATEGORY1 c1 ON t.USER_ID = c1.USER_ID AND t.CATEGORY1_CODE = c1.CATEGORY1_CODE
LEFT JOIN ACCOUNTS a1 ON t.USER_ID = a1.USER_ID AND t.FROM_ACCOUNT_CODE = a1.ACCOUNT_CODE
LEFT JOIN ACCOUNTS a2 ON t.USER_ID = a2.USER_ID AND t.TO_ACCOUNT_CODE = a2.ACCOUNT_CODE
LEFT JOIN MEMOS m ON t.MEMO_ID = m.MEMO_ID
WHERE 
"#;

pub const TRANSACTION_LIST_ORDER: &str = " ORDER BY t.TRANSACTION_DATE DESC, t.TRANSACTION_ID DESC";

// Keyword filter: substring match against memo text on the header row and
// on any detail row of the header. Two `?` placeholders — bind the same
// escaped LIKE pattern twice. Paired with `ESCAPE '\'` so caller-supplied
// LIKE metacharacters (`%`, `_`, `\`) match literally.
pub const TRANSACTION_KEYWORD_MEMO_FILTER: &str = r"(EXISTS (SELECT 1 FROM MEMOS mh
    WHERE mh.MEMO_ID = t.MEMO_ID
      AND mh.MEMO_TEXT LIKE ? ESCAPE '\')
   OR EXISTS (SELECT 1 FROM TRANSACTIONS_DETAIL td
    JOIN MEMOS md ON md.MEMO_ID = td.MEMO_ID
    WHERE td.USER_ID = t.USER_ID
      AND td.TRANSACTION_ID = t.TRANSACTION_ID
      AND md.MEMO_TEXT LIKE ? ESCAPE '\'))";


// ============================================================================
// Transaction Tables Migration
// ============================================================================

pub const CREATE_MEMOS_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS MEMOS (
    MEMO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    MEMO_TEXT TEXT NOT NULL,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CHECK (MEMO_TEXT != '')
)
"#;

pub const CREATE_TRANSACTIONS_HEADER_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS TRANSACTIONS_HEADER (
    TRANSACTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    SHOP_ID INTEGER,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    FROM_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TO_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TRANSACTION_DATE DATETIME NOT NULL,
    TOTAL_AMOUNT INTEGER NOT NULL,
    TAX_ROUNDING_TYPE INTEGER DEFAULT 0,
    TAX_INCLUDED_TYPE INTEGER DEFAULT 1 NOT NULL,
    MEMO_ID INTEGER,
    IS_DISABLED INTEGER DEFAULT 0,
    IS_SCHEDULED INTEGER DEFAULT 0,
    RULE_ID INTEGER,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now', 'localtime')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID, CATEGORY1_CODE) REFERENCES CATEGORY1(USER_ID, CATEGORY1_CODE),
    FOREIGN KEY (USER_ID, FROM_ACCOUNT_CODE) REFERENCES ACCOUNTS(USER_ID, ACCOUNT_CODE),
    FOREIGN KEY (USER_ID, TO_ACCOUNT_CODE) REFERENCES ACCOUNTS(USER_ID, ACCOUNT_CODE)
)
"#;

pub const CREATE_TRANSACTIONS_DETAIL_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS TRANSACTIONS_DETAIL (
    DETAIL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TRANSACTION_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    CATEGORY2_CODE VARCHAR(50),
    CATEGORY3_CODE VARCHAR(50),
    ITEM_NAME TEXT NOT NULL,
    AMOUNT INTEGER NOT NULL,
    TAX_AMOUNT INTEGER DEFAULT 0,
    TAX_RATE INTEGER DEFAULT 8,
    AMOUNT_INCLUDING_TAX INTEGER,
    PRODUCT_ID INTEGER,
    MEMO_ID INTEGER,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS_HEADER(TRANSACTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE SET NULL,
    FOREIGN KEY (MEMO_ID) REFERENCES MEMOS(MEMO_ID),
    CHECK (ITEM_NAME != '')
)
"#;

// ============================================================================
// Transaction Detail Table Migration Queries
// ============================================================================

pub const CHECK_TRANSACTIONS_DETAIL_HAS_USER_ID: &str = r#"
SELECT COUNT(*) as count
FROM pragma_table_info('TRANSACTIONS_DETAIL')
WHERE name = 'USER_ID'
"#;

pub const MIGRATE_TRANSACTIONS_DETAIL_CREATE_NEW: &str = r#"
CREATE TABLE TRANSACTIONS_DETAIL_NEW (
    DETAIL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TRANSACTION_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    CATEGORY2_CODE VARCHAR(50),
    CATEGORY3_CODE VARCHAR(50),
    ITEM_NAME TEXT NOT NULL,
    AMOUNT INTEGER NOT NULL,
    TAX_AMOUNT INTEGER DEFAULT 0,
    TAX_RATE INTEGER DEFAULT 8,
    AMOUNT_INCLUDING_TAX INTEGER,
    PRODUCT_ID INTEGER,
    MEMO_ID INTEGER,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS_HEADER(TRANSACTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE SET NULL,
    FOREIGN KEY (MEMO_ID) REFERENCES MEMOS(MEMO_ID),
    CHECK (ITEM_NAME != '')
)
"#;

pub const MIGRATE_TRANSACTIONS_DETAIL_COPY_DATA: &str = r#"
INSERT INTO TRANSACTIONS_DETAIL_NEW (
    DETAIL_ID, TRANSACTION_ID, USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE,
    ITEM_NAME, AMOUNT, TAX_AMOUNT, TAX_RATE, MEMO_ID, ENTRY_DT, UPDATE_DT
)
SELECT
    d.DETAIL_ID, d.TRANSACTION_ID, h.USER_ID, h.CATEGORY1_CODE, d.CATEGORY2_CODE, d.CATEGORY3_CODE,
    d.ITEM_NAME, d.AMOUNT, d.TAX_AMOUNT, d.TAX_RATE, d.MEMO_ID, d.ENTRY_DT, d.UPDATE_DT
FROM TRANSACTIONS_DETAIL d
INNER JOIN TRANSACTIONS_HEADER h ON d.TRANSACTION_ID = h.TRANSACTION_ID
"#;

pub const MIGRATE_TRANSACTIONS_DETAIL_DROP_OLD: &str = "DROP TABLE TRANSACTIONS_DETAIL";

pub const MIGRATE_TRANSACTIONS_DETAIL_RENAME_NEW: &str = "ALTER TABLE TRANSACTIONS_DETAIL_NEW RENAME TO TRANSACTIONS_DETAIL";

// PR15 (Fable-5 #20): SHOPS `UNIQUE(USER_ID, SHOP_NAME)` migration.
// dbaccess.sql adds the inline constraint for fresh installs; these
// constants back the idempotent migration for existing DBs.

/// Any pre-existing unique index (auto-index from an inline UNIQUE or a
/// manually created one from a previous migration run) that covers
/// exactly `(USER_ID, SHOP_NAME)`. The migration skips its work when
/// this returns > 0.
pub const SHOPS_HAS_UNIQUE_USER_NAME_INDEX: &str = r#"
SELECT COUNT(*)
FROM sqlite_master m
WHERE m.type = 'index'
  AND m.tbl_name = 'SHOPS'
  AND EXISTS (
      SELECT 1 FROM pragma_index_list('SHOPS') il
      WHERE il.name = m.name AND il."unique" = 1
  )
  AND (
      SELECT GROUP_CONCAT(name, ',') FROM (
          SELECT name FROM pragma_index_info(m.name) ORDER BY seqno
      )
  ) = 'USER_ID,SHOP_NAME'
"#;

/// Repoint every TRANSACTIONS_HEADER.SHOP_ID that references a
/// non-survivor SHOPS row onto the survivor of its (USER_ID, SHOP_NAME)
/// group. Devin #118 review: shops are soft-deleted (SHOP_DELETE_LOGICAL
/// sets IS_DISABLED=1), and the add-time dedup check only counts
/// IS_DISABLED=0 rows, so a legitimate DB can carry a disabled old row
/// (smaller id) and an active re-created row (larger id). The survivor
/// prefers `IS_DISABLED=0` first, then smallest `SHOP_ID` — so the
/// currently-visible shop always wins and only-disabled groups fall
/// back to the smallest id.
pub const MIGRATE_SHOPS_UNIQUE_REPOINT_HEADER: &str = r#"
UPDATE TRANSACTIONS_HEADER
SET SHOP_ID = (
    SELECT s_survivor.SHOP_ID
    FROM SHOPS s_survivor
    WHERE s_survivor.USER_ID = (
              SELECT USER_ID FROM SHOPS WHERE SHOP_ID = TRANSACTIONS_HEADER.SHOP_ID
          )
      AND s_survivor.SHOP_NAME = (
              SELECT SHOP_NAME FROM SHOPS WHERE SHOP_ID = TRANSACTIONS_HEADER.SHOP_ID
          )
    ORDER BY s_survivor.IS_DISABLED ASC, s_survivor.SHOP_ID ASC
    LIMIT 1
)
WHERE SHOP_ID IN (
    SELECT s.SHOP_ID FROM SHOPS s
    WHERE EXISTS (
        SELECT 1 FROM SHOPS s2
        WHERE s2.USER_ID = s.USER_ID
          AND s2.SHOP_NAME = s.SHOP_NAME
          AND (s2.IS_DISABLED < s.IS_DISABLED
               OR (s2.IS_DISABLED = s.IS_DISABLED AND s2.SHOP_ID < s.SHOP_ID))
    )
)
"#;

/// Same shape as [`MIGRATE_SHOPS_UNIQUE_REPOINT_HEADER`] for the
/// recurring-rule table — including the active-preferred survivor rule.
pub const MIGRATE_SHOPS_UNIQUE_REPOINT_RECURRING: &str = r#"
UPDATE RECURRING_RULES
SET SHOP_ID = (
    SELECT s_survivor.SHOP_ID
    FROM SHOPS s_survivor
    WHERE s_survivor.USER_ID = (
              SELECT USER_ID FROM SHOPS WHERE SHOP_ID = RECURRING_RULES.SHOP_ID
          )
      AND s_survivor.SHOP_NAME = (
              SELECT SHOP_NAME FROM SHOPS WHERE SHOP_ID = RECURRING_RULES.SHOP_ID
          )
    ORDER BY s_survivor.IS_DISABLED ASC, s_survivor.SHOP_ID ASC
    LIMIT 1
)
WHERE SHOP_ID IN (
    SELECT s.SHOP_ID FROM SHOPS s
    WHERE EXISTS (
        SELECT 1 FROM SHOPS s2
        WHERE s2.USER_ID = s.USER_ID
          AND s2.SHOP_NAME = s.SHOP_NAME
          AND (s2.IS_DISABLED < s.IS_DISABLED
               OR (s2.IS_DISABLED = s.IS_DISABLED AND s2.SHOP_ID < s.SHOP_ID))
    )
)
"#;

/// Delete non-survivor SHOPS rows within each (USER_ID, SHOP_NAME)
/// group, using the same active-preferred ordering as the repoint
/// steps above. Safe to run after the repoint — no live reference is
/// left pointing at the doomed rows.
pub const MIGRATE_SHOPS_UNIQUE_DELETE_DUPLICATES: &str = r#"
DELETE FROM SHOPS
WHERE EXISTS (
    SELECT 1 FROM SHOPS s2
    WHERE s2.USER_ID = SHOPS.USER_ID
      AND s2.SHOP_NAME = SHOPS.SHOP_NAME
      AND (s2.IS_DISABLED < SHOPS.IS_DISABLED
           OR (s2.IS_DISABLED = SHOPS.IS_DISABLED AND s2.SHOP_ID < SHOPS.SHOP_ID))
)
"#;

/// Create the unique index that enforces (USER_ID, SHOP_NAME) going
/// forward. `IF NOT EXISTS` makes the migration itself re-runnable.
pub const MIGRATE_SHOPS_UNIQUE_CREATE_INDEX: &str = r#"
CREATE UNIQUE INDEX IF NOT EXISTS idx_shops_user_unique_name
    ON SHOPS(USER_ID, SHOP_NAME)
"#;

// Fable-5 review #11: SHOPS `FOREIGN KEY (USER_ID) REFERENCES USERS`
// missing `ON DELETE CASCADE`. Sibling master tables (ACCOUNTS,
// PRODUCTS, MANUFACTURERS, TRANSACTIONS_HEADER, MEMOS) all cascade
// on user deletion, so deleting a user with SHOPS rows fails with
// `FOREIGN KEY constraint failed` and aborts the whole DELETE.
// SQLite has no `ALTER TABLE ... ADD/MODIFY FOREIGN KEY` — the FK
// clause is baked into the CREATE statement — so the migration
// recreates the table with the same shape plus the CASCADE clause,
// copies every row, drops the old table, renames the new one, and
// restores the indexes.

/// Any FK entry from SHOPS to USERS whose `on_delete` action is
/// `CASCADE`. Zero means the migration must run; > 0 means fresh
/// installs and previously-migrated DBs — both no-ops.
pub const SHOPS_HAS_USER_CASCADE_FK: &str = r#"
SELECT COUNT(*)
FROM pragma_foreign_key_list('SHOPS')
WHERE "table" = 'USERS' AND on_delete = 'CASCADE'
"#;

/// Recreate SHOPS with the CASCADE FK (and the sibling UNIQUE
/// constraint already added by `migrate_shops_unique`). This is a
/// pure DDL step — the shape mirrors `res/sql/dbaccess.sql` exactly
/// except for the auto-generated column list order guarantee. Kept
/// as a plain CREATE (not `IF NOT EXISTS`) because the migration
/// only reaches this statement after asserting the new name is free.
pub const MIGRATE_SHOPS_CASCADE_CREATE_NEW_TABLE: &str = r#"
CREATE TABLE SHOPS_NEW (
    SHOP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    SHOP_NAME TEXT NOT NULL,
    MEMO TEXT,
    DISPLAY_ORDER INTEGER NOT NULL DEFAULT 0,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    UNIQUE(USER_ID, SHOP_NAME)
)
"#;

/// Copy every SHOPS row into SHOPS_NEW verbatim. Column list spelled
/// out so the copy stays correct even if a later migration appends a
/// column to `SHOPS_NEW` without touching this constant — the extra
/// column would take its DEFAULT and the old rows would still line
/// up on the original columns.
pub const MIGRATE_SHOPS_CASCADE_COPY_ROWS: &str = r#"
INSERT INTO SHOPS_NEW
    (SHOP_ID, USER_ID, SHOP_NAME, MEMO, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT, UPDATE_DT)
SELECT
    SHOP_ID, USER_ID, SHOP_NAME, MEMO, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT, UPDATE_DT
FROM SHOPS
"#;

pub const MIGRATE_SHOPS_CASCADE_DROP_OLD_TABLE: &str = "DROP TABLE SHOPS";

pub const MIGRATE_SHOPS_CASCADE_RENAME_TABLE: &str = "ALTER TABLE SHOPS_NEW RENAME TO SHOPS";

/// FK enforcement is per-connection in SQLite. The SHOPS cascade
/// migration flips it off for the recreate step (DROP would otherwise
/// trip the parent-check from tables that reference SHOPS.SHOP_ID) and
/// flips it back on before returning. Kept as constants so the test
/// path and the production path share the exact strings — CodeRabbit
/// on #128: "SQL literals in db.rs" belong in `sql_queries.rs` so a
/// future PRAGMA rename can't drift between the two.
pub const PRAGMA_FOREIGN_KEYS_OFF: &str = "PRAGMA foreign_keys = OFF";
pub const PRAGMA_FOREIGN_KEYS_ON: &str = "PRAGMA foreign_keys = ON";

/// Reports one row per FK violation. The SHOPS cascade migration runs
/// this after the recreate as a belt-and-braces guard so a botched
/// copy is caught immediately rather than at the next query.
pub const PRAGMA_FOREIGN_KEY_CHECK: &str = "PRAGMA foreign_key_check";

/// Recreate the non-unique index dropped along with the old table.
/// The inline `UNIQUE(USER_ID, SHOP_NAME)` on the new table already
/// gives us the auto-index for the unique constraint; the
/// `idx_shops_user_unique_name` created by `migrate_shops_unique` is
/// then re-created with `IF NOT EXISTS` for extra safety on DBs that
/// used to depend on it by name.
pub const MIGRATE_SHOPS_CASCADE_CREATE_USER_ORDER_INDEX: &str = r#"
CREATE INDEX IF NOT EXISTS idx_shops_user
    ON SHOPS(USER_ID, DISPLAY_ORDER)
"#;

// Check if CATEGORY2_CODE has NOT NULL constraint (notnull=1 means NOT NULL)
pub const CHECK_CATEGORY2_NOT_NULL: &str = r#"
SELECT COALESCE(MAX("notnull"), 0) as is_not_null
FROM pragma_table_info('TRANSACTIONS_DETAIL')
WHERE name = 'CATEGORY2_CODE'
"#;

// Copy data preserving AMOUNT_INCLUDING_TAX for nullable migration
pub const MIGRATE_NULLABLE_CATEGORY_COPY_DATA: &str = r#"
INSERT INTO TRANSACTIONS_DETAIL_NEW (
    DETAIL_ID, TRANSACTION_ID, USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE,
    ITEM_NAME, AMOUNT, TAX_AMOUNT, TAX_RATE, AMOUNT_INCLUDING_TAX, MEMO_ID, ENTRY_DT, UPDATE_DT
)
SELECT
    DETAIL_ID, TRANSACTION_ID, USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE,
    ITEM_NAME, AMOUNT, TAX_AMOUNT, TAX_RATE, AMOUNT_INCLUDING_TAX, MEMO_ID, ENTRY_DT, UPDATE_DT
FROM TRANSACTIONS_DETAIL
"#;

// ============================================================================
// Recurring Scheduled Transactions Tables (v2.1.0)
// ============================================================================

// Holds the cycle definition + HEADER template fields for one recurring rule.
// MONTH_DAY_RULE_TYPE distinguishes the four MonthlyDayRule variants and
// supersedes the older IS_END_OF_MONTH flag (which lacked DayOfMonthOrEnd).
// Group membership of generated occurrences is established by the RULE_ID
// foreign key on each TRANSACTIONS_HEADER row (no linked-list bookkeeping).
pub const CREATE_RECURRING_RULES_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS RECURRING_RULES (
    RULE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    RULE_NAME TEXT,
    PERIOD_UNIT TEXT NOT NULL,
    PERIOD_INTERVAL INTEGER NOT NULL,
    ANCHOR_DATE DATE,
    DAY_OF_WEEK INTEGER,
    MONTH_DAY_RULE_TYPE TEXT,
    DAY_OF_MONTH INTEGER,
    WEEK_OF_MONTH INTEGER,
    MONTH_OF_YEAR INTEGER,
    HOLIDAY_SHIFT_TYPE INTEGER DEFAULT 0,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    SHOP_ID INTEGER,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    FROM_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TO_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TOTAL_AMOUNT INTEGER NOT NULL,
    TAX_ROUNDING_TYPE INTEGER DEFAULT 0,
    TAX_INCLUDED_TYPE INTEGER DEFAULT 1 NOT NULL,
    MEMO_ID INTEGER,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now', 'localtime')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID, CATEGORY1_CODE) REFERENCES CATEGORY1(USER_ID, CATEGORY1_CODE),
    FOREIGN KEY (USER_ID, FROM_ACCOUNT_CODE) REFERENCES ACCOUNTS(USER_ID, ACCOUNT_CODE),
    FOREIGN KEY (USER_ID, TO_ACCOUNT_CODE) REFERENCES ACCOUNTS(USER_ID, ACCOUNT_CODE)
)
"#;

// 1:1 with RECURRING_RULES enforced by RULE_ID UNIQUE (DB-level prong of the
// triple defense; frontend + backend validation are the other two).
pub const CREATE_RECURRING_RULE_DETAILS_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS RECURRING_RULE_DETAILS (
    RULE_DETAIL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    RULE_ID INTEGER NOT NULL UNIQUE,
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    CATEGORY2_CODE VARCHAR(50),
    CATEGORY3_CODE VARCHAR(50),
    ITEM_NAME TEXT NOT NULL,
    AMOUNT INTEGER NOT NULL,
    TAX_AMOUNT INTEGER DEFAULT 0,
    TAX_RATE INTEGER DEFAULT 8,
    AMOUNT_INCLUDING_TAX INTEGER,
    MEMO_ID INTEGER,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (RULE_ID) REFERENCES RECURRING_RULES(RULE_ID) ON DELETE CASCADE,
    FOREIGN KEY (MEMO_ID) REFERENCES MEMOS(MEMO_ID),
    CHECK (ITEM_NAME != '')
)
"#;

// System-defined holidays (e.g. transcribed from the jpholiday crate).
pub const CREATE_HOLIDAYS_STANDARD_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS HOLIDAYS_STANDARD (
    STANDARD_HOLIDAY_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    LOCALE TEXT NOT NULL,
    HOLIDAY_DATE DATE NOT NULL,
    HOLIDAY_NAME TEXT NOT NULL,
    UNIQUE (LOCALE, HOLIDAY_DATE)
)
"#;

// User-added holidays (company holidays, personal days off, etc).
pub const CREATE_HOLIDAYS_USER_CUSTOM_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS HOLIDAYS_USER_CUSTOM (
    USER_HOLIDAY_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    HOLIDAY_DATE DATE NOT NULL,
    HOLIDAY_NAME TEXT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    UNIQUE (USER_ID, HOLIDAY_DATE)
)
"#;

// ============================================================================
// Recurring Scheduled Transactions Queries (v2.1.0)
// ============================================================================

// Bind order matches the create_rule_with_instances() service. FIRST_TRANSACTION_ID
// stays NULL on insert and is patched after the first instance is generated.
pub const RECURRING_RULES_INSERT: &str = r#"
INSERT INTO RECURRING_RULES (
    USER_ID, RULE_NAME,
    PERIOD_UNIT, PERIOD_INTERVAL,
    ANCHOR_DATE, DAY_OF_WEEK, MONTH_DAY_RULE_TYPE,
    DAY_OF_MONTH, WEEK_OF_MONTH, MONTH_OF_YEAR,
    HOLIDAY_SHIFT_TYPE,
    START_DATE, END_DATE,
    SHOP_ID, CATEGORY1_CODE, FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE,
    TOTAL_AMOUNT, TAX_ROUNDING_TYPE, TAX_INCLUDED_TYPE, MEMO_ID
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
"#;

pub const RECURRING_RULE_DETAILS_INSERT: &str = r#"
INSERT INTO RECURRING_RULE_DETAILS (
    RULE_ID, USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE,
    ITEM_NAME, AMOUNT, TAX_AMOUNT, TAX_RATE, AMOUNT_INCLUDING_TAX, MEMO_ID
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
"#;

// HEADER insert for a generated occurrence: IS_SCHEDULED is fixed to 1 here so
// callers cannot accidentally write a non-scheduled row through this path.
// RULE_ID is the only group identifier — no linked-list bookkeeping.
pub const TRANSACTIONS_HEADER_INSERT_FOR_RECURRING: &str = r#"
INSERT INTO TRANSACTIONS_HEADER (
    USER_ID, SHOP_ID, TRANSACTION_DATE, CATEGORY1_CODE,
    FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE,
    TOTAL_AMOUNT, TAX_ROUNDING_TYPE, TAX_INCLUDED_TYPE, MEMO_ID,
    IS_SCHEDULED, RULE_ID, ENTRY_DT
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?, datetime('now', 'localtime'))
"#;

// Cascade-delete path for a recurring rule: drop every generated HEADER first
// (their DETAILs cascade via the existing FK). Caller still has to DELETE the
// RECURRING_RULES row afterwards (which cascades RECURRING_RULE_DETAILS).
pub const TRANSACTIONS_HEADER_DELETE_BY_RULE: &str = r#"
DELETE FROM TRANSACTIONS_HEADER
WHERE RULE_ID = ? AND USER_ID = ?
"#;

// Detach-mode path: orphan generated HEADERs from the rule before the rule
// goes away. Used when the user wants to remove the rule template but keep
// the already-generated occurrences as standalone scheduled transactions.
// On new DBs the FK ON DELETE SET NULL would do this automatically; we run
// it explicitly so older DBs (created before the FK existed) behave the same.
pub const TRANSACTIONS_HEADER_DETACH_FROM_RULE: &str = r#"
UPDATE TRANSACTIONS_HEADER
SET RULE_ID = NULL
WHERE RULE_ID = ? AND USER_ID = ?
"#;

pub const RECURRING_RULES_DELETE: &str = r#"
DELETE FROM RECURRING_RULES
WHERE RULE_ID = ? AND USER_ID = ?
"#;

// List active recurring rules for a user, with the number of occurrences
// each one has currently materialized in TRANSACTIONS_HEADER. The LEFT JOIN
// keeps rules that have not generated any rows yet (count = 0).
pub const RECURRING_RULES_LIST_BY_USER: &str = r#"
SELECT
    r.RULE_ID,
    r.RULE_NAME,
    r.PERIOD_UNIT,
    r.PERIOD_INTERVAL,
    r.START_DATE,
    r.END_DATE,
    r.TOTAL_AMOUNT,
    r.HOLIDAY_SHIFT_TYPE,
    COUNT(h.TRANSACTION_ID) AS OCCURRENCE_COUNT
FROM RECURRING_RULES r
LEFT JOIN TRANSACTIONS_HEADER h
    ON h.RULE_ID = r.RULE_ID AND h.IS_SCHEDULED = 1
WHERE r.USER_ID = ? AND COALESCE(r.IS_DISABLED, 0) = 0
GROUP BY r.RULE_ID
ORDER BY r.RULE_ID DESC
"#;

// ============================================================================
// Unspecified Master Data Insertion
// ============================================================================

pub const INSERT_UNSPECIFIED_ACCOUNT: &str = r#"
INSERT OR IGNORE INTO ACCOUNTS (USER_ID, ACCOUNT_CODE, ACCOUNT_NAME, TEMPLATE_CODE, INITIAL_BALANCE, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT)
VALUES (?, 'NONE', '指定なし', 'NONE', 0, 0, 0, datetime('now'))
"#;

pub const INSERT_UNSPECIFIED_CATEGORY2: &str = r#"
INSERT OR IGNORE INTO CATEGORY2 (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY2_NAME, DISPLAY_ORDER, ENTRY_DT)
SELECT USER_ID, CATEGORY1_CODE, 'NONE', '指定なし', 0, datetime('now')
FROM CATEGORY1
WHERE USER_ID = ?
"#;

pub const INSERT_UNSPECIFIED_CATEGORY3: &str = r#"
INSERT OR IGNORE INTO CATEGORY3 (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, CATEGORY3_NAME, DISPLAY_ORDER, ENTRY_DT)
SELECT USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, 'NONE', '指定なし', 0, datetime('now')
FROM CATEGORY2
WHERE USER_ID = ?
"#;

// ============================================================================
// Transaction Header Queries
// ============================================================================

pub const TRANSACTION_HEADER_INSERT: &str = r#"
INSERT INTO TRANSACTIONS_HEADER (
    USER_ID, SHOP_ID, TRANSACTION_DATE, CATEGORY1_CODE, FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE,
    TOTAL_AMOUNT, TAX_ROUNDING_TYPE, TAX_INCLUDED_TYPE, MEMO_ID, IS_SCHEDULED, ENTRY_DT
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
"#;

pub const TRANSACTION_HEADER_GET_BY_ID: &str = r#"
SELECT TRANSACTION_ID, USER_ID, SHOP_ID, TRANSACTION_DATE, CATEGORY1_CODE,
       FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE, TOTAL_AMOUNT, TAX_ROUNDING_TYPE,
       TAX_INCLUDED_TYPE, MEMO_ID, IS_DISABLED, IS_SCHEDULED, ENTRY_DT, UPDATE_DT
FROM TRANSACTIONS_HEADER
WHERE TRANSACTION_ID = ? AND USER_ID = ?
"#;

pub const TRANSACTION_HEADER_GET_BY_ID_WITH_MEMO: &str = r#"
SELECT
    t.TRANSACTION_ID, t.USER_ID, t.SHOP_ID, t.TRANSACTION_DATE, t.CATEGORY1_CODE,
    t.FROM_ACCOUNT_CODE, t.TO_ACCOUNT_CODE, t.TOTAL_AMOUNT, t.TAX_ROUNDING_TYPE,
    t.TAX_INCLUDED_TYPE, t.MEMO_ID, t.IS_DISABLED, t.IS_SCHEDULED, t.ENTRY_DT, t.UPDATE_DT,
    m.MEMO_TEXT
FROM TRANSACTIONS_HEADER t
LEFT JOIN MEMOS m ON t.MEMO_ID = m.MEMO_ID
WHERE t.TRANSACTION_ID = ? AND t.USER_ID = ?
"#;

pub const TRANSACTION_HEADER_UPDATE: &str = r#"
UPDATE TRANSACTIONS_HEADER
SET SHOP_ID = ?, TRANSACTION_DATE = ?, CATEGORY1_CODE = ?, FROM_ACCOUNT_CODE = ?,
    TO_ACCOUNT_CODE = ?, TOTAL_AMOUNT = ?, TAX_ROUNDING_TYPE = ?, TAX_INCLUDED_TYPE = ?,
    MEMO_ID = ?, UPDATE_DT = datetime('now')
WHERE TRANSACTION_ID = ? AND USER_ID = ?
"#;

/// Read just the columns needed to recompute a transaction's TOTAL_AMOUNT
/// from its details. Used by the auto-recalculation path; does not need to
/// hydrate the full TransactionHeader struct.
pub const TRANSACTION_HEADER_GET_ROUNDING_TYPE: &str = r#"
SELECT TAX_ROUNDING_TYPE
FROM TRANSACTIONS_HEADER
WHERE TRANSACTION_ID = ? AND USER_ID = ?
"#;

/// Cheap existence + ownership check used before inserting a
/// TRANSACTIONS_DETAIL row. The FK on TRANSACTIONS_DETAIL.TRANSACTION_ID
/// only enforces "some header exists" — it does not check that the
/// header belongs to the caller. Without this SELECT, a request that
/// bypasses the frontend (e.g. a direct `invoke` with another user's
/// transaction_id) would attach one user's detail to another user's
/// header.
pub const TRANSACTION_HEADER_EXISTS_FOR_USER: &str = r#"
SELECT 1
FROM TRANSACTIONS_HEADER
WHERE TRANSACTION_ID = ? AND USER_ID = ?
LIMIT 1
"#;

/// Update only TOTAL_AMOUNT (and the audit timestamp). Used when the header
/// total is recalculated from details after a detail edit, without touching
/// any of the other header fields the user just edited.
pub const TRANSACTION_HEADER_UPDATE_TOTAL_ONLY: &str = r#"
UPDATE TRANSACTIONS_HEADER
SET TOTAL_AMOUNT = ?, UPDATE_DT = datetime('now')
WHERE TRANSACTION_ID = ? AND USER_ID = ?
"#;

/// Update only the tax-rounding and tax-included-type columns. Used by the
/// bulk recalc flow when a different (rounding, included) pattern matches the
/// user-entered TOTAL_AMOUNT — we adopt the matching pattern so future
/// recalculations stay in agreement, but we leave TOTAL_AMOUNT alone.
pub const TRANSACTION_HEADER_UPDATE_TAX_SETTINGS_ONLY: &str = r#"
UPDATE TRANSACTIONS_HEADER
SET TAX_ROUNDING_TYPE = ?, TAX_INCLUDED_TYPE = ?, UPDATE_DT = datetime('now')
WHERE TRANSACTION_ID = ? AND USER_ID = ?
"#;

pub const TRANSACTION_HEADER_DELETE: &str = r#"
DELETE FROM TRANSACTIONS_HEADER
WHERE TRANSACTION_ID = ? AND USER_ID = ?
"#;

pub const TRANSACTION_HEADER_CONFIRM_SCHEDULED: &str = r#"
UPDATE TRANSACTIONS_HEADER
SET IS_SCHEDULED = 0, UPDATE_DT = datetime('now')
WHERE TRANSACTION_ID = ? AND USER_ID = ? AND IS_SCHEDULED = 1
"#;

// ============================================================================
// Transaction Detail Queries
// ============================================================================

pub const TRANSACTION_DETAIL_INSERT: &str = r#"
INSERT INTO TRANSACTIONS_DETAIL (
    TRANSACTION_ID, CATEGORY2_CODE, CATEGORY3_CODE, ITEM_NAME,
    AMOUNT, TAX_AMOUNT, TAX_RATE, MEMO_ID, ENTRY_DT
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
"#;

pub const TRANSACTION_DETAIL_GET_BY_HEADER: &str = r#"
SELECT DETAIL_ID, TRANSACTION_ID, CATEGORY2_CODE, CATEGORY3_CODE,
       ITEM_NAME, AMOUNT, TAX_AMOUNT, TAX_RATE, MEMO_ID, ENTRY_DT, UPDATE_DT
FROM TRANSACTIONS_DETAIL
WHERE TRANSACTION_ID = ?
ORDER BY DETAIL_ID
"#;

/// Read the minimal set of columns that drive `calculate_recommended_total`:
/// pre-tax AMOUNT, the optional tax-included counterpart, and the per-detail
/// tax rate. Scoped by USER_ID so callers can rely on session isolation.
pub const TRANSACTION_DETAIL_GET_FOR_RECALC: &str = r#"
SELECT AMOUNT, AMOUNT_INCLUDING_TAX, TAX_RATE
FROM TRANSACTIONS_DETAIL
WHERE TRANSACTION_ID = ? AND USER_ID = ?
"#;

/// PR12 (Fable-5 #32): every detail row for a user in one SELECT,
/// consumed by `recalculate_all_transaction_totals` after grouping by
/// `TRANSACTION_ID` in Rust. Prior shape ran the single-transaction
/// query above once per header (N+1); this version replaces the whole
/// loop's fetch with a single scan. The DETAIL_ID tie-breaker in ORDER
/// BY is inherited from the schema so callers get the same in-detail
/// order as the older per-transaction query.
pub const TRANSACTION_DETAIL_GET_ALL_FOR_USER_RECALC: &str = r#"
SELECT TRANSACTION_ID, AMOUNT, AMOUNT_INCLUDING_TAX, TAX_RATE
FROM TRANSACTIONS_DETAIL
WHERE USER_ID = ?
ORDER BY TRANSACTION_ID, DETAIL_ID
"#;

pub const TRANSACTION_DETAIL_UPDATE: &str = r#"
UPDATE TRANSACTIONS_DETAIL
SET CATEGORY2_CODE = ?, CATEGORY3_CODE = ?, ITEM_NAME = ?,
    AMOUNT = ?, TAX_AMOUNT = ?, TAX_RATE = ?, MEMO_ID = ?,
    UPDATE_DT = datetime('now')
WHERE DETAIL_ID = ? AND TRANSACTION_ID = ?
"#;

pub const TRANSACTION_DETAIL_DELETE: &str = r#"
DELETE FROM TRANSACTIONS_DETAIL
WHERE DETAIL_ID = ?
"#;

// ============================================================================
// Memo Queries
// ============================================================================

pub const MEMO_INSERT: &str = r#"
INSERT INTO MEMOS (USER_ID, MEMO_TEXT, ENTRY_DT)
VALUES (?, ?, datetime('now', 'localtime'))
"#;

pub const MEMO_GET_BY_ID: &str = r#"
SELECT MEMO_ID, MEMO_TEXT, ENTRY_DT, UPDATE_DT
FROM MEMOS
WHERE MEMO_ID = ?
"#;

pub const MEMO_UPDATE: &str = r#"
UPDATE MEMOS
SET MEMO_TEXT = ?, UPDATE_DT = datetime('now', 'localtime')
WHERE MEMO_ID = ?
"#;

pub const MEMO_FIND_BY_TEXT: &str = r#"
SELECT MEMO_ID, MEMO_TEXT, ENTRY_DT, UPDATE_DT
FROM MEMOS
WHERE USER_ID = ? AND MEMO_TEXT = ?
LIMIT 1
"#;

pub const MEMO_DELETE: &str = r#"
DELETE FROM MEMOS WHERE MEMO_ID = ?
"#;

pub const MEMO_COUNT_USAGE: &str = r#"
SELECT
  (SELECT COUNT(*) FROM TRANSACTIONS_HEADER WHERE MEMO_ID = ?)
  + (SELECT COUNT(*) FROM TRANSACTIONS_DETAIL WHERE MEMO_ID = ?)
  + (SELECT COUNT(*) FROM RECURRING_RULES WHERE MEMO_ID = ?)
  + (SELECT COUNT(*) FROM RECURRING_RULE_DETAILS WHERE MEMO_ID = ?)
  AS usage_count
"#;

// ============================================================================
// Shop Service Queries
// ============================================================================

pub const SHOP_GET_ALL: &str = r#"
SELECT SHOP_ID, USER_ID, SHOP_NAME, MEMO, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT, UPDATE_DT
FROM SHOPS
WHERE USER_ID = ? AND IS_DISABLED = 0
ORDER BY DISPLAY_ORDER, SHOP_NAME
"#;

pub const SHOP_GET_BY_ID: &str = r#"
SELECT SHOP_ID, USER_ID, SHOP_NAME, MEMO, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT, UPDATE_DT
FROM SHOPS
WHERE USER_ID = ? AND SHOP_ID = ?
"#;

pub const SHOP_GET_NEXT_DISPLAY_ORDER: &str = r#"
SELECT COALESCE(MAX(DISPLAY_ORDER), 0) + 1
FROM SHOPS
WHERE USER_ID = ?
"#;

pub const SHOP_INSERT: &str = r#"
INSERT INTO SHOPS (USER_ID, SHOP_NAME, MEMO, DISPLAY_ORDER, ENTRY_DT)
VALUES (?, ?, ?, ?, datetime('now'))
"#;

pub const SHOP_UPDATE: &str = r#"
UPDATE SHOPS
SET SHOP_NAME = ?, MEMO = ?, DISPLAY_ORDER = ?, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND SHOP_ID = ?
"#;

pub const SHOP_DELETE_LOGICAL: &str = r#"
UPDATE SHOPS
SET IS_DISABLED = 1, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND SHOP_ID = ?
"#;

/// Delete-lock guard: does any transaction or recurring rule still name
/// this shop? Binds: (user_id, shop_id, user_id, shop_id).
pub const SHOP_CHECK_IN_USE: &str = r#"
SELECT EXISTS(
    SELECT 1 FROM TRANSACTIONS_HEADER
    WHERE USER_ID = ? AND SHOP_ID = ?
    UNION ALL
    SELECT 1 FROM RECURRING_RULES
    WHERE USER_ID = ? AND SHOP_ID = ?
)
"#;

pub const SHOP_CHECK_DUPLICATE_FOR_ADD: &str = r#"
SELECT COUNT(*) as count
FROM SHOPS
WHERE USER_ID = ? AND SHOP_NAME = ? AND IS_DISABLED = 0
"#;

pub const SHOP_CHECK_DUPLICATE_FOR_UPDATE: &str = r#"
SELECT COUNT(*) as count
FROM SHOPS
WHERE USER_ID = ? AND SHOP_NAME = ? AND SHOP_ID != ? AND IS_DISABLED = 0
"#;

// ============================================================================
// Manufacturer Service Queries
// ============================================================================

pub const MANUFACTURER_GET_ALL: &str = r#"
SELECT MANUFACTURER_ID, USER_ID, MANUFACTURER_NAME, MEMO, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT, UPDATE_DT
FROM MANUFACTURERS
WHERE USER_ID = ? AND IS_DISABLED = 0
ORDER BY DISPLAY_ORDER, MANUFACTURER_NAME
"#;

pub const MANUFACTURER_GET_ALL_INCLUDING_DISABLED: &str = r#"
SELECT MANUFACTURER_ID, USER_ID, MANUFACTURER_NAME, MEMO, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT, UPDATE_DT
FROM MANUFACTURERS
WHERE USER_ID = ?
ORDER BY DISPLAY_ORDER, MANUFACTURER_NAME
"#;

pub const MANUFACTURER_GET_BY_ID: &str = r#"
SELECT MANUFACTURER_ID, USER_ID, MANUFACTURER_NAME, MEMO, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT, UPDATE_DT
FROM MANUFACTURERS
WHERE USER_ID = ? AND MANUFACTURER_ID = ?
"#;

pub const MANUFACTURER_GET_NEXT_DISPLAY_ORDER: &str = r#"
SELECT COALESCE(MAX(DISPLAY_ORDER), 0) + 1
FROM MANUFACTURERS
WHERE USER_ID = ?
"#;

pub const MANUFACTURER_INSERT: &str = r#"
INSERT INTO MANUFACTURERS (USER_ID, MANUFACTURER_NAME, MEMO, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, datetime('now'))
"#;

pub const MANUFACTURER_UPDATE: &str = r#"
UPDATE MANUFACTURERS
SET MANUFACTURER_NAME = ?, MEMO = ?, DISPLAY_ORDER = ?, IS_DISABLED = ?, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND MANUFACTURER_ID = ?
"#;

pub const MANUFACTURER_DELETE_LOGICAL: &str = r#"
UPDATE MANUFACTURERS
SET IS_DISABLED = 1, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND MANUFACTURER_ID = ?
"#;

/// Delete-lock guard: does any product (active OR disabled) still name
/// this manufacturer? A disabled product row keeps the FK link and would
/// silently be orphaned to NULL by the ON DELETE SET NULL on physical
/// removal — a logical delete leaves the manufacturer's IS_DISABLED=1
/// row referenced by a disabled product's MANUFACTURER_ID, which the
/// products screen still surfaces via "Show disabled". Blocking here
/// keeps that consistent. Binds: (user_id, manufacturer_id).
pub const MANUFACTURER_CHECK_IN_USE: &str = r#"
SELECT EXISTS(
    SELECT 1 FROM PRODUCTS
    WHERE USER_ID = ? AND MANUFACTURER_ID = ?
)
"#;

pub const MANUFACTURER_CHECK_DUPLICATE_FOR_ADD: &str = r#"
SELECT COUNT(*) as count
FROM MANUFACTURERS
WHERE USER_ID = ? AND MANUFACTURER_NAME = ? AND IS_DISABLED = 0
"#;

pub const MANUFACTURER_CHECK_DUPLICATE_FOR_UPDATE: &str = r#"
SELECT COUNT(*) as count
FROM MANUFACTURERS
WHERE USER_ID = ? AND MANUFACTURER_NAME = ? AND MANUFACTURER_ID != ? AND IS_DISABLED = 0
"#;

// ============================================================================
// Product Service Queries
// ============================================================================

// The JOIN on MANUFACTURER_ID additionally requires the manufacturer to
// belong to the same user as the product. Without `m.USER_ID = p.USER_ID`,
// a product row whose MANUFACTURER_ID happens to collide with another
// user's manufacturer_id (perfectly possible — the pool is
// AUTOINCREMENT per table, not per user) would display *that other
// user's* manufacturer name. Mirrors the scoping already in
// TRANSACTION_DETAIL_GET_WITH_INFO. Fable-5 review #13.
pub const PRODUCT_GET_ALL: &str = r#"
SELECT p.PRODUCT_ID, p.USER_ID, p.PRODUCT_NAME,
       p.MANUFACTURER_ID, m.MANUFACTURER_NAME,
       p.MEMO, p.DISPLAY_ORDER, p.IS_DISABLED, p.ENTRY_DT, p.UPDATE_DT
FROM PRODUCTS p
LEFT JOIN MANUFACTURERS m
    ON p.MANUFACTURER_ID = m.MANUFACTURER_ID
   AND m.USER_ID = p.USER_ID
WHERE p.USER_ID = ? AND p.IS_DISABLED = 0
ORDER BY p.DISPLAY_ORDER, p.PRODUCT_NAME
"#;

pub const PRODUCT_GET_ALL_INCLUDING_DISABLED: &str = r#"
SELECT p.PRODUCT_ID, p.USER_ID, p.PRODUCT_NAME,
       p.MANUFACTURER_ID, m.MANUFACTURER_NAME,
       p.MEMO, p.DISPLAY_ORDER, p.IS_DISABLED, p.ENTRY_DT, p.UPDATE_DT
FROM PRODUCTS p
LEFT JOIN MANUFACTURERS m
    ON p.MANUFACTURER_ID = m.MANUFACTURER_ID
   AND m.USER_ID = p.USER_ID
WHERE p.USER_ID = ?
ORDER BY p.DISPLAY_ORDER, p.PRODUCT_NAME
"#;

pub const PRODUCT_GET_BY_ID: &str = r#"
SELECT p.PRODUCT_ID, p.USER_ID, p.PRODUCT_NAME,
       p.MANUFACTURER_ID, m.MANUFACTURER_NAME,
       p.MEMO, p.DISPLAY_ORDER, p.IS_DISABLED, p.ENTRY_DT, p.UPDATE_DT
FROM PRODUCTS p
LEFT JOIN MANUFACTURERS m
    ON p.MANUFACTURER_ID = m.MANUFACTURER_ID
   AND m.USER_ID = p.USER_ID
WHERE p.USER_ID = ? AND p.PRODUCT_ID = ?
"#;

pub const PRODUCT_GET_NEXT_DISPLAY_ORDER: &str = r#"
SELECT COALESCE(MAX(DISPLAY_ORDER), 0) + 1
FROM PRODUCTS
WHERE USER_ID = ?
"#;

pub const PRODUCT_INSERT: &str = r#"
INSERT INTO PRODUCTS (USER_ID, PRODUCT_NAME, MANUFACTURER_ID, MEMO, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
"#;

pub const PRODUCT_UPDATE: &str = r#"
UPDATE PRODUCTS
SET PRODUCT_NAME = ?, MANUFACTURER_ID = ?, MEMO = ?, DISPLAY_ORDER = ?, IS_DISABLED = ?, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND PRODUCT_ID = ?
"#;

pub const PRODUCT_DELETE_LOGICAL: &str = r#"
UPDATE PRODUCTS
SET IS_DISABLED = 1, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND PRODUCT_ID = ?
"#;

/// Delete-lock guard: does any transaction detail still name this
/// product? TRANSACTIONS_DETAIL has no USER_ID column so scoping runs
/// through TRANSACTIONS_HEADER. Detail rows from IS_DISABLED=1
/// transactions still count — the history reads them and the product
/// handle must not be recycled while any history references it.
/// Binds: (user_id, product_id).
pub const PRODUCT_CHECK_IN_USE: &str = r#"
SELECT EXISTS(
    SELECT 1
    FROM TRANSACTIONS_DETAIL td
    JOIN TRANSACTIONS_HEADER th ON td.TRANSACTION_ID = th.TRANSACTION_ID
    WHERE th.USER_ID = ? AND td.PRODUCT_ID = ?
)
"#;

pub const PRODUCT_CHECK_DUPLICATE_FOR_ADD: &str = r#"
SELECT COUNT(*) as count
FROM PRODUCTS
WHERE USER_ID = ? AND PRODUCT_NAME = ? AND IS_DISABLED = 0
"#;

pub const PRODUCT_CHECK_DUPLICATE_FOR_UPDATE: &str = r#"
SELECT COUNT(*) as count
FROM PRODUCTS
WHERE USER_ID = ? AND PRODUCT_NAME = ? AND PRODUCT_ID != ? AND IS_DISABLED = 0
"#;

// Autocomplete lookup for transaction detail entry (v2.6.0 master integration).
// Substring (LIKE %?%) match on PRODUCT_NAME, scoped to the user's enabled
// products, joined with the manufacturer for the "商品名 (メーカー名)"
// dropdown label. Capped at 20 rows so a typo doesn't paint the whole DB into
// the suggestion list.
pub const PRODUCT_SEARCH_BY_NAME: &str = r#"
SELECT p.PRODUCT_ID, p.USER_ID, p.PRODUCT_NAME,
       p.MANUFACTURER_ID, m.MANUFACTURER_NAME,
       p.MEMO, p.DISPLAY_ORDER, p.IS_DISABLED, p.ENTRY_DT, p.UPDATE_DT
FROM PRODUCTS p
LEFT JOIN MANUFACTURERS m
    ON p.MANUFACTURER_ID = m.MANUFACTURER_ID
   AND m.USER_ID = p.USER_ID
WHERE p.USER_ID = ? AND p.IS_DISABLED = 0 AND p.PRODUCT_NAME LIKE ?
ORDER BY p.PRODUCT_NAME
LIMIT 20
"#;

/// Cheap existence + ownership check for MANUFACTURERS. Used before
/// binding `manufacturer_id` into `PRODUCT_INSERT` / `PRODUCT_UPDATE` so
/// a request from user B cannot attach one of B's products to a
/// manufacturer_id that belongs to user A. See Fable-5 review #13.
pub const MANUFACTURER_EXISTS_FOR_USER: &str = r#"
SELECT 1
FROM MANUFACTURERS
WHERE MANUFACTURER_ID = ? AND USER_ID = ?
LIMIT 1
"#;

// ============================================================================
// Test Queries - Shop
// ============================================================================

pub const TEST_SHOP_CREATE_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS SHOPS (
    SHOP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    SHOP_NAME TEXT NOT NULL,
    MEMO TEXT,
    DISPLAY_ORDER INTEGER NOT NULL DEFAULT 0,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
)
"#;

// ============================================================================
// Test Queries - Manufacturer
// ============================================================================

pub const TEST_MANUFACTURER_CREATE_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS MANUFACTURERS (
    MANUFACTURER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    MANUFACTURER_NAME TEXT NOT NULL,
    MEMO TEXT,
    DISPLAY_ORDER INTEGER NOT NULL DEFAULT 0,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    UNIQUE(USER_ID, MANUFACTURER_NAME)
)
"#;

// ============================================================================
// Test Queries - Product
// ============================================================================

pub const TEST_PRODUCT_CREATE_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    PRODUCT_NAME TEXT NOT NULL,
    MANUFACTURER_ID INTEGER,
    MEMO TEXT,
    DISPLAY_ORDER INTEGER NOT NULL DEFAULT 0,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURERS(MANUFACTURER_ID) ON DELETE SET NULL,
    UNIQUE(USER_ID, PRODUCT_NAME)
)
"#;

// ============================================================================
// Test Queries - Delete-lock reference tables
// ----------------------------------------------------------------------------
// Reference tables needed by the master-delete-lock tests. The
// TRANSACTIONS_HEADER minimal is `TEST_TRANSACTION_CREATE_HEADER_TABLE`
// above (both this file and the aggregation tests use it via IF NOT
// EXISTS). RECURRING_RULES and TRANSACTIONS_DETAIL get their own
// stripped-down definitions so the master-service tests do not have to
// spin up CATEGORY1 + MEMOS + PRODUCTS just to insert one reference row.
// FOREIGN KEYs deliberately omitted.
// ============================================================================
pub const TEST_CREATE_RECURRING_RULES_MINIMAL: &str = r#"
CREATE TABLE IF NOT EXISTS RECURRING_RULES (
    RULE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    SHOP_ID INTEGER,
    FROM_ACCOUNT_CODE VARCHAR(50),
    TO_ACCOUNT_CODE VARCHAR(50)
)
"#;

pub const TEST_CREATE_TRANSACTIONS_DETAIL_MINIMAL: &str = r#"
CREATE TABLE IF NOT EXISTS TRANSACTIONS_DETAIL (
    DETAIL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TRANSACTION_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER
)
"#;

/// Insert one TRANSACTIONS_HEADER row for shop delete-lock tests. Binds
/// `(user_id, shop_id)`; the required NOT NULL columns
/// (CATEGORY1_CODE / FROM_ACCOUNT_CODE / TO_ACCOUNT_CODE /
/// TRANSACTION_DATE / TOTAL_AMOUNT) get harmless literals — the guard
/// only reads USER_ID and SHOP_ID.
pub const TEST_INSERT_TRANSACTIONS_HEADER_SHOP_REF: &str = r#"
INSERT INTO TRANSACTIONS_HEADER
    (USER_ID, SHOP_ID, CATEGORY1_CODE, FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE, TRANSACTION_DATE, TOTAL_AMOUNT)
VALUES (?, ?, 'EXPENSE', 'CASH', 'CASH', '2026-01-01', 0)
"#;

pub const TEST_INSERT_RECURRING_RULES_SHOP_REF: &str = r#"
INSERT INTO RECURRING_RULES (USER_ID, SHOP_ID, FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE)
VALUES (?, ?, 'CASH', 'CASH')
"#;

/// Insert one TRANSACTIONS_HEADER row for account delete-lock tests.
/// Binds `(user_id, from_account_code, to_account_code)`.
pub const TEST_INSERT_TRANSACTIONS_HEADER_ACCOUNT_REF: &str = r#"
INSERT INTO TRANSACTIONS_HEADER
    (USER_ID, CATEGORY1_CODE, FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE, TRANSACTION_DATE, TOTAL_AMOUNT)
VALUES (?, 'EXPENSE', ?, ?, '2026-01-01', 0)
"#;

pub const TEST_INSERT_RECURRING_RULES_ACCOUNT_REF: &str = r#"
INSERT INTO RECURRING_RULES (USER_ID, FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE)
VALUES (?, ?, ?)
"#;

/// Insert one TRANSACTIONS_HEADER row scoped to `user_id`, used to give
/// a TRANSACTIONS_DETAIL row a parent for product delete-lock tests.
/// Binds `(user_id)`.
pub const TEST_INSERT_TRANSACTIONS_HEADER_USER_ONLY: &str = r#"
INSERT INTO TRANSACTIONS_HEADER
    (USER_ID, CATEGORY1_CODE, FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE, TRANSACTION_DATE, TOTAL_AMOUNT)
VALUES (?, 'EXPENSE', 'CASH', 'CASH', '2026-01-01', 0)
"#;

pub const TEST_INSERT_TRANSACTIONS_DETAIL_PRODUCT_REF: &str = r#"
INSERT INTO TRANSACTIONS_DETAIL (TRANSACTION_ID, PRODUCT_ID)
VALUES (?, ?)
"#;

/// Insert one active PRODUCTS row that points at a manufacturer,
/// scoped to `user_id`. Binds `(user_id, product_name, manufacturer_id)`.
/// Used by the manufacturer delete-lock tests to build a reference.
pub const TEST_INSERT_PRODUCT_WITH_MANUFACTURER: &str = r#"
INSERT INTO PRODUCTS (USER_ID, PRODUCT_NAME, MANUFACTURER_ID, DISPLAY_ORDER)
VALUES (?, ?, ?, 0)
"#;

/// Same as `TEST_INSERT_PRODUCT_WITH_MANUFACTURER` but marks the row
/// IS_DISABLED=1. The manufacturer guard must still block delete when
/// only disabled products reference it — the FK link is preserved and
/// the products screen still surfaces the row under "Show disabled".
pub const TEST_INSERT_PRODUCT_WITH_MANUFACTURER_DISABLED: &str = r#"
INSERT INTO PRODUCTS (USER_ID, PRODUCT_NAME, MANUFACTURER_ID, DISPLAY_ORDER, IS_DISABLED)
VALUES (?, ?, ?, 0, 1)
"#;

// ============================================================================
// Transaction Detail Management Queries (with JOIN)
// ============================================================================

pub const TRANSACTION_HEADER_GET_WITH_INFO: &str = r#"
SELECT 
    h.TRANSACTION_ID,
    h.USER_ID,
    h.SHOP_ID,
    s.SHOP_NAME,
    h.TRANSACTION_DATE,
    h.CATEGORY1_CODE,
    h.FROM_ACCOUNT_CODE,
    h.TO_ACCOUNT_CODE,
    fa.ACCOUNT_NAME as FROM_ACCOUNT_NAME,
    ta.ACCOUNT_NAME as TO_ACCOUNT_NAME,
    h.TOTAL_AMOUNT,
    h.TAX_ROUNDING_TYPE,
    h.TAX_INCLUDED_TYPE,
    h.MEMO_ID,
    m.MEMO_TEXT,
    h.IS_DISABLED,
    h.IS_SCHEDULED,
    h.ENTRY_DT,
    h.UPDATE_DT
FROM TRANSACTIONS_HEADER h
LEFT JOIN SHOPS s ON h.SHOP_ID = s.SHOP_ID
LEFT JOIN ACCOUNTS fa ON h.FROM_ACCOUNT_CODE = fa.ACCOUNT_CODE AND h.USER_ID = fa.USER_ID
LEFT JOIN ACCOUNTS ta ON h.TO_ACCOUNT_CODE = ta.ACCOUNT_CODE AND h.USER_ID = ta.USER_ID
LEFT JOIN MEMOS m ON h.MEMO_ID = m.MEMO_ID
WHERE h.TRANSACTION_ID = ? AND h.USER_ID = ?
"#;

pub const TRANSACTION_DETAIL_GET_WITH_INFO: &str = r#"
SELECT
    d.DETAIL_ID,
    d.TRANSACTION_ID,
    d.USER_ID,
    d.CATEGORY1_CODE,
    d.CATEGORY2_CODE,
    d.CATEGORY3_CODE,
    c1.CATEGORY1_NAME,
    c2.CATEGORY2_NAME,
    c3.CATEGORY3_NAME,
    d.ITEM_NAME,
    d.AMOUNT,
    d.TAX_AMOUNT,
    d.TAX_RATE,
    d.AMOUNT_INCLUDING_TAX,
    d.PRODUCT_ID,
    p.PRODUCT_NAME,
    mf.MANUFACTURER_NAME,
    d.MEMO_ID,
    m.MEMO_TEXT,
    d.ENTRY_DT,
    d.UPDATE_DT
FROM TRANSACTIONS_DETAIL d
LEFT JOIN CATEGORY1 c1 ON d.CATEGORY1_CODE = c1.CATEGORY1_CODE AND d.USER_ID = c1.USER_ID
LEFT JOIN CATEGORY2 c2 ON d.CATEGORY1_CODE = c2.CATEGORY1_CODE
    AND d.CATEGORY2_CODE = c2.CATEGORY2_CODE AND d.USER_ID = c2.USER_ID
LEFT JOIN CATEGORY3 c3 ON d.CATEGORY1_CODE = c3.CATEGORY1_CODE
    AND d.CATEGORY2_CODE = c3.CATEGORY2_CODE
    AND d.CATEGORY3_CODE = c3.CATEGORY3_CODE AND d.USER_ID = c3.USER_ID
LEFT JOIN PRODUCTS p ON d.PRODUCT_ID = p.PRODUCT_ID AND p.USER_ID = d.USER_ID
LEFT JOIN MANUFACTURERS mf ON p.MANUFACTURER_ID = mf.MANUFACTURER_ID AND mf.USER_ID = d.USER_ID
LEFT JOIN MEMOS m ON d.MEMO_ID = m.MEMO_ID
WHERE d.TRANSACTION_ID = ? AND d.USER_ID = ?
ORDER BY d.DETAIL_ID
"#;

pub const TRANSACTION_DETAIL_INSERT_FULL: &str = r#"
INSERT INTO TRANSACTIONS_DETAIL (
    TRANSACTION_ID, USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE,
    ITEM_NAME, AMOUNT, TAX_AMOUNT, TAX_RATE, AMOUNT_INCLUDING_TAX, PRODUCT_ID, MEMO_ID
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
"#;

pub const TRANSACTION_DETAIL_UPDATE_FULL: &str = r#"
UPDATE TRANSACTIONS_DETAIL SET
    CATEGORY1_CODE = ?,
    CATEGORY2_CODE = ?,
    CATEGORY3_CODE = ?,
    ITEM_NAME = ?,
    AMOUNT = ?,
    TAX_AMOUNT = ?,
    TAX_RATE = ?,
    AMOUNT_INCLUDING_TAX = ?,
    PRODUCT_ID = ?,
    MEMO_ID = ?,
    UPDATE_DT = datetime('now')
WHERE DETAIL_ID = ? AND USER_ID = ?
"#;

pub const TRANSACTION_DETAIL_GET_BY_ID: &str = r#"
SELECT DETAIL_ID, TRANSACTION_ID, USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE,
       ITEM_NAME, AMOUNT, TAX_AMOUNT, TAX_RATE, AMOUNT_INCLUDING_TAX, PRODUCT_ID, MEMO_ID, ENTRY_DT, UPDATE_DT
FROM TRANSACTIONS_DETAIL
WHERE DETAIL_ID = ? AND USER_ID = ?
"#;

pub const TRANSACTION_DETAIL_DELETE_BY_ID: &str = r#"
DELETE FROM TRANSACTIONS_DETAIL
WHERE DETAIL_ID = ? AND USER_ID = ?
"#;

// ============================================================================
// Transaction Service Test Queries
// ============================================================================

pub const TEST_TRANSACTION_CREATE_USERS_TABLE: &str = r#"
CREATE TABLE USERS (
    USER_ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    PAW TEXT NOT NULL,
    ROLE INTEGER NOT NULL,
    ENTRY_DT DATETIME NOT NULL,
    UPDATE_DT DATETIME
)
"#;

pub const TEST_TRANSACTION_INSERT_USER: &str = "INSERT INTO USERS (USER_ID, NAME, PAW, ROLE, ENTRY_DT) VALUES (2, 'testuser', 'hash', 1, datetime('now'))";

// Fable-5 #7 (CodeRabbit on #130): test-only SQL used by the
// `add_transaction_detail` memo-dedup / atomicity pins. Kept here as
// named constants so a rename or schema change fails in ONE place
// instead of leaving stale strings inside the test module — matches
// the "Never hardcode SQL in service code" rule.

/// List MEMO_ID for all details of a given transaction, in DETAIL_ID
/// order, filtering out NULLs. Used to confirm two adds land on the
/// same MEMO_ID.
pub const TEST_ADD_DETAIL_SELECT_MEMO_IDS_BY_TXN: &str =
    "SELECT MEMO_ID FROM TRANSACTIONS_DETAIL \
     WHERE TRANSACTION_ID = ? AND MEMO_ID IS NOT NULL ORDER BY DETAIL_ID";

/// Count MEMOS rows carrying the same (USER_ID, MEMO_TEXT). Used to
/// confirm the dedup fix does not create a duplicate row.
pub const TEST_ADD_DETAIL_COUNT_MEMOS_BY_TEXT: &str =
    "SELECT COUNT(*) FROM MEMOS WHERE USER_ID = ? AND MEMO_TEXT = ?";

/// Insert a MEMOS row and return the new MEMO_ID. Used by the
/// header-sharing pin to seed a header memo the add path should
/// reuse.
pub const TEST_ADD_DETAIL_INSERT_MEMO_RETURNING_ID: &str =
    "INSERT INTO MEMOS (USER_ID, MEMO_TEXT) VALUES (?, ?) RETURNING MEMO_ID";

/// Point a given header at a specific MEMO_ID.
pub const TEST_ADD_DETAIL_UPDATE_HEADER_MEMO_ID: &str =
    "UPDATE TRANSACTIONS_HEADER SET MEMO_ID = ? WHERE TRANSACTION_ID = ?";

/// Fetch the MEMO_ID a specific detail row references (nullable).
pub const TEST_ADD_DETAIL_SELECT_DETAIL_MEMO_ID: &str =
    "SELECT MEMO_ID FROM TRANSACTIONS_DETAIL WHERE DETAIL_ID = ?";

/// Count MEMOS rows carrying a specific text (any user). Used by the
/// rollback pin to confirm a failed add did not leak a MEMOS row.
pub const TEST_ADD_DETAIL_COUNT_MEMOS_ORPHAN: &str =
    "SELECT COUNT(*) FROM MEMOS WHERE MEMO_TEXT = ?";

pub const TEST_TRANSACTION_CREATE_MEMOS_TABLE: &str = r#"
CREATE TABLE MEMOS (
    MEMO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    MEMO_TEXT TEXT NOT NULL,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
)
"#;

pub const TEST_TRANSACTION_CREATE_CATEGORY1_TABLE: &str = r#"
CREATE TABLE CATEGORY1 (
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    CATEGORY1_NAME TEXT NOT NULL,
    DISPLAY_ORDER INTEGER DEFAULT 0,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    PRIMARY KEY (USER_ID, CATEGORY1_CODE)
)
"#;

pub const TEST_TRANSACTION_INSERT_CATEGORY1: &str = "INSERT INTO CATEGORY1 (USER_ID, CATEGORY1_CODE, CATEGORY1_NAME) VALUES (2, 'EXPENSE', '支出')";

pub const TEST_TRANSACTION_CREATE_ACCOUNTS_TABLE: &str = r#"
CREATE TABLE ACCOUNTS (
    ACCOUNT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    ACCOUNT_CODE VARCHAR(50) NOT NULL,
    ACCOUNT_NAME TEXT NOT NULL,
    TEMPLATE_CODE VARCHAR(50) NOT NULL,
    INITIAL_BALANCE INTEGER DEFAULT 0,
    DISPLAY_ORDER INTEGER DEFAULT 0,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    UNIQUE(USER_ID, ACCOUNT_CODE)
)
"#;

pub const TEST_TRANSACTION_INSERT_ACCOUNT_CASH: &str = "INSERT INTO ACCOUNTS (USER_ID, ACCOUNT_CODE, ACCOUNT_NAME, TEMPLATE_CODE) VALUES (2, 'CASH', '現金', 'CASH')";

pub const TEST_TRANSACTION_INSERT_ACCOUNT_BANK: &str = "INSERT INTO ACCOUNTS (USER_ID, ACCOUNT_CODE, ACCOUNT_NAME, TEMPLATE_CODE) VALUES (2, 'BANK', '銀行', 'BANK')";

// IF NOT EXISTS so the master-delete-lock tests can also create this from
// their own setup_test_db without racing the balance-computation tests
// that create it inline.
pub const TEST_TRANSACTION_CREATE_HEADER_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS TRANSACTIONS_HEADER (
    TRANSACTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    SHOP_ID INTEGER,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    FROM_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TO_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TRANSACTION_DATE DATETIME NOT NULL,
    TOTAL_AMOUNT INTEGER NOT NULL,
    TAX_ROUNDING_TYPE INTEGER DEFAULT 0,
    TAX_INCLUDED_TYPE INTEGER DEFAULT 1 NOT NULL,
    MEMO_ID INTEGER,
    IS_DISABLED INTEGER DEFAULT 0,
    IS_SCHEDULED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME
)
"#;

pub const TEST_TRANSACTION_CREATE_SHOPS_TABLE: &str = r#"
CREATE TABLE SHOPS (
    SHOP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    SHOP_NAME TEXT NOT NULL,
    MEMO TEXT,
    DISPLAY_ORDER INTEGER DEFAULT 0,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME
)
"#;

pub const TEST_TRANSACTION_CREATE_CATEGORY2_TABLE: &str = r#"
CREATE TABLE CATEGORY2 (
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(64) NOT NULL,
    CATEGORY2_CODE VARCHAR(64) NOT NULL,
    DISPLAY_ORDER INTEGER NOT NULL DEFAULT 0,
    CATEGORY2_NAME VARCHAR(128) NOT NULL,
    IS_DISABLED INTEGER NOT NULL DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    PRIMARY KEY(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE),
    FOREIGN KEY(USER_ID, CATEGORY1_CODE) REFERENCES CATEGORY1(USER_ID, CATEGORY1_CODE) ON DELETE CASCADE
)
"#;

pub const TEST_TRANSACTION_CREATE_CATEGORY3_TABLE: &str = r#"
CREATE TABLE CATEGORY3 (
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(64) NOT NULL,
    CATEGORY2_CODE VARCHAR(64) NOT NULL,
    CATEGORY3_CODE VARCHAR(64) NOT NULL,
    DISPLAY_ORDER INTEGER NOT NULL DEFAULT 0,
    CATEGORY3_NAME VARCHAR(128) NOT NULL,
    IS_DISABLED INTEGER NOT NULL DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    PRIMARY KEY(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE),
    FOREIGN KEY(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE) REFERENCES CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE) ON DELETE CASCADE
)
"#;

pub const TEST_TRANSACTION_CREATE_DETAIL_TABLE: &str = r#"
CREATE TABLE TRANSACTIONS_DETAIL (
    DETAIL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TRANSACTION_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    CATEGORY2_CODE VARCHAR(50),
    CATEGORY3_CODE VARCHAR(50),
    ITEM_NAME TEXT NOT NULL,
    AMOUNT INTEGER NOT NULL,
    TAX_AMOUNT INTEGER DEFAULT 0,
    TAX_RATE INTEGER DEFAULT 8,
    AMOUNT_INCLUDING_TAX INTEGER,
    PRODUCT_ID INTEGER,
    MEMO_ID INTEGER,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS_HEADER(TRANSACTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (MEMO_ID) REFERENCES MEMOS(MEMO_ID),
    -- Fable-5 #7 (CodeRabbit on #130): matches the composite FK the
    -- production schema declares (see `CREATE_TRANSACTIONS_DETAIL_TABLE`
    -- above). Test fixtures seed EXPENSE into CATEGORY1 so happy paths
    -- pass unchanged; the FK now also lets the atomicity pin drive
    -- DETAIL_INSERT into a deterministic FK failure by supplying a
    -- CATEGORY1_CODE that isn't seeded.
    FOREIGN KEY (USER_ID, CATEGORY1_CODE)
        REFERENCES CATEGORY1(USER_ID, CATEGORY1_CODE),
    CHECK (ITEM_NAME != '')
)
"#;

pub const TEST_TRANSACTION_INSERT_CATEGORY2: &str =
    "INSERT INTO CATEGORY2 (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME) VALUES (2, 'EXPENSE', 'FOOD', 1, '食費')";

pub const TEST_TRANSACTION_INSERT_CATEGORY3: &str =
    "INSERT INTO CATEGORY3 (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME) VALUES (2, 'EXPENSE', 'FOOD', 'GROCERY', 1, '食料品')";


// ============================================================================
// Test queries for holiday service
// ============================================================================

pub const TEST_HOLIDAY_CREATE_USERS_TABLE: &str = r#"
CREATE TABLE USERS (
    USER_ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    PAW TEXT NOT NULL,
    ROLE INTEGER NOT NULL,
    HOLIDAY_LOCALE TEXT DEFAULT 'JP',
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now'))
)
"#;

pub const TEST_HOLIDAY_INSERT_USER: &str =
    "INSERT INTO USERS (USER_ID, NAME, PAW, ROLE, HOLIDAY_LOCALE) VALUES (?, ?, 'hash', 1, ?)";

pub const TEST_HOLIDAY_INSERT_STANDARD: &str =
    "INSERT INTO HOLIDAYS_STANDARD (LOCALE, HOLIDAY_DATE, HOLIDAY_NAME) VALUES (?, ?, ?)";

pub const TEST_HOLIDAY_INSERT_CUSTOM: &str =
    "INSERT INTO HOLIDAYS_USER_CUSTOM (USER_ID, HOLIDAY_DATE, HOLIDAY_NAME) VALUES (?, ?, ?)";

// ============================================================================
// Test queries for db migrations
// ============================================================================

// Pre-v2.1.0 USERS schema: no HOLIDAY_LOCALE / WEEK_START_DAY / period columns.
pub const TEST_DB_CREATE_LEGACY_USERS_TABLE: &str = r#"
CREATE TABLE USERS (
    USER_ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    PAW TEXT NOT NULL,
    ROLE INTEGER NOT NULL,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now'))
)
"#;

// Pre-v2.1.0 TRANSACTIONS_HEADER schema: no RULE_ID, but carries the obsolete
// linked-list columns an unreleased dev build added.
pub const TEST_DB_CREATE_LEGACY_HEADER_TABLE: &str = r#"
CREATE TABLE TRANSACTIONS_HEADER (
    TRANSACTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    FROM_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TO_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TRANSACTION_DATE DATETIME NOT NULL,
    TOTAL_AMOUNT INTEGER NOT NULL,
    GROUP_HEAD INTEGER,
    NEXT_TRANSACTION_ID INTEGER,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now'))
)
"#;

pub const TEST_DB_COUNT_TABLE_COLUMN: &str =
    "SELECT COUNT(*) FROM pragma_table_info(?) WHERE name = ?";

pub const TEST_DB_COUNT_TABLE: &str =
    "SELECT COUNT(*) FROM sqlite_master WHERE type = 'table' AND name = ?";

pub const TEST_DB_COUNT_STANDARD_HOLIDAYS: &str =
    "SELECT COUNT(*) FROM HOLIDAYS_STANDARD WHERE LOCALE = 'JP'";

// ============================================================================
// Additional test queries for account service
// ============================================================================

pub const TEST_ACCOUNT_INSERT_HEADER: &str = r#"
INSERT INTO TRANSACTIONS_HEADER
    (USER_ID, CATEGORY1_CODE, FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE,
     TRANSACTION_DATE, TOTAL_AMOUNT, IS_SCHEDULED)
VALUES (?, ?, ?, ?, ?, ?, ?)
"#;

pub const TEST_ACCOUNT_GET_IS_DISABLED: &str =
    "SELECT IS_DISABLED FROM ACCOUNTS WHERE USER_ID = ? AND ACCOUNT_CODE = ?";

pub const TEST_ACCOUNT_INSERT_NONE_TEMPLATE: &str = r#"
INSERT INTO ACCOUNT_TEMPLATES (TEMPLATE_CODE, TEMPLATE_NAME_JA, TEMPLATE_NAME_EN, DISPLAY_ORDER)
VALUES ('NONE', '指定なし', 'Unspecified', 0)
"#;
