// SQL Query Constants
// This module centralizes all SQL queries used in the application

// ============================================================================
// Authentication Service Queries
// ============================================================================

pub const AUTH_GET_USER_BY_NAME: &str = r#"
SELECT USER_ID, NAME, PAW, ROLE, ENTRY_DT, UPDATE_DT 
FROM USERS 
WHERE NAME = ?
"#;

pub const AUTH_GET_NEXT_USER_ID: &str = "SELECT COALESCE(MAX(USER_ID), 0) + 1 as next_id FROM USERS";

pub const AUTH_INSERT_USER: &str = r#"
INSERT INTO USERS (USER_ID, NAME, PAW, ROLE, ENTRY_DT) 
VALUES (?, ?, ?, ?, datetime('now'))
"#;

pub const AUTH_CHECK_TABLE_EXISTS: &str = r#"
SELECT name FROM sqlite_master 
WHERE type='table' AND name='USERS'
"#;

pub const AUTH_COUNT_USERS: &str = "SELECT COUNT(*) as count FROM USERS";

pub const AUTH_COUNT_USERS_BY_ROLE: &str = "SELECT COUNT(*) as count FROM USERS WHERE ROLE = ?";

pub const AUTH_GET_USER_NAME_BY_ID: &str = "SELECT NAME FROM USERS WHERE USER_ID = 1";

pub const AUTH_GET_PASSWORD_BY_ID: &str = "SELECT PAW FROM USERS WHERE USER_ID = 1";

pub const AUTH_GET_ROLE_BY_ID: &str = "SELECT ROLE FROM USERS WHERE USER_ID = 1";

// ============================================================================
// User Management Service Queries
// ============================================================================

pub const USER_LIST_USERS: &str = r#"
SELECT USER_ID, NAME, ROLE, ENTRY_DT, UPDATE_DT 
FROM USERS 
ORDER BY USER_ID
"#;

pub const USER_GET_BY_ID: &str = r#"
SELECT USER_ID, NAME, ROLE, ENTRY_DT, UPDATE_DT 
FROM USERS 
WHERE USER_ID = ?
"#;

pub const USER_CHECK_NAME_EXISTS: &str = "SELECT COUNT(*) as count FROM USERS WHERE NAME = ?";

pub const USER_GET_NEXT_ID: &str = "SELECT COALESCE(MAX(USER_ID), 0) + 1 as next_id FROM USERS";

pub const USER_INSERT: &str = r#"
INSERT INTO USERS (USER_ID, NAME, PAW, ROLE, ENTRY_DT) 
VALUES (?, ?, ?, ?, datetime('now'))
"#;

pub const USER_UPDATE_NAME: &str = r#"
UPDATE USERS 
SET NAME = ?, UPDATE_DT = datetime('now') 
WHERE USER_ID = ?
"#;

pub const USER_CHECK_NAME_EXISTS_EXCLUDING_ID: &str = r#"
SELECT COUNT(*) as count 
FROM USERS 
WHERE NAME = ? AND USER_ID != ?
"#;

pub const USER_UPDATE_PASSWORD: &str = r#"
UPDATE USERS 
SET PAW = ?, UPDATE_DT = datetime('now') 
WHERE USER_ID = ?
"#;

pub const USER_GET_PASSWORD_BY_ID: &str = "SELECT PAW FROM USERS WHERE USER_ID = ?";

pub const USER_DELETE: &str = "DELETE FROM USERS WHERE USER_ID = ?";

// ============================================================================
// Encryption Service Queries
// ============================================================================

pub const ENCRYPTION_LIST_FIELDS: &str = r#"
SELECT FIELD_ID, TABLE_NAME, COLUMN_NAME, DESCRIPTION, IS_ACTIVE 
FROM ENCRYPTED_FIELDS 
WHERE IS_ACTIVE = 1
"#;

pub const ENCRYPTION_GET_NEXT_FIELD_ID: &str = "SELECT COALESCE(MAX(FIELD_ID), 0) + 1 as next_id FROM ENCRYPTED_FIELDS";

pub const ENCRYPTION_INSERT_FIELD: &str = r#"
INSERT INTO ENCRYPTED_FIELDS (FIELD_ID, TABLE_NAME, COLUMN_NAME, DESCRIPTION, IS_ACTIVE, ENTRY_DT) 
VALUES (?, ?, ?, ?, 1, datetime('now'))
"#;

// ============================================================================
// I18N Service Queries
// ============================================================================

pub const I18N_GET_RESOURCE: &str = r#"
SELECT RESOURCE_VALUE 
FROM I18N_RESOURCES 
WHERE RESOURCE_KEY = ? AND LANG_CODE = ?
"#;

pub const I18N_GET_BY_CATEGORY: &str = r#"
SELECT RESOURCE_KEY, RESOURCE_VALUE 
FROM I18N_RESOURCES 
WHERE LANG_CODE = ? AND CATEGORY = ?
"#;

pub const I18N_GET_ALL: &str = r#"
SELECT RESOURCE_KEY, RESOURCE_VALUE 
FROM I18N_RESOURCES 
WHERE LANG_CODE = ?
"#;

pub const I18N_GET_AVAILABLE_LANGUAGES: &str = r#"
SELECT DISTINCT LANG_CODE 
FROM I18N_RESOURCES 
ORDER BY LANG_CODE
"#;

// ============================================================================
// Category Service Queries
// ============================================================================

pub const CATEGORY_COUNT_BY_USER: &str = "SELECT COUNT(*) FROM CATEGORY1 WHERE USER_ID = ?";

pub const CATEGORY1_LIST: &str = r#"
SELECT 
    c.USER_ID,
    c.CATEGORY1_CODE,
    c.DISPLAY_ORDER,
    COALESCE(i18n.CATEGORY1_NAME_I18N, c.CATEGORY1_NAME) as CATEGORY1_NAME,
    c.IS_DISABLED
FROM CATEGORY1 c
LEFT JOIN CATEGORY1_I18N i18n 
    ON c.USER_ID = i18n.USER_ID 
    AND c.CATEGORY1_CODE = i18n.CATEGORY1_CODE 
    AND i18n.LANG_CODE = ?
WHERE c.USER_ID = ? AND c.IS_DISABLED = 0
ORDER BY c.DISPLAY_ORDER
"#;

pub const CATEGORY1_TREE: &str = r#"
SELECT 
    c.CATEGORY1_CODE,
    c.DISPLAY_ORDER,
    COALESCE(i18n.CATEGORY1_NAME_I18N, c.CATEGORY1_NAME) as name
FROM CATEGORY1 c
LEFT JOIN CATEGORY1_I18N i18n 
    ON c.USER_ID = i18n.USER_ID 
    AND c.CATEGORY1_CODE = i18n.CATEGORY1_CODE 
    AND i18n.LANG_CODE = ?
WHERE c.USER_ID = ? AND c.IS_DISABLED = 0
ORDER BY c.DISPLAY_ORDER
"#;

pub const CATEGORY2_TREE: &str = r#"
SELECT 
    c.CATEGORY2_CODE,
    c.DISPLAY_ORDER,
    COALESCE(i18n.CATEGORY2_NAME_I18N, c.CATEGORY2_NAME) as name
FROM CATEGORY2 c
LEFT JOIN CATEGORY2_I18N i18n 
    ON c.USER_ID = i18n.USER_ID 
    AND c.CATEGORY1_CODE = i18n.CATEGORY1_CODE 
    AND c.CATEGORY2_CODE = i18n.CATEGORY2_CODE 
    AND i18n.LANG_CODE = ?
WHERE c.USER_ID = ? AND c.CATEGORY1_CODE = ? AND c.IS_DISABLED = 0
ORDER BY c.DISPLAY_ORDER
"#;

pub const CATEGORY3_TREE: &str = r#"
SELECT 
    c.CATEGORY3_CODE,
    c.DISPLAY_ORDER,
    COALESCE(i18n.CATEGORY3_NAME_I18N, c.CATEGORY3_NAME) as name
FROM CATEGORY3 c
LEFT JOIN CATEGORY3_I18N i18n 
    ON c.USER_ID = i18n.USER_ID 
    AND c.CATEGORY1_CODE = i18n.CATEGORY1_CODE 
    AND c.CATEGORY2_CODE = i18n.CATEGORY2_CODE 
    AND c.CATEGORY3_CODE = i18n.CATEGORY3_CODE 
    AND i18n.LANG_CODE = ?
WHERE c.USER_ID = ? 
    AND c.CATEGORY1_CODE = ? 
    AND c.CATEGORY2_CODE = ? 
    AND c.IS_DISABLED = 0
ORDER BY c.DISPLAY_ORDER
"#;

pub const CATEGORY2_GET_MAX_ORDER: &str = r#"
SELECT COALESCE(MAX(DISPLAY_ORDER), 0) as max_order
FROM CATEGORY2
WHERE USER_ID = ? AND CATEGORY1_CODE = ?
"#;

pub const CATEGORY2_INSERT: &str = r#"
INSERT INTO CATEGORY2 (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, DISPLAY_ORDER, CATEGORY2_NAME, IS_DISABLED, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, 0, datetime('now'))
"#;

pub const CATEGORY2_I18N_INSERT: &str = r#"
INSERT INTO CATEGORY2_I18N (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, LANG_CODE, CATEGORY2_NAME_I18N, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, datetime('now'))
"#;

pub const CATEGORY3_GET_MAX_ORDER: &str = r#"
SELECT COALESCE(MAX(DISPLAY_ORDER), 0) as max_order
FROM CATEGORY3
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ?
"#;

pub const CATEGORY3_INSERT: &str = r#"
INSERT INTO CATEGORY3 (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, DISPLAY_ORDER, CATEGORY3_NAME, IS_DISABLED, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, ?, 0, datetime('now'))
"#;

pub const CATEGORY3_I18N_INSERT: &str = r#"
INSERT INTO CATEGORY3_I18N (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, LANG_CODE, CATEGORY3_NAME_I18N, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
"#;

pub const CATEGORY2_CHECK_DUPLICATE_NAME: &str = r#"
SELECT COUNT(*) as count FROM CATEGORY2_I18N 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_NAME_I18N = ? AND LANG_CODE = ?
"#;

pub const CATEGORY2_CHECK_DUPLICATE_NAME_EXCLUDING: &str = r#"
SELECT COUNT(*) as count FROM CATEGORY2_I18N 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE != ? 
AND LANG_CODE = ? AND CATEGORY2_NAME_I18N = ?
"#;

pub const CATEGORY3_CHECK_DUPLICATE_NAME: &str = r#"
SELECT COUNT(*) as count FROM CATEGORY3_I18N 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND CATEGORY3_NAME_I18N = ? AND LANG_CODE = ?
"#;

pub const CATEGORY3_CHECK_DUPLICATE_NAME_EXCLUDING: &str = r#"
SELECT COUNT(*) as count FROM CATEGORY3_I18N 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? 
AND CATEGORY3_CODE != ? AND LANG_CODE = ? AND CATEGORY3_NAME_I18N = ?
"#;

pub const CATEGORY2_CHECK_DUPLICATE_CODE: &str = r#"
SELECT COUNT(*) as count FROM CATEGORY2 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ?
"#;

pub const CATEGORY3_CHECK_DUPLICATE_CODE: &str = r#"
SELECT COUNT(*) as count FROM CATEGORY3 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND CATEGORY3_CODE = ?
"#;

pub const CATEGORY2_UPDATE: &str = r#"
UPDATE CATEGORY2 
SET CATEGORY2_NAME = ?, UPDATE_DT = datetime('now') 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ?
"#;

pub const CATEGORY2_I18N_UPDATE: &str = r#"
UPDATE CATEGORY2_I18N 
SET CATEGORY2_NAME_I18N = ?, UPDATE_DT = datetime('now') 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND LANG_CODE = ?
"#;

pub const CATEGORY3_UPDATE: &str = r#"
UPDATE CATEGORY3 
SET CATEGORY3_NAME = ?, UPDATE_DT = datetime('now') 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND CATEGORY3_CODE = ?
"#;

pub const CATEGORY3_I18N_UPDATE: &str = r#"
UPDATE CATEGORY3_I18N 
SET CATEGORY3_NAME_I18N = ?, UPDATE_DT = datetime('now') 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND CATEGORY3_CODE = ? AND LANG_CODE = ?
"#;

pub const CATEGORY2_GET_FOR_EDIT: &str = r#"
SELECT 
    c.CATEGORY2_CODE,
    c.CATEGORY2_NAME,
    COALESCE(i18n_ja.CATEGORY2_NAME_I18N, c.CATEGORY2_NAME) as name_ja,
    COALESCE(i18n_en.CATEGORY2_NAME_I18N, c.CATEGORY2_NAME) as name_en
FROM CATEGORY2 c
LEFT JOIN CATEGORY2_I18N i18n_ja 
    ON c.USER_ID = i18n_ja.USER_ID 
    AND c.CATEGORY1_CODE = i18n_ja.CATEGORY1_CODE 
    AND c.CATEGORY2_CODE = i18n_ja.CATEGORY2_CODE 
    AND i18n_ja.LANG_CODE = 'ja'
LEFT JOIN CATEGORY2_I18N i18n_en 
    ON c.USER_ID = i18n_en.USER_ID 
    AND c.CATEGORY1_CODE = i18n_en.CATEGORY1_CODE 
    AND c.CATEGORY2_CODE = i18n_en.CATEGORY2_CODE 
    AND i18n_en.LANG_CODE = 'en'
WHERE c.USER_ID = ? AND c.CATEGORY1_CODE = ? AND c.CATEGORY2_CODE = ?
"#;

pub const CATEGORY3_GET_FOR_EDIT: &str = r#"
SELECT 
    c.CATEGORY3_CODE,
    c.CATEGORY3_NAME,
    COALESCE(i18n_ja.CATEGORY3_NAME_I18N, c.CATEGORY3_NAME) as name_ja,
    COALESCE(i18n_en.CATEGORY3_NAME_I18N, c.CATEGORY3_NAME) as name_en
FROM CATEGORY3 c
LEFT JOIN CATEGORY3_I18N i18n_ja 
    ON c.USER_ID = i18n_ja.USER_ID 
    AND c.CATEGORY1_CODE = i18n_ja.CATEGORY1_CODE 
    AND c.CATEGORY2_CODE = i18n_ja.CATEGORY2_CODE 
    AND c.CATEGORY3_CODE = i18n_ja.CATEGORY3_CODE 
    AND i18n_ja.LANG_CODE = 'ja'
LEFT JOIN CATEGORY3_I18N i18n_en 
    ON c.USER_ID = i18n_en.USER_ID 
    AND c.CATEGORY1_CODE = i18n_en.CATEGORY1_CODE 
    AND c.CATEGORY2_CODE = i18n_en.CATEGORY2_CODE 
    AND c.CATEGORY3_CODE = i18n_en.CATEGORY3_CODE 
    AND i18n_en.LANG_CODE = 'en'
WHERE c.USER_ID = ? AND c.CATEGORY1_CODE = ? AND c.CATEGORY2_CODE = ? AND c.CATEGORY3_CODE = ?
"#;

// ============================================================================
// Category Order Management Queries
// ============================================================================

pub const CATEGORY2_GET_ORDER: &str = r#"
SELECT DISPLAY_ORDER FROM CATEGORY2 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ?
"#;

pub const CATEGORY2_UPDATE_ORDER: &str = r#"
UPDATE CATEGORY2 SET DISPLAY_ORDER = ?, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ?
"#;

pub const CATEGORY2_GET_SIBLING_BY_ORDER: &str = r#"
SELECT CATEGORY2_CODE FROM CATEGORY2
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND DISPLAY_ORDER = ?
"#;

pub const CATEGORY3_GET_ORDER: &str = r#"
SELECT DISPLAY_ORDER FROM CATEGORY3 
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND CATEGORY3_CODE = ?
"#;

pub const CATEGORY3_UPDATE_ORDER: &str = r#"
UPDATE CATEGORY3 SET DISPLAY_ORDER = ?, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND CATEGORY3_CODE = ?
"#;

pub const CATEGORY3_GET_SIBLING_BY_ORDER: &str = r#"
SELECT CATEGORY3_CODE FROM CATEGORY3
WHERE USER_ID = ? AND CATEGORY1_CODE = ? AND CATEGORY2_CODE = ? AND DISPLAY_ORDER = ?
"#;

// ============================================================================
// Account Management Service Queries
// ============================================================================

// Note: get_accounts() and get_account_by_code() use sqlx::query_as! macro
// with hardcoded SQL for compile-time type checking. The queries below are
// provided for reference but not used directly in those functions.

// Account Templates
pub const ACCOUNT_TEMPLATE_LIST: &str = r#"
SELECT TEMPLATE_ID, TEMPLATE_CODE, TEMPLATE_NAME_JA, TEMPLATE_NAME_EN, DISPLAY_ORDER, ENTRY_DT
FROM ACCOUNT_TEMPLATES
ORDER BY DISPLAY_ORDER
"#;

// User Accounts
pub const ACCOUNT_LIST_BY_USER: &str = r#"
SELECT ACCOUNT_ID, USER_ID, ACCOUNT_CODE, ACCOUNT_NAME, TEMPLATE_CODE, 
       INITIAL_BALANCE, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT, UPDATE_DT
FROM ACCOUNTS
WHERE USER_ID = ? AND IS_DISABLED = 0
ORDER BY DISPLAY_ORDER, ACCOUNT_CODE
"#;

pub const ACCOUNT_GET_BY_CODE: &str = r#"
SELECT ACCOUNT_ID, USER_ID, ACCOUNT_CODE, ACCOUNT_NAME, TEMPLATE_CODE, 
       INITIAL_BALANCE, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT, UPDATE_DT
FROM ACCOUNTS
WHERE USER_ID = ? AND ACCOUNT_CODE = ?
"#;

pub const ACCOUNT_CHECK_DUPLICATE_CODE: &str = r#"
SELECT COUNT(*) as count
FROM ACCOUNTS
WHERE USER_ID = ? AND ACCOUNT_CODE = ? AND IS_DISABLED = 0
"#;

pub const ACCOUNT_INSERT: &str = r#"
INSERT INTO ACCOUNTS (USER_ID, ACCOUNT_CODE, ACCOUNT_NAME, TEMPLATE_CODE, 
                      INITIAL_BALANCE, DISPLAY_ORDER, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
"#;

pub const ACCOUNT_UPSERT: &str = r#"
INSERT INTO ACCOUNTS (USER_ID, ACCOUNT_CODE, ACCOUNT_NAME, TEMPLATE_CODE, 
                      INITIAL_BALANCE, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, ?, 0, datetime('now'))
ON CONFLICT(USER_ID, ACCOUNT_CODE) 
DO UPDATE SET 
    ACCOUNT_NAME = excluded.ACCOUNT_NAME,
    TEMPLATE_CODE = excluded.TEMPLATE_CODE,
    INITIAL_BALANCE = excluded.INITIAL_BALANCE,
    DISPLAY_ORDER = excluded.DISPLAY_ORDER,
    IS_DISABLED = 0,
    UPDATE_DT = datetime('now')
"#;

pub const ACCOUNT_UPDATE: &str = r#"
UPDATE ACCOUNTS 
SET ACCOUNT_NAME = ?, TEMPLATE_CODE = ?, INITIAL_BALANCE = ?, 
    DISPLAY_ORDER = ?, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND ACCOUNT_CODE = ?
"#;

pub const ACCOUNT_DELETE_LOGICAL: &str = r#"
UPDATE ACCOUNTS 
SET IS_DISABLED = 1, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND ACCOUNT_CODE = ?
"#;

pub const ACCOUNT_GET_NEXT_DISPLAY_ORDER: &str = r#"
SELECT COALESCE(MAX(DISPLAY_ORDER), 0) + 1 as next_order
FROM ACCOUNTS
WHERE USER_ID = ?
"#;

// ============================================================================
// Database Service Queries
// ============================================================================

pub const DB_PRAGMA_WAL: &str = "PRAGMA journal_mode = WAL;";

pub const DB_TEST_CONNECTION: &str = "SELECT 1 as test";

// ============================================================================
// Test-Only Queries (用于测试代码)
// ============================================================================

pub const TEST_AUTH_GET_USER_NAME_BY_ID: &str = "SELECT NAME FROM USERS WHERE USER_ID = 1";

pub const TEST_AUTH_GET_PASSWORD_BY_ID: &str = "SELECT PAW FROM USERS WHERE USER_ID = 1";

pub const TEST_AUTH_GET_ROLE_BY_ID: &str = "SELECT ROLE FROM USERS WHERE USER_ID = 1";

pub const TEST_CREATE_USERS_TABLE: &str = r#"
CREATE TABLE USERS (
    USER_ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    PAW TEXT NOT NULL,
    ROLE INTEGER NOT NULL,
    ENTRY_DT DATETIME NOT NULL,
    UPDATE_DT DATETIME
)
"#;

// Test queries for category service
pub const TEST_CATEGORY_GET_CATEGORY2_NAME: &str = "SELECT CATEGORY2_NAME FROM CATEGORY2 WHERE USER_ID = ? AND CATEGORY2_CODE = ?";

pub const TEST_CATEGORY_GET_CATEGORY2_I18N_NAME: &str = "SELECT CATEGORY2_NAME_I18N FROM CATEGORY2_I18N WHERE USER_ID = ? AND CATEGORY2_CODE = ? AND LANG_CODE = ?";

pub const TEST_CATEGORY_GET_FIRST_CATEGORY2_CODE: &str = "SELECT CATEGORY2_CODE FROM CATEGORY2 WHERE USER_ID = ? LIMIT 1";

pub const TEST_CATEGORY_GET_CATEGORY3_NAME: &str = "SELECT CATEGORY3_NAME FROM CATEGORY3 WHERE USER_ID = ? AND CATEGORY3_CODE = ?";

// Test queries for account service
pub const TEST_ACCOUNT_CREATE_TEMPLATES_TABLE: &str = r#"
CREATE TABLE ACCOUNT_TEMPLATES (
    TEMPLATE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TEMPLATE_CODE VARCHAR(50) NOT NULL UNIQUE,
    TEMPLATE_NAME_JA TEXT NOT NULL,
    TEMPLATE_NAME_EN TEXT NOT NULL,
    DISPLAY_ORDER INTEGER,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now'))
)
"#;

pub const TEST_ACCOUNT_CREATE_ACCOUNTS_TABLE: &str = r#"
CREATE TABLE ACCOUNTS (
    ACCOUNT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    ACCOUNT_CODE VARCHAR(50) NOT NULL,
    ACCOUNT_NAME TEXT NOT NULL,
    TEMPLATE_CODE VARCHAR(50) NOT NULL,
    INITIAL_BALANCE INTEGER DEFAULT 0,
    DISPLAY_ORDER INTEGER,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (TEMPLATE_CODE) REFERENCES ACCOUNT_TEMPLATES(TEMPLATE_CODE),
    UNIQUE(USER_ID, ACCOUNT_CODE)
)
"#;

pub const TEST_ACCOUNT_INSERT_TEMPLATES: &str = r#"
INSERT INTO ACCOUNT_TEMPLATES (TEMPLATE_CODE, TEMPLATE_NAME_JA, TEMPLATE_NAME_EN, DISPLAY_ORDER)
VALUES 
('CASH', '現金', 'Cash', 1),
('BANK', '銀行口座', 'Bank Account', 2)
"#;

pub const TEST_INSERT_USER_ADMIN: &str = "INSERT INTO USERS (USER_ID, NAME, PAW, ROLE, ENTRY_DT) VALUES (1, 'admin', 'dummy', 0, datetime('now'))";

pub const TEST_INSERT_USER_GENERAL: &str = "INSERT INTO USERS (USER_ID, NAME, PAW, ROLE, ENTRY_DT) VALUES (2, 'testuser', 'dummy', 1, datetime('now'))";

pub const TEST_CATEGORY2_GET_DISPLAY_ORDER: &str = "SELECT DISPLAY_ORDER FROM CATEGORY2 WHERE USER_ID = ? AND CATEGORY2_CODE = ?";

pub const TEST_CATEGORY3_GET_DISPLAY_ORDER: &str = "SELECT DISPLAY_ORDER FROM CATEGORY3 WHERE USER_ID = ? AND CATEGORY3_CODE = ?";

pub const TEST_CATEGORY2_COUNT: &str = "SELECT COUNT(*) FROM CATEGORY2 WHERE USER_ID = ?";

pub const TEST_CATEGORY3_COUNT: &str = "SELECT COUNT(*) FROM CATEGORY3 WHERE USER_ID = ?";

pub const TEST_CREATE_CATEGORY2_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS CATEGORY2 (
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(64) NOT NULL,
    CATEGORY2_CODE VARCHAR(64) NOT NULL,
    DISPLAY_ORDER INTEGER NOT NULL,
    CATEGORY2_NAME VARCHAR(128) NOT NULL,
    IS_DISABLED INTEGER NOT NULL DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL,
    UPDATE_DT DATETIME,
    PRIMARY KEY(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE),
    FOREIGN KEY(USER_ID, CATEGORY1_CODE) REFERENCES CATEGORY1(USER_ID, CATEGORY1_CODE) ON DELETE CASCADE
)
"#;

pub const TEST_CREATE_CATEGORY3_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS CATEGORY3 (
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(64) NOT NULL,
    CATEGORY2_CODE VARCHAR(64) NOT NULL,
    CATEGORY3_CODE VARCHAR(64) NOT NULL,
    DISPLAY_ORDER INTEGER NOT NULL,
    CATEGORY3_NAME VARCHAR(128) NOT NULL,
    IS_DISABLED INTEGER NOT NULL DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL,
    UPDATE_DT DATETIME,
    PRIMARY KEY(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE),
    FOREIGN KEY(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE) REFERENCES CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE) ON DELETE CASCADE
)
"#;

pub const TEST_CREATE_CATEGORY1_TABLE: &str = r#"
CREATE TABLE CATEGORY1 (
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(64) NOT NULL,
    CATEGORY1_NAME VARCHAR(128) NOT NULL,
    ENTRY_DT DATETIME NOT NULL,
    UPDATE_DT DATETIME,
    PRIMARY KEY(USER_ID, CATEGORY1_CODE),
    FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
)
"#;

pub const TEST_INSERT_TEST_USER: &str = "INSERT INTO USERS (USER_ID, NAME, PAW, ROLE, ENTRY_DT) VALUES (1, 'testuser', 'hash', 0, datetime('now'))";

pub const TEST_INSERT_CATEGORY1: &str = "INSERT INTO CATEGORY1 (USER_ID, CATEGORY1_CODE, CATEGORY1_NAME, ENTRY_DT) VALUES (1, 'INCOME', '収入', datetime('now'))";

pub const TEST_INSERT_CATEGORY2: &str = "INSERT INTO CATEGORY2 (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY2_NAME, DISPLAY_ORDER, ENTRY_DT) VALUES (1, 'INCOME', 'SALARY', '給料', 0, datetime('now'))";

pub const TEST_INSERT_CATEGORY3: &str = "INSERT INTO CATEGORY3 (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, CATEGORY3_NAME, DISPLAY_ORDER, ENTRY_DT) VALUES (1, 'INCOME', 'SALARY', 'MONTHLY', '月給', 0, datetime('now'))";

pub const TEST_INSERT_TRANSACTION_HEADER: &str = r#"
INSERT INTO TRANSACTIONS_HEADER
(USER_ID, CATEGORY1_CODE, FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE, TRANSACTION_DATE, TOTAL_AMOUNT, ENTRY_DT)
VALUES (1, 'INCOME', 'NONE', 'NONE', datetime('now'), 1000, datetime('now'))
"#;

pub const TEST_CREATE_OLD_TRANSACTIONS_DETAIL_TABLE: &str = r#"
CREATE TABLE TRANSACTIONS_DETAIL (
    DETAIL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TRANSACTION_ID INTEGER NOT NULL,
    CATEGORY2_CODE VARCHAR(50) NOT NULL,
    CATEGORY3_CODE VARCHAR(50) NOT NULL,
    ITEM_NAME TEXT NOT NULL,
    AMOUNT INTEGER NOT NULL,
    TAX_AMOUNT INTEGER DEFAULT 0,
    TAX_RATE INTEGER DEFAULT 8,
    MEMO_ID INTEGER,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS_HEADER(TRANSACTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (MEMO_ID) REFERENCES MEMOS(MEMO_ID),
    CHECK (ITEM_NAME != '')
)
"#;

pub const TEST_INSERT_TRANSACTION_DETAIL: &str = r#"
INSERT INTO TRANSACTIONS_DETAIL
(TRANSACTION_ID, CATEGORY2_CODE, CATEGORY3_CODE, ITEM_NAME, AMOUNT, ENTRY_DT)
VALUES (1, 'SALARY', 'MONTHLY', 'Test Item', 1000, datetime('now'))
"#;

pub const TEST_SELECT_MIGRATED_TRANSACTION_DETAIL: &str = "SELECT DETAIL_ID, TRANSACTION_ID, USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, ITEM_NAME, AMOUNT FROM TRANSACTIONS_DETAIL WHERE DETAIL_ID = 1";

// ============================================================================
// Category Initialization Queries
// ============================================================================

pub const CATEGORY_INSERT_CATEGORY1: &str = r#"
INSERT INTO CATEGORY1 (USER_ID, CATEGORY1_CODE, DISPLAY_ORDER, CATEGORY1_NAME, IS_DISABLED, ENTRY_DT) 
VALUES (?, ?, ?, ?, 0, ?)
"#;

pub const CATEGORY_INSERT_CATEGORY1_I18N: &str = r#"
INSERT INTO CATEGORY1_I18N (USER_ID, CATEGORY1_CODE, LANG_CODE, CATEGORY1_NAME_I18N, ENTRY_DT) 
VALUES (?, ?, ?, ?, ?)
"#;

// ============================================================================
// Test-only Data Setup Queries
// ============================================================================

// Test data setup queries
pub const TEST_CATEGORY_INSERT_CATEGORY1: &str = "INSERT INTO CATEGORY1 (USER_ID, CATEGORY1_CODE, DISPLAY_ORDER, CATEGORY1_NAME, IS_DISABLED, ENTRY_DT) VALUES (?, ?, ?, ?, ?, datetime('now'))";

pub const TEST_CATEGORY_INSERT_CATEGORY1_I18N: &str = "INSERT INTO CATEGORY1_I18N (USER_ID, CATEGORY1_CODE, LANG_CODE, CATEGORY1_NAME_I18N, ENTRY_DT) VALUES (?, ?, ?, ?, datetime('now'))";

pub const TEST_USER_GET_PASSWORD_BY_ID: &str = "SELECT PAW FROM USERS WHERE USER_ID = ?";

// ============================================================================
// Transaction Management Service Queries
// ============================================================================

// Transaction CRUD operations
pub const TRANSACTION_INSERT: &str = r#"
INSERT INTO TRANSACTIONS 
(USER_ID, TRANSACTION_DATE, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, AMOUNT, DESCRIPTION, MEMO, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
"#;

pub const TRANSACTION_SELECT_BY_ID: &str = r#"
SELECT TRANSACTION_ID, USER_ID, TRANSACTION_DATE, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, 
       AMOUNT, DESCRIPTION, MEMO, ENTRY_DT, UPDATE_DT
FROM TRANSACTIONS 
WHERE USER_ID = ? AND TRANSACTION_ID = ?
"#;

pub const TRANSACTION_UPDATE: &str = r#"
UPDATE TRANSACTIONS 
SET TRANSACTION_DATE = ?, CATEGORY1_CODE = ?, CATEGORY2_CODE = ?, CATEGORY3_CODE = ?, 
    AMOUNT = ?, DESCRIPTION = ?, MEMO = ?, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND TRANSACTION_ID = ?
"#;

pub const TRANSACTION_DELETE: &str = r#"
DELETE FROM TRANSACTIONS 
WHERE USER_ID = ? AND TRANSACTION_ID = ?
"#;

// Transaction list queries (base queries - WHERE clause is built dynamically)
pub const TRANSACTION_COUNT_BASE: &str = "SELECT COUNT(*) FROM TRANSACTIONS_HEADER t WHERE ";

pub const TRANSACTION_LIST_BASE: &str = r#"
SELECT
    t.TRANSACTION_ID, t.USER_ID, t.SHOP_ID, t.TRANSACTION_DATE,
    t.CATEGORY1_CODE, t.FROM_ACCOUNT_CODE, t.TO_ACCOUNT_CODE,
    t.TOTAL_AMOUNT, t.TAX_ROUNDING_TYPE, t.MEMO_ID,
    c1.CATEGORY1_NAME,
    a1.ACCOUNT_NAME as FROM_ACCOUNT_NAME,
    a2.ACCOUNT_NAME as TO_ACCOUNT_NAME,
    m.MEMO_TEXT
FROM TRANSACTIONS_HEADER t
LEFT JOIN CATEGORY1 c1 ON t.USER_ID = c1.USER_ID AND t.CATEGORY1_CODE = c1.CATEGORY1_CODE
LEFT JOIN ACCOUNTS a1 ON t.USER_ID = a1.USER_ID AND t.FROM_ACCOUNT_CODE = a1.ACCOUNT_CODE
LEFT JOIN ACCOUNTS a2 ON t.USER_ID = a2.USER_ID AND t.TO_ACCOUNT_CODE = a2.ACCOUNT_CODE
LEFT JOIN MEMOS m ON t.MEMO_ID = m.MEMO_ID
WHERE 
"#;

pub const TRANSACTION_LIST_ORDER: &str = " ORDER BY t.TRANSACTION_DATE DESC, t.TRANSACTION_ID DESC";


// ============================================================================
// Transaction Tables Migration
// ============================================================================

pub const CREATE_MEMOS_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS MEMOS (
    MEMO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    MEMO_TEXT TEXT NOT NULL,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CHECK (MEMO_TEXT != '')
)
"#;

pub const CREATE_TRANSACTIONS_HEADER_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS TRANSACTIONS_HEADER (
    TRANSACTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    SHOP_ID INTEGER,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    FROM_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TO_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TRANSACTION_DATE DATETIME NOT NULL,
    TOTAL_AMOUNT INTEGER NOT NULL,
    TAX_ROUNDING_TYPE INTEGER DEFAULT 0,
    TAX_INCLUDED_TYPE INTEGER DEFAULT 1 NOT NULL,
    MEMO_ID INTEGER,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now', 'localtime')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID, CATEGORY1_CODE) REFERENCES CATEGORY1(USER_ID, CATEGORY1_CODE),
    FOREIGN KEY (USER_ID, FROM_ACCOUNT_CODE) REFERENCES ACCOUNTS(USER_ID, ACCOUNT_CODE),
    FOREIGN KEY (USER_ID, TO_ACCOUNT_CODE) REFERENCES ACCOUNTS(USER_ID, ACCOUNT_CODE)
)
"#;

pub const CREATE_TRANSACTIONS_DETAIL_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS TRANSACTIONS_DETAIL (
    DETAIL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TRANSACTION_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    CATEGORY2_CODE VARCHAR(50) NOT NULL,
    CATEGORY3_CODE VARCHAR(50) NOT NULL,
    ITEM_NAME TEXT NOT NULL,
    AMOUNT INTEGER NOT NULL,
    TAX_AMOUNT INTEGER DEFAULT 0,
    TAX_RATE INTEGER DEFAULT 8,
    MEMO_ID INTEGER,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS_HEADER(TRANSACTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE) REFERENCES CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE),
    FOREIGN KEY (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE) REFERENCES CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE),
    FOREIGN KEY (MEMO_ID) REFERENCES MEMOS(MEMO_ID),
    CHECK (ITEM_NAME != '')
)
"#;

// ============================================================================
// Transaction Detail Table Migration Queries
// ============================================================================

pub const CHECK_TRANSACTIONS_DETAIL_HAS_USER_ID: &str = r#"
SELECT COUNT(*) as count
FROM pragma_table_info('TRANSACTIONS_DETAIL')
WHERE name = 'USER_ID'
"#;

pub const MIGRATE_TRANSACTIONS_DETAIL_CREATE_NEW: &str = r#"
CREATE TABLE TRANSACTIONS_DETAIL_NEW (
    DETAIL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TRANSACTION_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    CATEGORY2_CODE VARCHAR(50) NOT NULL,
    CATEGORY3_CODE VARCHAR(50) NOT NULL,
    ITEM_NAME TEXT NOT NULL,
    AMOUNT INTEGER NOT NULL,
    TAX_AMOUNT INTEGER DEFAULT 0,
    TAX_RATE INTEGER DEFAULT 8,
    MEMO_ID INTEGER,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS_HEADER(TRANSACTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE) REFERENCES CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE),
    FOREIGN KEY (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE) REFERENCES CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE),
    FOREIGN KEY (MEMO_ID) REFERENCES MEMOS(MEMO_ID),
    CHECK (ITEM_NAME != '')
)
"#;

pub const MIGRATE_TRANSACTIONS_DETAIL_COPY_DATA: &str = r#"
INSERT INTO TRANSACTIONS_DETAIL_NEW (
    DETAIL_ID, TRANSACTION_ID, USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE,
    ITEM_NAME, AMOUNT, TAX_AMOUNT, TAX_RATE, MEMO_ID, ENTRY_DT, UPDATE_DT
)
SELECT
    d.DETAIL_ID, d.TRANSACTION_ID, h.USER_ID, h.CATEGORY1_CODE, d.CATEGORY2_CODE, d.CATEGORY3_CODE,
    d.ITEM_NAME, d.AMOUNT, d.TAX_AMOUNT, d.TAX_RATE, d.MEMO_ID, d.ENTRY_DT, d.UPDATE_DT
FROM TRANSACTIONS_DETAIL d
INNER JOIN TRANSACTIONS_HEADER h ON d.TRANSACTION_ID = h.TRANSACTION_ID
"#;

pub const MIGRATE_TRANSACTIONS_DETAIL_DROP_OLD: &str = "DROP TABLE TRANSACTIONS_DETAIL";

pub const MIGRATE_TRANSACTIONS_DETAIL_RENAME_NEW: &str = "ALTER TABLE TRANSACTIONS_DETAIL_NEW RENAME TO TRANSACTIONS_DETAIL";

// ============================================================================
// Unspecified Master Data Insertion
// ============================================================================

pub const INSERT_UNSPECIFIED_ACCOUNT: &str = r#"
INSERT OR IGNORE INTO ACCOUNTS (USER_ID, ACCOUNT_CODE, ACCOUNT_NAME, TEMPLATE_CODE, INITIAL_BALANCE, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT)
VALUES (?, 'NONE', '指定なし', 'NONE', 0, 0, 0, datetime('now'))
"#;

pub const INSERT_UNSPECIFIED_CATEGORY2: &str = r#"
INSERT OR IGNORE INTO CATEGORY2 (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY2_NAME, DISPLAY_ORDER, ENTRY_DT)
SELECT USER_ID, CATEGORY1_CODE, 'NONE', '指定なし', 0, datetime('now')
FROM CATEGORY1
WHERE USER_ID = ?
"#;

pub const INSERT_UNSPECIFIED_CATEGORY3: &str = r#"
INSERT OR IGNORE INTO CATEGORY3 (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE, CATEGORY3_NAME, DISPLAY_ORDER, ENTRY_DT)
SELECT USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, 'NONE', '指定なし', 0, datetime('now')
FROM CATEGORY2
WHERE USER_ID = ?
"#;

// ============================================================================
// Transaction Header Queries
// ============================================================================

pub const TRANSACTION_HEADER_INSERT: &str = r#"
INSERT INTO TRANSACTIONS_HEADER (
    USER_ID, SHOP_ID, TRANSACTION_DATE, CATEGORY1_CODE, FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE,
    TOTAL_AMOUNT, TAX_ROUNDING_TYPE, TAX_INCLUDED_TYPE, MEMO_ID, ENTRY_DT
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
"#;

pub const TRANSACTION_HEADER_GET_BY_ID: &str = r#"
SELECT TRANSACTION_ID, USER_ID, SHOP_ID, TRANSACTION_DATE, CATEGORY1_CODE,
       FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE, TOTAL_AMOUNT, TAX_ROUNDING_TYPE,
       TAX_INCLUDED_TYPE, MEMO_ID, IS_DISABLED, ENTRY_DT, UPDATE_DT
FROM TRANSACTIONS_HEADER
WHERE TRANSACTION_ID = ? AND USER_ID = ?
"#;

pub const TRANSACTION_HEADER_GET_BY_ID_WITH_MEMO: &str = r#"
SELECT
    t.TRANSACTION_ID, t.USER_ID, t.SHOP_ID, t.TRANSACTION_DATE, t.CATEGORY1_CODE,
    t.FROM_ACCOUNT_CODE, t.TO_ACCOUNT_CODE, t.TOTAL_AMOUNT, t.TAX_ROUNDING_TYPE,
    t.TAX_INCLUDED_TYPE, t.MEMO_ID, t.IS_DISABLED, t.ENTRY_DT, t.UPDATE_DT,
    m.MEMO_TEXT
FROM TRANSACTIONS_HEADER t
LEFT JOIN MEMOS m ON t.MEMO_ID = m.MEMO_ID
WHERE t.TRANSACTION_ID = ? AND t.USER_ID = ?
"#;

pub const TRANSACTION_HEADER_UPDATE: &str = r#"
UPDATE TRANSACTIONS_HEADER
SET SHOP_ID = ?, TRANSACTION_DATE = ?, CATEGORY1_CODE = ?, FROM_ACCOUNT_CODE = ?,
    TO_ACCOUNT_CODE = ?, TOTAL_AMOUNT = ?, TAX_ROUNDING_TYPE = ?, TAX_INCLUDED_TYPE = ?,
    MEMO_ID = ?, UPDATE_DT = datetime('now')
WHERE TRANSACTION_ID = ? AND USER_ID = ?
"#;

pub const TRANSACTION_HEADER_DELETE: &str = r#"
DELETE FROM TRANSACTIONS_HEADER
WHERE TRANSACTION_ID = ? AND USER_ID = ?
"#;

// ============================================================================
// Transaction Detail Queries
// ============================================================================

pub const TRANSACTION_DETAIL_INSERT: &str = r#"
INSERT INTO TRANSACTIONS_DETAIL (
    TRANSACTION_ID, CATEGORY2_CODE, CATEGORY3_CODE, ITEM_NAME,
    AMOUNT, TAX_AMOUNT, TAX_RATE, MEMO_ID, ENTRY_DT
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
"#;

pub const TRANSACTION_DETAIL_GET_BY_HEADER: &str = r#"
SELECT DETAIL_ID, TRANSACTION_ID, CATEGORY2_CODE, CATEGORY3_CODE, 
       ITEM_NAME, AMOUNT, TAX_AMOUNT, TAX_RATE, MEMO_ID, ENTRY_DT, UPDATE_DT
FROM TRANSACTIONS_DETAIL
WHERE TRANSACTION_ID = ?
ORDER BY DETAIL_ID
"#;

pub const TRANSACTION_DETAIL_UPDATE: &str = r#"
UPDATE TRANSACTIONS_DETAIL
SET CATEGORY2_CODE = ?, CATEGORY3_CODE = ?, ITEM_NAME = ?,
    AMOUNT = ?, TAX_AMOUNT = ?, TAX_RATE = ?, MEMO_ID = ?,
    UPDATE_DT = datetime('now')
WHERE DETAIL_ID = ? AND TRANSACTION_ID = ?
"#;

pub const TRANSACTION_DETAIL_DELETE: &str = r#"
DELETE FROM TRANSACTIONS_DETAIL
WHERE DETAIL_ID = ?
"#;

// ============================================================================
// Memo Queries
// ============================================================================

pub const MEMO_INSERT: &str = r#"
INSERT INTO MEMOS (USER_ID, MEMO_TEXT, ENTRY_DT)
VALUES (?, ?, datetime('now', 'localtime'))
"#;

pub const MEMO_GET_BY_ID: &str = r#"
SELECT MEMO_ID, MEMO_TEXT, ENTRY_DT, UPDATE_DT
FROM MEMOS
WHERE MEMO_ID = ?
"#;

pub const MEMO_UPDATE: &str = r#"
UPDATE MEMOS
SET MEMO_TEXT = ?, UPDATE_DT = datetime('now', 'localtime')
WHERE MEMO_ID = ?
"#;

pub const MEMO_FIND_BY_TEXT: &str = r#"
SELECT MEMO_ID, MEMO_TEXT, ENTRY_DT, UPDATE_DT
FROM MEMOS
WHERE USER_ID = ? AND MEMO_TEXT = ?
LIMIT 1
"#;

pub const MEMO_DELETE: &str = r#"
DELETE FROM MEMOS WHERE MEMO_ID = ?
"#;

pub const MEMO_COUNT_USAGE: &str = r#"
SELECT COUNT(*) as usage_count
FROM TRANSACTIONS_HEADER
WHERE MEMO_ID = ?
"#;

// ============================================================================
// Shop Service Queries
// ============================================================================

pub const SHOP_GET_ALL: &str = r#"
SELECT SHOP_ID, USER_ID, SHOP_NAME, MEMO, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT, UPDATE_DT
FROM SHOPS
WHERE USER_ID = ? AND IS_DISABLED = 0
ORDER BY DISPLAY_ORDER, SHOP_NAME
"#;

pub const SHOP_GET_BY_ID: &str = r#"
SELECT SHOP_ID, USER_ID, SHOP_NAME, MEMO, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT, UPDATE_DT
FROM SHOPS
WHERE USER_ID = ? AND SHOP_ID = ?
"#;

pub const SHOP_GET_NEXT_DISPLAY_ORDER: &str = r#"
SELECT COALESCE(MAX(DISPLAY_ORDER), 0) + 1
FROM SHOPS
WHERE USER_ID = ?
"#;

pub const SHOP_INSERT: &str = r#"
INSERT INTO SHOPS (USER_ID, SHOP_NAME, MEMO, DISPLAY_ORDER, ENTRY_DT)
VALUES (?, ?, ?, ?, datetime('now'))
"#;

pub const SHOP_UPDATE: &str = r#"
UPDATE SHOPS
SET SHOP_NAME = ?, MEMO = ?, DISPLAY_ORDER = ?, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND SHOP_ID = ?
"#;

pub const SHOP_DELETE_LOGICAL: &str = r#"
UPDATE SHOPS
SET IS_DISABLED = 1, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND SHOP_ID = ?
"#;

pub const SHOP_CHECK_DUPLICATE_FOR_ADD: &str = r#"
SELECT COUNT(*) as count
FROM SHOPS
WHERE USER_ID = ? AND SHOP_NAME = ? AND IS_DISABLED = 0
"#;

pub const SHOP_CHECK_DUPLICATE_FOR_UPDATE: &str = r#"
SELECT COUNT(*) as count
FROM SHOPS
WHERE USER_ID = ? AND SHOP_NAME = ? AND SHOP_ID != ? AND IS_DISABLED = 0
"#;

// ============================================================================
// Manufacturer Service Queries
// ============================================================================

pub const MANUFACTURER_GET_ALL: &str = r#"
SELECT MANUFACTURER_ID, USER_ID, MANUFACTURER_NAME, MEMO, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT, UPDATE_DT
FROM MANUFACTURERS
WHERE USER_ID = ? AND IS_DISABLED = 0
ORDER BY DISPLAY_ORDER, MANUFACTURER_NAME
"#;

pub const MANUFACTURER_GET_ALL_INCLUDING_DISABLED: &str = r#"
SELECT MANUFACTURER_ID, USER_ID, MANUFACTURER_NAME, MEMO, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT, UPDATE_DT
FROM MANUFACTURERS
WHERE USER_ID = ?
ORDER BY DISPLAY_ORDER, MANUFACTURER_NAME
"#;

pub const MANUFACTURER_GET_BY_ID: &str = r#"
SELECT MANUFACTURER_ID, USER_ID, MANUFACTURER_NAME, MEMO, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT, UPDATE_DT
FROM MANUFACTURERS
WHERE USER_ID = ? AND MANUFACTURER_ID = ?
"#;

pub const MANUFACTURER_GET_NEXT_DISPLAY_ORDER: &str = r#"
SELECT COALESCE(MAX(DISPLAY_ORDER), 0) + 1
FROM MANUFACTURERS
WHERE USER_ID = ?
"#;

pub const MANUFACTURER_INSERT: &str = r#"
INSERT INTO MANUFACTURERS (USER_ID, MANUFACTURER_NAME, MEMO, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, datetime('now'))
"#;

pub const MANUFACTURER_UPDATE: &str = r#"
UPDATE MANUFACTURERS
SET MANUFACTURER_NAME = ?, MEMO = ?, DISPLAY_ORDER = ?, IS_DISABLED = ?, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND MANUFACTURER_ID = ?
"#;

pub const MANUFACTURER_DELETE_LOGICAL: &str = r#"
UPDATE MANUFACTURERS
SET IS_DISABLED = 1, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND MANUFACTURER_ID = ?
"#;

pub const MANUFACTURER_CHECK_DUPLICATE_FOR_ADD: &str = r#"
SELECT COUNT(*) as count
FROM MANUFACTURERS
WHERE USER_ID = ? AND MANUFACTURER_NAME = ? AND IS_DISABLED = 0
"#;

pub const MANUFACTURER_CHECK_DUPLICATE_FOR_UPDATE: &str = r#"
SELECT COUNT(*) as count
FROM MANUFACTURERS
WHERE USER_ID = ? AND MANUFACTURER_NAME = ? AND MANUFACTURER_ID != ? AND IS_DISABLED = 0
"#;

// ============================================================================
// Product Service Queries
// ============================================================================

pub const PRODUCT_GET_ALL: &str = r#"
SELECT p.PRODUCT_ID, p.USER_ID, p.PRODUCT_NAME,
       p.MANUFACTURER_ID, m.MANUFACTURER_NAME,
       p.MEMO, p.DISPLAY_ORDER, p.IS_DISABLED, p.ENTRY_DT, p.UPDATE_DT
FROM PRODUCTS p
LEFT JOIN MANUFACTURERS m ON p.MANUFACTURER_ID = m.MANUFACTURER_ID
WHERE p.USER_ID = ? AND p.IS_DISABLED = 0
ORDER BY p.DISPLAY_ORDER, p.PRODUCT_NAME
"#;

pub const PRODUCT_GET_ALL_INCLUDING_DISABLED: &str = r#"
SELECT p.PRODUCT_ID, p.USER_ID, p.PRODUCT_NAME,
       p.MANUFACTURER_ID, m.MANUFACTURER_NAME,
       p.MEMO, p.DISPLAY_ORDER, p.IS_DISABLED, p.ENTRY_DT, p.UPDATE_DT
FROM PRODUCTS p
LEFT JOIN MANUFACTURERS m ON p.MANUFACTURER_ID = m.MANUFACTURER_ID
WHERE p.USER_ID = ?
ORDER BY p.DISPLAY_ORDER, p.PRODUCT_NAME
"#;

pub const PRODUCT_GET_BY_ID: &str = r#"
SELECT p.PRODUCT_ID, p.USER_ID, p.PRODUCT_NAME,
       p.MANUFACTURER_ID, m.MANUFACTURER_NAME,
       p.MEMO, p.DISPLAY_ORDER, p.IS_DISABLED, p.ENTRY_DT, p.UPDATE_DT
FROM PRODUCTS p
LEFT JOIN MANUFACTURERS m ON p.MANUFACTURER_ID = m.MANUFACTURER_ID
WHERE p.USER_ID = ? AND p.PRODUCT_ID = ?
"#;

pub const PRODUCT_GET_NEXT_DISPLAY_ORDER: &str = r#"
SELECT COALESCE(MAX(DISPLAY_ORDER), 0) + 1
FROM PRODUCTS
WHERE USER_ID = ?
"#;

pub const PRODUCT_INSERT: &str = r#"
INSERT INTO PRODUCTS (USER_ID, PRODUCT_NAME, MANUFACTURER_ID, MEMO, DISPLAY_ORDER, IS_DISABLED, ENTRY_DT)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
"#;

pub const PRODUCT_UPDATE: &str = r#"
UPDATE PRODUCTS
SET PRODUCT_NAME = ?, MANUFACTURER_ID = ?, MEMO = ?, DISPLAY_ORDER = ?, IS_DISABLED = ?, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND PRODUCT_ID = ?
"#;

pub const PRODUCT_DELETE_LOGICAL: &str = r#"
UPDATE PRODUCTS
SET IS_DISABLED = 1, UPDATE_DT = datetime('now')
WHERE USER_ID = ? AND PRODUCT_ID = ?
"#;

pub const PRODUCT_CHECK_DUPLICATE_FOR_ADD: &str = r#"
SELECT COUNT(*) as count
FROM PRODUCTS
WHERE USER_ID = ? AND PRODUCT_NAME = ? AND IS_DISABLED = 0
"#;

pub const PRODUCT_CHECK_DUPLICATE_FOR_UPDATE: &str = r#"
SELECT COUNT(*) as count
FROM PRODUCTS
WHERE USER_ID = ? AND PRODUCT_NAME = ? AND PRODUCT_ID != ? AND IS_DISABLED = 0
"#;

// ============================================================================
// Test Queries - Shop
// ============================================================================

pub const TEST_SHOP_CREATE_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS SHOPS (
    SHOP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    SHOP_NAME TEXT NOT NULL,
    MEMO TEXT,
    DISPLAY_ORDER INTEGER NOT NULL DEFAULT 0,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
)
"#;

// ============================================================================
// Test Queries - Manufacturer
// ============================================================================

pub const TEST_MANUFACTURER_CREATE_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS MANUFACTURERS (
    MANUFACTURER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    MANUFACTURER_NAME TEXT NOT NULL,
    MEMO TEXT,
    DISPLAY_ORDER INTEGER NOT NULL DEFAULT 0,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    UNIQUE(USER_ID, MANUFACTURER_NAME)
)
"#;

// ============================================================================
// Test Queries - Product
// ============================================================================

pub const TEST_PRODUCT_CREATE_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    PRODUCT_NAME TEXT NOT NULL,
    MANUFACTURER_ID INTEGER,
    MEMO TEXT,
    DISPLAY_ORDER INTEGER NOT NULL DEFAULT 0,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURERS(MANUFACTURER_ID) ON DELETE SET NULL,
    UNIQUE(USER_ID, PRODUCT_NAME)
)
"#;

// ============================================================================
// Transaction Detail Management Queries (with JOIN)
// ============================================================================

pub const TRANSACTION_HEADER_GET_WITH_INFO: &str = r#"
SELECT 
    h.TRANSACTION_ID,
    h.USER_ID,
    h.SHOP_ID,
    s.SHOP_NAME,
    h.TRANSACTION_DATE,
    h.CATEGORY1_CODE,
    h.FROM_ACCOUNT_CODE,
    h.TO_ACCOUNT_CODE,
    fa.ACCOUNT_NAME as FROM_ACCOUNT_NAME,
    ta.ACCOUNT_NAME as TO_ACCOUNT_NAME,
    h.TOTAL_AMOUNT,
    h.TAX_ROUNDING_TYPE,
    h.TAX_INCLUDED_TYPE,
    h.MEMO_ID,
    m.MEMO_TEXT,
    h.IS_DISABLED,
    h.ENTRY_DT,
    h.UPDATE_DT
FROM TRANSACTIONS_HEADER h
LEFT JOIN SHOPS s ON h.SHOP_ID = s.SHOP_ID
LEFT JOIN ACCOUNTS fa ON h.FROM_ACCOUNT_CODE = fa.ACCOUNT_CODE AND h.USER_ID = fa.USER_ID
LEFT JOIN ACCOUNTS ta ON h.TO_ACCOUNT_CODE = ta.ACCOUNT_CODE AND h.USER_ID = ta.USER_ID
LEFT JOIN MEMOS m ON h.MEMO_ID = m.MEMO_ID
WHERE h.TRANSACTION_ID = ? AND h.USER_ID = ?
"#;

pub const TRANSACTION_DETAIL_GET_WITH_INFO: &str = r#"
SELECT 
    d.DETAIL_ID,
    d.TRANSACTION_ID,
    d.USER_ID,
    d.CATEGORY1_CODE,
    d.CATEGORY2_CODE,
    d.CATEGORY3_CODE,
    c1.CATEGORY1_NAME,
    c2.CATEGORY2_NAME,
    c3.CATEGORY3_NAME,
    d.ITEM_NAME,
    d.AMOUNT,
    d.TAX_AMOUNT,
    d.TAX_RATE,
    d.AMOUNT_INCLUDING_TAX,
    d.MEMO_ID,
    m.MEMO_TEXT,
    d.ENTRY_DT,
    d.UPDATE_DT
FROM TRANSACTIONS_DETAIL d
LEFT JOIN CATEGORY1 c1 ON d.CATEGORY1_CODE = c1.CATEGORY1_CODE AND d.USER_ID = c1.USER_ID
LEFT JOIN CATEGORY2 c2 ON d.CATEGORY1_CODE = c2.CATEGORY1_CODE 
    AND d.CATEGORY2_CODE = c2.CATEGORY2_CODE AND d.USER_ID = c2.USER_ID
LEFT JOIN CATEGORY3 c3 ON d.CATEGORY1_CODE = c3.CATEGORY1_CODE 
    AND d.CATEGORY2_CODE = c3.CATEGORY2_CODE 
    AND d.CATEGORY3_CODE = c3.CATEGORY3_CODE AND d.USER_ID = c3.USER_ID
LEFT JOIN MEMOS m ON d.MEMO_ID = m.MEMO_ID
WHERE d.TRANSACTION_ID = ? AND d.USER_ID = ?
ORDER BY d.DETAIL_ID
"#;

pub const TRANSACTION_DETAIL_INSERT_FULL: &str = r#"
INSERT INTO TRANSACTIONS_DETAIL (
    TRANSACTION_ID, USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE,
    ITEM_NAME, AMOUNT, TAX_AMOUNT, TAX_RATE, AMOUNT_INCLUDING_TAX, MEMO_ID
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
"#;

pub const TRANSACTION_DETAIL_UPDATE_FULL: &str = r#"
UPDATE TRANSACTIONS_DETAIL SET
    CATEGORY1_CODE = ?,
    CATEGORY2_CODE = ?,
    CATEGORY3_CODE = ?,
    ITEM_NAME = ?,
    AMOUNT = ?,
    TAX_AMOUNT = ?,
    TAX_RATE = ?,
    AMOUNT_INCLUDING_TAX = ?,
    MEMO_ID = ?,
    UPDATE_DT = datetime('now')
WHERE DETAIL_ID = ? AND USER_ID = ?
"#;

pub const TRANSACTION_DETAIL_GET_BY_ID: &str = r#"
SELECT DETAIL_ID, TRANSACTION_ID, USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE,
       ITEM_NAME, AMOUNT, TAX_AMOUNT, TAX_RATE, AMOUNT_INCLUDING_TAX, MEMO_ID, ENTRY_DT, UPDATE_DT
FROM TRANSACTIONS_DETAIL
WHERE DETAIL_ID = ? AND USER_ID = ?
"#;

pub const TRANSACTION_DETAIL_DELETE_BY_ID: &str = r#"
DELETE FROM TRANSACTIONS_DETAIL
WHERE DETAIL_ID = ? AND USER_ID = ?
"#;

// ============================================================================
// Transaction Service Test Queries
// ============================================================================

pub const TEST_TRANSACTION_CREATE_USERS_TABLE: &str = r#"
CREATE TABLE USERS (
    USER_ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    PAW TEXT NOT NULL,
    ROLE INTEGER NOT NULL,
    ENTRY_DT DATETIME NOT NULL,
    UPDATE_DT DATETIME
)
"#;

pub const TEST_TRANSACTION_INSERT_USER: &str = "INSERT INTO USERS (USER_ID, NAME, PAW, ROLE, ENTRY_DT) VALUES (2, 'testuser', 'hash', 1, datetime('now'))";

pub const TEST_TRANSACTION_CREATE_MEMOS_TABLE: &str = r#"
CREATE TABLE MEMOS (
    MEMO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    MEMO_TEXT TEXT NOT NULL,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
)
"#;

pub const TEST_TRANSACTION_CREATE_CATEGORY1_TABLE: &str = r#"
CREATE TABLE CATEGORY1 (
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    CATEGORY1_NAME TEXT NOT NULL,
    DISPLAY_ORDER INTEGER DEFAULT 0,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    PRIMARY KEY (USER_ID, CATEGORY1_CODE)
)
"#;

pub const TEST_TRANSACTION_INSERT_CATEGORY1: &str = "INSERT INTO CATEGORY1 (USER_ID, CATEGORY1_CODE, CATEGORY1_NAME) VALUES (2, 'EXPENSE', '支出')";

pub const TEST_TRANSACTION_CREATE_ACCOUNTS_TABLE: &str = r#"
CREATE TABLE ACCOUNTS (
    ACCOUNT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    ACCOUNT_CODE VARCHAR(50) NOT NULL,
    ACCOUNT_NAME TEXT NOT NULL,
    TEMPLATE_CODE VARCHAR(50) NOT NULL,
    INITIAL_BALANCE INTEGER DEFAULT 0,
    DISPLAY_ORDER INTEGER DEFAULT 0,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    UNIQUE(USER_ID, ACCOUNT_CODE)
)
"#;

pub const TEST_TRANSACTION_INSERT_ACCOUNT_CASH: &str = "INSERT INTO ACCOUNTS (USER_ID, ACCOUNT_CODE, ACCOUNT_NAME, TEMPLATE_CODE) VALUES (2, 'CASH', '現金', 'CASH')";

pub const TEST_TRANSACTION_INSERT_ACCOUNT_BANK: &str = "INSERT INTO ACCOUNTS (USER_ID, ACCOUNT_CODE, ACCOUNT_NAME, TEMPLATE_CODE) VALUES (2, 'BANK', '銀行', 'BANK')";

pub const TEST_TRANSACTION_CREATE_HEADER_TABLE: &str = r#"
CREATE TABLE TRANSACTIONS_HEADER (
    TRANSACTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    SHOP_ID INTEGER,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    FROM_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TO_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TRANSACTION_DATE DATETIME NOT NULL,
    TOTAL_AMOUNT INTEGER NOT NULL,
    TAX_ROUNDING_TYPE INTEGER DEFAULT 0,
    TAX_INCLUDED_TYPE INTEGER DEFAULT 1 NOT NULL,
    MEMO_ID INTEGER,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME
)
"#;

pub const TEST_TRANSACTION_CREATE_SHOPS_TABLE: &str = r#"
CREATE TABLE SHOPS (
    SHOP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    SHOP_NAME TEXT NOT NULL,
    MEMO TEXT,
    DISPLAY_ORDER INTEGER DEFAULT 0,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME
)
"#;

