-- Create TRANSACTIONS_HEADER table
-- This table stores transaction header information
-- Created: 2025-01-07
-- Updated: 2025-11-08 - Changed TRANSACTION_DATE to DATETIME, TAX_RATE moved to TRANSACTIONS_DETAIL

CREATE TABLE IF NOT EXISTS TRANSACTIONS_HEADER (
    TRANSACTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    SHOP_ID INTEGER,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    FROM_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TO_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TRANSACTION_DATE DATETIME NOT NULL,
    TOTAL_AMOUNT INTEGER NOT NULL,
    TAX_ROUNDING_TYPE INTEGER DEFAULT 0,  -- 0: Round down, 1: Round half, 2: Round up
    MEMO_ID INTEGER,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID, CATEGORY1_CODE) REFERENCES CATEGORY1(USER_ID, CATEGORY1_CODE),
    FOREIGN KEY (USER_ID, FROM_ACCOUNT_CODE) REFERENCES ACCOUNTS(USER_ID, ACCOUNT_CODE),
    FOREIGN KEY (USER_ID, TO_ACCOUNT_CODE) REFERENCES ACCOUNTS(USER_ID, ACCOUNT_CODE),
    FOREIGN KEY (MEMO_ID) REFERENCES MEMOS(MEMO_ID)
);

-- Create indexes for TRANSACTIONS_HEADER
CREATE INDEX IF NOT EXISTS idx_transactions_header_user 
    ON TRANSACTIONS_HEADER(USER_ID, TRANSACTION_DATE);
CREATE INDEX IF NOT EXISTS idx_transactions_header_accounts 
    ON TRANSACTIONS_HEADER(FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE);
CREATE INDEX IF NOT EXISTS idx_transactions_header_category 
    ON TRANSACTIONS_HEADER(CATEGORY1_CODE);
CREATE INDEX IF NOT EXISTS idx_transactions_header_date 
    ON TRANSACTIONS_HEADER(TRANSACTION_DATE);
