-- Create TRANSACTIONS_DETAIL table
-- This table stores transaction detail (item-level) information
-- Created: 2025-01-07
-- Updated: 2025-11-17 - Added USER_ID, CATEGORY1_CODE, AMOUNT_INCLUDING_TAX
-- Updated: 2025-11-18 - Removed MEMO_ID foreign key constraint (MEMO_ID is now a simple reference)

CREATE TABLE IF NOT EXISTS TRANSACTIONS_DETAIL (
    DETAIL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TRANSACTION_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    CATEGORY2_CODE VARCHAR(50) NOT NULL,
    CATEGORY3_CODE VARCHAR(50) NOT NULL,
    ITEM_NAME TEXT NOT NULL,
    AMOUNT INTEGER NOT NULL,
    TAX_AMOUNT INTEGER DEFAULT 0,
    TAX_RATE INTEGER DEFAULT 8,  -- Default 8% for food items
    AMOUNT_INCLUDING_TAX INTEGER,
    MEMO_ID INTEGER,  -- Simple reference, no foreign key constraint
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now', 'localtime')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS_HEADER(TRANSACTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE) REFERENCES CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE),
    FOREIGN KEY (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE) REFERENCES CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE),
    CHECK (ITEM_NAME != '')  -- Item name cannot be empty
);

-- Create indexes for TRANSACTIONS_DETAIL
CREATE INDEX IF NOT EXISTS idx_transactions_detail_transaction 
    ON TRANSACTIONS_DETAIL(TRANSACTION_ID);
CREATE INDEX IF NOT EXISTS idx_transactions_detail_categories 
    ON TRANSACTIONS_DETAIL(CATEGORY2_CODE, CATEGORY3_CODE);
