-- Create ACCOUNT_TEMPLATES and ACCOUNTS tables
-- Phase 0: Account Master Management (Template-based approach)
-- Date: 2025-11-07

-- Account Templates (Master data, not user-specific)
CREATE TABLE ACCOUNT_TEMPLATES (
    TEMPLATE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TEMPLATE_CODE VARCHAR(50) NOT NULL UNIQUE,
    TEMPLATE_NAME_JA TEXT NOT NULL,
    TEMPLATE_NAME_EN TEXT NOT NULL,
    DISPLAY_ORDER INTEGER,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now'))
);

-- Insert default templates
INSERT INTO ACCOUNT_TEMPLATES (TEMPLATE_CODE, TEMPLATE_NAME_JA, TEMPLATE_NAME_EN, DISPLAY_ORDER) VALUES
('CASH', '現金', 'Cash', 1),
('BANK', '銀行口座', 'Bank Account', 2),
('CREDIT', 'クレジットカード', 'Credit Card', 3),
('DEBIT', 'デビットカード', 'Debit Card', 4),
('ELECTRONIC', '電子マネー', 'Electronic Money', 5);

-- User Accounts (derived from templates)
CREATE TABLE ACCOUNTS (
    ACCOUNT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    ACCOUNT_CODE VARCHAR(50) NOT NULL,
    ACCOUNT_NAME TEXT NOT NULL,
    TEMPLATE_CODE VARCHAR(50) NOT NULL,
    INITIAL_BALANCE INTEGER DEFAULT 0,
    DISPLAY_ORDER INTEGER,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (TEMPLATE_CODE) REFERENCES ACCOUNT_TEMPLATES(TEMPLATE_CODE),
    UNIQUE(USER_ID, ACCOUNT_CODE)
);

CREATE INDEX idx_accounts_user ON ACCOUNTS(USER_ID, ACCOUNT_CODE);
CREATE INDEX idx_accounts_user_order ON ACCOUNTS(USER_ID, DISPLAY_ORDER);
CREATE INDEX idx_accounts_template ON ACCOUNTS(TEMPLATE_CODE);

