-- Fix foreign key constraints in TRANSACTIONS_HEADER table
-- Drop and recreate the table with correct foreign keys
-- Date: 2025-11-07

-- Drop existing table (no data loss risk - table is empty)
DROP TABLE IF EXISTS TRANSACTIONS_HEADER;

-- Recreate with correct foreign keys
CREATE TABLE TRANSACTIONS_HEADER (
    TRANSACTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    FROM_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TO_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    TOTAL_AMOUNT INTEGER NOT NULL,
    TAX_ROUNDING_TYPE INTEGER DEFAULT 0,  -- 0: Round down, 1: Round half-up, 2: Round up
    MEMO_ID INTEGER,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID, CATEGORY1_CODE) REFERENCES CATEGORY1(USER_ID, CATEGORY1_CODE),
    FOREIGN KEY (USER_ID, FROM_ACCOUNT_CODE) REFERENCES ACCOUNTS(USER_ID, ACCOUNT_CODE),
    FOREIGN KEY (USER_ID, TO_ACCOUNT_CODE) REFERENCES ACCOUNTS(USER_ID, ACCOUNT_CODE),
    FOREIGN KEY (MEMO_ID) REFERENCES MEMOS(MEMO_ID)
);

-- Recreate indexes
CREATE INDEX idx_transactions_header_user 
    ON TRANSACTIONS_HEADER(USER_ID, TRANSACTION_DATE);
CREATE INDEX idx_transactions_header_accounts 
    ON TRANSACTIONS_HEADER(FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE);
CREATE INDEX idx_transactions_header_category 
    ON TRANSACTIONS_HEADER(CATEGORY1_CODE);
CREATE INDEX idx_transactions_header_date 
    ON TRANSACTIONS_HEADER(TRANSACTION_DATE);
