-- Fix MEMO foreign key constraints
-- Change direction: TRANSACTIONS_HEADER/DETAIL -> MEMOS to proper parent-child relationship
-- Date: 2025-11-18

-- Disable foreign keys temporarily
PRAGMA foreign_keys = OFF;

BEGIN TRANSACTION;

-- Step 1: Backup existing data
CREATE TABLE TRANSACTIONS_HEADER_BACKUP AS SELECT * FROM TRANSACTIONS_HEADER;
CREATE TABLE TRANSACTIONS_DETAIL_BACKUP AS SELECT * FROM TRANSACTIONS_DETAIL;

-- Step 2: Drop old tables
DROP TABLE TRANSACTIONS_DETAIL;
DROP TABLE TRANSACTIONS_HEADER;

-- Step 3: Recreate TRANSACTIONS_HEADER without MEMO_ID foreign key
CREATE TABLE IF NOT EXISTS "TRANSACTIONS_HEADER" (
    TRANSACTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    SHOP_ID INTEGER,
    TRANSACTION_DATE DATE NOT NULL,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    FROM_ACCOUNT_CODE VARCHAR(50),
    TO_ACCOUNT_CODE VARCHAR(50),
    TOTAL_AMOUNT INTEGER NOT NULL DEFAULT 0,
    TAX_ROUNDING_TYPE INTEGER DEFAULT 0,
    TAX_INCLUDED_TYPE INTEGER DEFAULT 0,
    MEMO_ID INTEGER,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now', 'localtime')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID, CATEGORY1_CODE) REFERENCES CATEGORY1(USER_ID, CATEGORY1_CODE),
    FOREIGN KEY (USER_ID, FROM_ACCOUNT_CODE) REFERENCES ACCOUNTS(USER_ID, ACCOUNT_CODE),
    FOREIGN KEY (USER_ID, TO_ACCOUNT_CODE) REFERENCES ACCOUNTS(USER_ID, ACCOUNT_CODE)
);

-- Step 4: Recreate TRANSACTIONS_DETAIL without MEMO_ID foreign key
CREATE TABLE IF NOT EXISTS "TRANSACTIONS_DETAIL" (
    DETAIL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TRANSACTION_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    CATEGORY2_CODE VARCHAR(50) NOT NULL,
    CATEGORY3_CODE VARCHAR(50) NOT NULL,
    ITEM_NAME TEXT NOT NULL,
    AMOUNT INTEGER NOT NULL,
    TAX_AMOUNT INTEGER DEFAULT 0,
    TAX_RATE INTEGER DEFAULT 8,
    AMOUNT_INCLUDING_TAX INTEGER,
    MEMO_ID INTEGER,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now', 'localtime')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS_HEADER(TRANSACTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE) REFERENCES CATEGORY2(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE),
    FOREIGN KEY (USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE) REFERENCES CATEGORY3(USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE),
    CHECK (ITEM_NAME != '')
);

-- Step 5: Restore data (map columns explicitly to handle defaults)
INSERT INTO TRANSACTIONS_HEADER (
    TRANSACTION_ID, USER_ID, SHOP_ID, TRANSACTION_DATE, CATEGORY1_CODE,
    FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE, TOTAL_AMOUNT, TAX_ROUNDING_TYPE,
    TAX_INCLUDED_TYPE, MEMO_ID, IS_DISABLED, ENTRY_DT, UPDATE_DT
) SELECT 
    TRANSACTION_ID, USER_ID, SHOP_ID, TRANSACTION_DATE, CATEGORY1_CODE,
    FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE, TOTAL_AMOUNT, TAX_ROUNDING_TYPE,
    COALESCE(TAX_INCLUDED_TYPE, 0), MEMO_ID, IS_DISABLED,
    COALESCE(ENTRY_DT, datetime('now', 'localtime')),
    UPDATE_DT
FROM TRANSACTIONS_HEADER_BACKUP;

INSERT INTO TRANSACTIONS_DETAIL (
    DETAIL_ID, TRANSACTION_ID, USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE,
    ITEM_NAME, AMOUNT, TAX_AMOUNT, TAX_RATE, AMOUNT_INCLUDING_TAX, MEMO_ID,
    ENTRY_DT, UPDATE_DT
) SELECT 
    DETAIL_ID, TRANSACTION_ID, USER_ID, CATEGORY1_CODE, CATEGORY2_CODE, CATEGORY3_CODE,
    ITEM_NAME, AMOUNT, TAX_AMOUNT, TAX_RATE, AMOUNT_INCLUDING_TAX, MEMO_ID,
    COALESCE(ENTRY_DT, datetime('now', 'localtime')),
    UPDATE_DT
FROM TRANSACTIONS_DETAIL_BACKUP;

-- Step 6: Recreate indexes
CREATE INDEX idx_transactions_header_date ON TRANSACTIONS_HEADER(TRANSACTION_DATE);
CREATE INDEX idx_transactions_header_user ON TRANSACTIONS_HEADER(USER_ID);
CREATE INDEX idx_transactions_header_category ON TRANSACTIONS_HEADER(CATEGORY1_CODE);
CREATE INDEX idx_transactions_header_account ON TRANSACTIONS_HEADER(FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE);

CREATE INDEX idx_transactions_detail_transaction ON TRANSACTIONS_DETAIL(TRANSACTION_ID);
CREATE INDEX idx_transactions_detail_categories ON TRANSACTIONS_DETAIL(CATEGORY2_CODE, CATEGORY3_CODE);

-- Step 7: Drop backup tables
DROP TABLE TRANSACTIONS_HEADER_BACKUP;
DROP TABLE TRANSACTIONS_DETAIL_BACKUP;

COMMIT;

-- Re-enable foreign keys
PRAGMA foreign_keys = ON;

-- Verify foreign keys
PRAGMA foreign_key_check;
