-- Insert default accounts for existing users
-- Date: 2025-11-07

-- Insert accounts for User 1 (BonoJovi)
INSERT INTO ACCOUNTS (USER_ID, ACCOUNT_CODE, ACCOUNT_NAME, TEMPLATE_CODE, INITIAL_BALANCE, DISPLAY_ORDER)
SELECT 1, TEMPLATE_CODE, TEMPLATE_NAME_JA, TEMPLATE_CODE, 0, DISPLAY_ORDER
FROM ACCOUNT_TEMPLATES
WHERE NOT EXISTS (SELECT 1 FROM ACCOUNTS WHERE USER_ID = 1 AND ACCOUNT_CODE = ACCOUNT_TEMPLATES.TEMPLATE_CODE);

-- Insert accounts for User 2 (JuiceA)
INSERT INTO ACCOUNTS (USER_ID, ACCOUNT_CODE, ACCOUNT_NAME, TEMPLATE_CODE, INITIAL_BALANCE, DISPLAY_ORDER)
SELECT 2, TEMPLATE_CODE, TEMPLATE_NAME_JA, TEMPLATE_CODE, 0, DISPLAY_ORDER
FROM ACCOUNT_TEMPLATES
WHERE NOT EXISTS (SELECT 1 FROM ACCOUNTS WHERE USER_ID = 2 AND ACCOUNT_CODE = ACCOUNT_TEMPLATES.TEMPLATE_CODE);
