-- Migrate TRANSACTIONS_HEADER.TRANSACTION_DATE from DATE to DATETIME
-- Date: 2025-11-08
-- Purpose: Add time (hour:minute) support to transaction dates

-- Create temporary table with new schema
CREATE TABLE TRANSACTIONS_HEADER_NEW (
    TRANSACTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    CATEGORY1_CODE VARCHAR(50) NOT NULL,
    FROM_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TO_ACCOUNT_CODE VARCHAR(50) NOT NULL,
    TRANSACTION_DATE DATETIME NOT NULL,
    TOTAL_AMOUNT INTEGER NOT NULL,
    TAX_ROUNDING_TYPE INTEGER DEFAULT 0,
    MEMO_ID INTEGER,
    IS_DISABLED INTEGER DEFAULT 0,
    ENTRY_DT DATETIME NOT NULL DEFAULT (datetime('now')),
    UPDATE_DT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID, CATEGORY1_CODE) REFERENCES CATEGORY1(USER_ID, CATEGORY1_CODE),
    FOREIGN KEY (USER_ID, FROM_ACCOUNT_CODE) REFERENCES ACCOUNTS(USER_ID, ACCOUNT_CODE),
    FOREIGN KEY (USER_ID, TO_ACCOUNT_CODE) REFERENCES ACCOUNTS(USER_ID, ACCOUNT_CODE),
    FOREIGN KEY (MEMO_ID) REFERENCES MEMOS(MEMO_ID)
);

-- Copy data from old table, converting DATE to DATETIME (add 00:00:00)
INSERT INTO TRANSACTIONS_HEADER_NEW (
    TRANSACTION_ID, USER_ID, CATEGORY1_CODE, FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE,
    TRANSACTION_DATE, TOTAL_AMOUNT, TAX_ROUNDING_TYPE, MEMO_ID, IS_DISABLED,
    ENTRY_DT, UPDATE_DT
)
SELECT 
    TRANSACTION_ID, USER_ID, CATEGORY1_CODE, FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE,
    datetime(TRANSACTION_DATE || ' 00:00:00') as TRANSACTION_DATE,
    TOTAL_AMOUNT, TAX_ROUNDING_TYPE, MEMO_ID, IS_DISABLED,
    ENTRY_DT, UPDATE_DT
FROM TRANSACTIONS_HEADER;

-- Drop old table
DROP TABLE TRANSACTIONS_HEADER;

-- Rename new table
ALTER TABLE TRANSACTIONS_HEADER_NEW RENAME TO TRANSACTIONS_HEADER;

-- Recreate indexes
CREATE INDEX idx_transactions_header_user 
    ON TRANSACTIONS_HEADER(USER_ID, TRANSACTION_DATE);
CREATE INDEX idx_transactions_header_accounts 
    ON TRANSACTIONS_HEADER(FROM_ACCOUNT_CODE, TO_ACCOUNT_CODE);
CREATE INDEX idx_transactions_header_category 
    ON TRANSACTIONS_HEADER(CATEGORY1_CODE);
CREATE INDEX idx_transactions_header_date 
    ON TRANSACTIONS_HEADER(TRANSACTION_DATE);
